/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type _GetApiMarketplaceV2SearchResultBoundAnyOfSouthWest = {
    lat: number;
    lng: number;
};
