/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCustomerGroupsId404Error } from './deleteApiCustomerGroupsId404Error';

export type DeleteApiCustomerGroupsId404 = {
    statusCode: number;
    error: DeleteApiCustomerGroupsId404Error;
    message: string;
};
