/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiDoctorsPortalDoctorsDoctorUuid404Error } from './deleteApiDoctorsPortalDoctorsDoctorUuid404Error';

export type DeleteApiDoctorsPortalDoctorsDoctorUuid404 = {
    statusCode: number;
    error: DeleteApiDoctorsPortalDoctorsDoctorUuid404Error;
    message: string;
};
