/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiDoctorsPortalDoctorsDoctorUuid500Error =
    (typeof DeleteApiDoctorsPortalDoctorsDoctorUuid500Error)[keyof typeof DeleteApiDoctorsPortalDoctorsDoctorUuid500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiDoctorsPortalDoctorsDoctorUuid500Error = {
    Bad_Request: 'Bad Request',
} as const;
