/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiHealthDeclarationTemplateId200Data } from './deleteApiHealthDeclarationTemplateId200Data';

export type DeleteApiHealthDeclarationTemplateId200 = {
    statusCode: number;
    message: string;
    success: boolean;
    data: DeleteApiHealthDeclarationTemplateId200Data;
};
