/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiHealthDeclarationTemplateId404Error } from './deleteApiHealthDeclarationTemplateId404Error';

export type DeleteApiHealthDeclarationTemplateId404 = {
    statusCode: number;
    error: DeleteApiHealthDeclarationTemplateId404Error;
    message: string;
};
