/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiPaymentsSubscriptionDelete400Error =
    (typeof DeleteApiPaymentsSubscriptionDelete400Error)[keyof typeof DeleteApiPaymentsSubscriptionDelete400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiPaymentsSubscriptionDelete400Error = {
    Bad_Request: 'Bad Request',
} as const;
