/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiExpenseId500Error = (typeof DeleteApiExpenseId500Error)[keyof typeof DeleteApiExpenseId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiExpenseId500Error = {
    Bad_Request: 'Bad Request',
} as const;
