/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiAddonsAddonId400Error =
    (typeof DeleteApiAddonsAddonId400Error)[keyof typeof DeleteApiAddonsAddonId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiAddonsAddonId400Error = {
    Bad_Request: 'Bad Request',
} as const;
