/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiFiles500Error } from './deleteApiFiles500Error';

export type DeleteApiFiles500 = {
    statusCode: number;
    error: DeleteApiFiles500Error;
    message: string;
};
