/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiPaymentsSubscriptionDelete403Error } from './deleteApiPaymentsSubscriptionDelete403Error';

export type DeleteApiPaymentsSubscriptionDelete403 = {
    statusCode: number;
    error: DeleteApiPaymentsSubscriptionDelete403Error;
    message: string;
};
