/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiExpenseId404Error } from './deleteApiExpenseId404Error';

export type DeleteApiExpenseId404 = {
    statusCode: number;
    error: DeleteApiExpenseId404Error;
    message: string;
};
