/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiFiles500Error = (typeof DeleteApiFiles500Error)[keyof typeof DeleteApiFiles500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiFiles500Error = {
    Bad_Request: 'Bad Request',
} as const;
