/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCalendlyWebhookSubscriptions401Error } from './deleteApiCalendlyWebhookSubscriptions401Error';

export type DeleteApiCalendlyWebhookSubscriptions401 = {
    statusCode: number;
    error: DeleteApiCalendlyWebhookSubscriptions401Error;
    message: string;
};
