/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiSupplierId400Error } from './deleteApiSupplierId400Error';

export type DeleteApiSupplierId400 = {
    statusCode: number;
    error: DeleteApiSupplierId400Error;
    message: string;
};
