/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiPaymentsSubscriptionDelete200Data } from './deleteApiPaymentsSubscriptionDelete200Data';

export type DeleteApiPaymentsSubscriptionDelete200 = {
    success?: boolean;
    data?: DeleteApiPaymentsSubscriptionDelete200Data;
    message?: string;
};
