/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiSupplierId500Error } from './deleteApiSupplierId500Error';

export type DeleteApiSupplierId500 = {
    statusCode: number;
    error: DeleteApiSupplierId500Error;
    message: string;
};
