/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiAddonsAddonId500Error =
    (typeof DeleteApiAddonsAddonId500Error)[keyof typeof DeleteApiAddonsAddonId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiAddonsAddonId500Error = {
    Bad_Request: 'Bad Request',
} as const;
