/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCustomerGroupsId500Error } from './deleteApiCustomerGroupsId500Error';

export type DeleteApiCustomerGroupsId500 = {
    statusCode: number;
    error: DeleteApiCustomerGroupsId500Error;
    message: string;
};
