/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiServiceAdvancedReminderTemplatesReminderTemplateId404Error } from './deleteApiServiceAdvancedReminderTemplatesReminderTemplateId404Error';

export type DeleteApiServiceAdvancedReminderTemplatesReminderTemplateId404 = {
    statusCode: number;
    error: DeleteApiServiceAdvancedReminderTemplatesReminderTemplateId404Error;
    message: string;
};
