/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiServiceSubscriptionId404Error } from './deleteApiServiceSubscriptionId404Error';

export type DeleteApiServiceSubscriptionId404 = {
    statusCode: number;
    error: DeleteApiServiceSubscriptionId404Error;
    message: string;
};
