/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCustomerGroupsIdCustomers500Error } from './deleteApiCustomerGroupsIdCustomers500Error';

export type DeleteApiCustomerGroupsIdCustomers500 = {
    statusCode: number;
    error: DeleteApiCustomerGroupsIdCustomers500Error;
    message: string;
};
