/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiHealthDeclarationTemplateId404Error =
    (typeof DeleteApiHealthDeclarationTemplateId404Error)[keyof typeof DeleteApiHealthDeclarationTemplateId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiHealthDeclarationTemplateId404Error = {
    Bad_Request: 'Bad Request',
} as const;
