/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiCalendlyWebhookSubscriptions401Error =
    (typeof DeleteApiCalendlyWebhookSubscriptions401Error)[keyof typeof DeleteApiCalendlyWebhookSubscriptions401Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiCalendlyWebhookSubscriptions401Error = {
    Bad_Request: 'Bad Request',
} as const;
