/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCalendlyWebhookSubscriptions500Error } from './deleteApiCalendlyWebhookSubscriptions500Error';

export type DeleteApiCalendlyWebhookSubscriptions500 = {
    statusCode: number;
    error: DeleteApiCalendlyWebhookSubscriptions500Error;
    message: string;
};
