/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiWebhooksId404Error } from './deleteApiWebhooksId404Error';

export type DeleteApiWebhooksId404 = {
    statusCode: number;
    error: DeleteApiWebhooksId404Error;
    message: string;
};
