/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiServiceSubscriptionId500Error } from './deleteApiServiceSubscriptionId500Error';

export type DeleteApiServiceSubscriptionId500 = {
    statusCode: number;
    error: DeleteApiServiceSubscriptionId500Error;
    message: string;
};
