/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCampaignsId200Description } from './deleteApiCampaignsId200Description';
import type { DeleteApiCampaignsId200DeletedAt } from './deleteApiCampaignsId200DeletedAt';

export type DeleteApiCampaignsId200 = {
    id?: string;
    outletId?: number;
    name?: string;
    description?: DeleteApiCampaignsId200Description;
    messageType?: string;
    campaignType?: string;
    campaignStatus?: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: DeleteApiCampaignsId200DeletedAt;
};
