/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiDoctorsPortalDoctorsDoctorUuid500Error } from './deleteApiDoctorsPortalDoctorsDoctorUuid500Error';

export type DeleteApiDoctorsPortalDoctorsDoctorUuid500 = {
    statusCode: number;
    error: DeleteApiDoctorsPortalDoctorsDoctorUuid500Error;
    message: string;
};
