/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiWebhooksId404Error =
    (typeof DeleteApiWebhooksId404Error)[keyof typeof DeleteApiWebhooksId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiWebhooksId404Error = {
    Bad_Request: 'Bad Request',
} as const;
