/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiProducts500Error } from './deleteApiProducts500Error';

export type DeleteApiProducts500 = {
    statusCode: number;
    error: DeleteApiProducts500Error;
    message: string;
};
