/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiDiscountId500Error } from './deleteApiDiscountId500Error';

export type DeleteApiDiscountId500 = {
    statusCode: number;
    error: DeleteApiDiscountId500Error;
    message: string;
};
