/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiProducts400Error } from './deleteApiProducts400Error';

export type DeleteApiProducts400 = {
    statusCode: number;
    error: DeleteApiProducts400Error;
    message: string;
};
