/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiHealthDeclarationTemplateId200DataContentAnyOf } from './deleteApiHealthDeclarationTemplateId200DataContentAnyOf';

export type DeleteApiHealthDeclarationTemplateId200DataContent =
    DeleteApiHealthDeclarationTemplateId200DataContentAnyOf | null;
