/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiProducts400Error = (typeof DeleteApiProducts400Error)[keyof typeof DeleteApiProducts400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiProducts400Error = {
    Bad_Request: 'Bad Request',
} as const;
