/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGoogleCalendarBookingStatusByGroupUuid200DataBookingsItem } from './getApiGoogleCalendarBookingStatusByGroupUuid200DataBookingsItem';

export type GetApiGoogleCalendarBookingStatusByGroupUuid200Data = {
    groupBookingUuid?: string;
    bookings?: GetApiGoogleCalendarBookingStatusByGroupUuid200DataBookingsItem[];
};
