/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProductListPrintType500Error =
    (typeof GetApiProductListPrintType500Error)[keyof typeof GetApiProductListPrintType500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiProductListPrintType500Error = {
    Bad_Request: 'Bad Request',
} as const;
