/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPublicHealthDeclarationsForm400Error } from './getApiPublicHealthDeclarationsForm400Error';

export type GetApiPublicHealthDeclarationsForm400 = {
    statusCode: number;
    error: GetApiPublicHealthDeclarationsForm400Error;
    message: string;
};
