/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsExportAppointmentsByTimeGroupBy } from './getApiStatisticsExportAppointmentsByTimeGroupBy';
import type { GetApiStatisticsExportAppointmentsByTimeSource } from './getApiStatisticsExportAppointmentsByTimeSource';
import type { GetApiStatisticsExportAppointmentsByTimeDateFilterType } from './getApiStatisticsExportAppointmentsByTimeDateFilterType';

export type GetApiStatisticsExportAppointmentsByTimeParams = {
    /**
     * Service ID to filter by (use "null" for no service)
     */
    serviceId?: string;
    /**
     * Grouping type for time statistics
     */
    groupBy: GetApiStatisticsExportAppointmentsByTimeGroupBy;
    /**
     * Source of bookings
     */
    source: GetApiStatisticsExportAppointmentsByTimeSource;
    /**
     * Type of date filtering
     */
    dateFilterType: GetApiStatisticsExportAppointmentsByTimeDateFilterType;
    fromDate: string;
    toDate: string;
    /**
     * Array of booking statuses to filter by
     */
    status?: string[];
};
