/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsCustomerStatistics200DataItem } from './getApiInsightsCustomerStatistics200DataItem';

export type GetApiInsightsCustomerStatistics200 = {
    success: boolean;
    data: GetApiInsightsCustomerStatistics200DataItem[];
    message: string;
    statusCode: number;
};
