/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceGroupsIdDrivingFees404Error =
    (typeof GetApiServiceGroupsIdDrivingFees404Error)[keyof typeof GetApiServiceGroupsIdDrivingFees404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceGroupsIdDrivingFees404Error = {
    Bad_Request: 'Bad Request',
} as const;
