/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataWeeksItemMondayDayName } from './getApiInsightsWeeklyTurnoverType200DataWeeksItemMondayDayName';

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemMonday = {
    date: string;
    dayName: GetApiInsightsWeeklyTurnoverType200DataWeeksItemMondayDayName;
    totalRevenue: number;
    totalCredit: number;
    transactionCount: number;
    averageTransactionValue: number;
};
