/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersSoldIdType200ItemApplicableServicesServices } from './getApiBundleOffersSoldIdType200ItemApplicableServicesServices';
import type { GetApiBundleOffersSoldIdType200ItemApplicableServicesResiduePunch } from './getApiBundleOffersSoldIdType200ItemApplicableServicesResiduePunch';
import type { GetApiBundleOffersSoldIdType200ItemApplicableServicesOriginalPunch } from './getApiBundleOffersSoldIdType200ItemApplicableServicesOriginalPunch';

/**
 * @nullable
 */
export type GetApiBundleOffersSoldIdType200ItemApplicableServices = {
    services?: GetApiBundleOffersSoldIdType200ItemApplicableServicesServices;
    residuePunch?: GetApiBundleOffersSoldIdType200ItemApplicableServicesResiduePunch;
    originalPunch?: GetApiBundleOffersSoldIdType200ItemApplicableServicesOriginalPunch;
} | null;
