/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsSummaryItemTypeType200DataItemsItemItemType =
    (typeof GetApiInsightsSummaryItemTypeType200DataItemsItemItemType)[keyof typeof GetApiInsightsSummaryItemTypeType200DataItemsItemItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsSummaryItemTypeType200DataItemsItemItemType = {
    product: 'product',
    service: 'service',
} as const;
