/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsListing200ServicesItemServicesItemAdditionalDataAnyOf } from './getApiProductsListing200ServicesItemServicesItemAdditionalDataAnyOf';

export type GetApiProductsListing200ServicesItemServicesItemAdditionalData =
    GetApiProductsListing200ServicesItemServicesItemAdditionalDataAnyOf | null;
