/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerGroupsIdMembers500Error } from './getApiCustomerGroupsIdMembers500Error';

export type GetApiCustomerGroupsIdMembers500 = {
    statusCode: number;
    error: GetApiCustomerGroupsIdMembers500Error;
    message: string;
};
