/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsSettings200GiftCardAttachmentAnyOf } from './getApiGiftCardsSettings200GiftCardAttachmentAnyOf';

export type GetApiGiftCardsSettings200GiftCardAttachment = GetApiGiftCardsSettings200GiftCardAttachmentAnyOf | null;
