/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomersExport500Error } from './getApiCustomersExport500Error';

export type GetApiCustomersExport500 = {
    statusCode: number;
    error: GetApiCustomersExport500Error;
    message: string;
};
