/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotals } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotals';

export type GetApiInsightsWeeklyTurnoverType200DataSummary = {
    totalRevenue: number;
    totalCredit: number;
    totalTransactions: number;
    averageTransactionValue: number;
    totalWeeks: number;
    dayTotals: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotals;
};
