/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsEmailOverview200EmailPreferences } from './getApiCampaignsEmailOverview200EmailPreferences';
import type { GetApiCampaignsEmailOverview200TopCampaignsItem } from './getApiCampaignsEmailOverview200TopCampaignsItem';
import type { GetApiCampaignsEmailOverview200TopCampaignsByRecipientsItem } from './getApiCampaignsEmailOverview200TopCampaignsByRecipientsItem';
import type { GetApiCampaignsEmailOverview200CustomerMarketingPermission } from './getApiCampaignsEmailOverview200CustomerMarketingPermission';

export type GetApiCampaignsEmailOverview200 = {
    emailPreferences: GetApiCampaignsEmailOverview200EmailPreferences;
    topCampaigns: GetApiCampaignsEmailOverview200TopCampaignsItem[];
    /** Top 2 email campaigns ordered by recipient count */
    topCampaignsByRecipients: GetApiCampaignsEmailOverview200TopCampaignsByRecipientsItem[];
    customerMarketingPermission: GetApiCampaignsEmailOverview200CustomerMarketingPermission;
};
