/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Bad request - invalid query parameters
 */
export type GetApiStatisticsAppointments400 = {
    error?: string;
    message?: string;
};
