/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarations200DataItemsItem } from './getApiHealthDeclarations200DataItemsItem';

export type GetApiHealthDeclarations200Data = {
    currentPage?: number;
    limit?: number;
    totalItems?: number;
    totalPages?: number;
    items?: GetApiHealthDeclarations200DataItemsItem[];
};
