/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPublicHealthDeclarationsForm401Error } from './getApiPublicHealthDeclarationsForm401Error';

export type GetApiPublicHealthDeclarationsForm401 = {
    statusCode: number;
    error: GetApiPublicHealthDeclarationsForm401Error;
    message: string;
};
