/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiPublicHealthDeclarationsForm500Error =
    (typeof GetApiPublicHealthDeclarationsForm500Error)[keyof typeof GetApiPublicHealthDeclarationsForm500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiPublicHealthDeclarationsForm500Error = {
    Bad_Request: 'Bad Request',
} as const;
