/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItem } from './getApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItem';

export type GetApiPaymentsSubscriptionOutletOutletId200Data = {
    outletId?: number;
    totalSubscriptions?: number;
    subscriptions?: GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItem[];
};
