/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2Recommended400Error } from './getApiMarketplaceV2Recommended400Error';

export type GetApiMarketplaceV2Recommended400 = {
    statusCode: number;
    error: GetApiMarketplaceV2Recommended400Error;
    message: string;
};
