/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceSubscriptionCustomer500Error } from './getApiServiceSubscriptionCustomer500Error';

export type GetApiServiceSubscriptionCustomer500 = {
    statusCode: number;
    error: GetApiServiceSubscriptionCustomer500Error;
    message: string;
};
