/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBooking404Data } from './getApiBooking404Data';

export type GetApiBooking404 = {
    success?: boolean;
    /** @nullable */
    data?: GetApiBooking404Data;
    message?: string;
};
