/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCashDrawerEmployeeSummaryParams = {
    /**
     * Employee ID
     * @minimum 1
     */
    employeeId: number;
    /**
     * End date (ISO 8601 format)
     */
    toDate: string;
};
