/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTerminalPaymentLogPaymentId200PaymentStatus } from './getApiTerminalPaymentLogPaymentId200PaymentStatus';
import type { GetApiTerminalPaymentLogPaymentId200ResponseObject } from './getApiTerminalPaymentLogPaymentId200ResponseObject';

export type GetApiTerminalPaymentLogPaymentId200 = {
    paymentStatus: GetApiTerminalPaymentLogPaymentId200PaymentStatus;
    /** @nullable */
    responseObject: GetApiTerminalPaymentLogPaymentId200ResponseObject;
    /** @nullable */
    event: string | null;
    createdAt: string;
};
