/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsZipcodeStatistics200DataItem } from './getApiInsightsZipcodeStatistics200DataItem';

export type GetApiInsightsZipcodeStatistics200 = {
    success: boolean;
    data: GetApiInsightsZipcodeStatistics200DataItem[];
    message: string;
    statusCode: number;
};
