/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsListing500Error } from './getApiProductsListing500Error';

export type GetApiProductsListing500 = {
    statusCode: number;
    error: GetApiProductsListing500Error;
    message: string;
};
