/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarationTemplateId200DataContentAnyOf } from './getApiHealthDeclarationTemplateId200DataContentAnyOf';

export type GetApiHealthDeclarationTemplateId200DataContent =
    GetApiHealthDeclarationTemplateId200DataContentAnyOf | null;
