/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesDetailsItemTypeIdType500Error } from './getApiInsightsSalesDetailsItemTypeIdType500Error';

export type GetApiInsightsSalesDetailsItemTypeIdType500 = {
    statusCode: number;
    error: GetApiInsightsSalesDetailsItemTypeIdType500Error;
    message: string;
};
