/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsSummaryItemTypeType400Error =
    (typeof GetApiInsightsSummaryItemTypeType400Error)[keyof typeof GetApiInsightsSummaryItemTypeType400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsSummaryItemTypeType400Error = {
    Bad_Request: 'Bad Request',
} as const;
