/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Recommended400Error =
    (typeof GetApiMarketplaceV2Recommended400Error)[keyof typeof GetApiMarketplaceV2Recommended400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiMarketplaceV2Recommended400Error = {
    Bad_Request: 'Bad Request',
} as const;
