/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId404Error } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId404Error';

export type GetApiServiceAdvancedReminderTemplatesReminderTemplateId404 = {
    statusCode: number;
    error: GetApiServiceAdvancedReminderTemplatesReminderTemplateId404Error;
    message: string;
};
