/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsCustomerStatisticsParams = {
    /**
     * Start date for statistics calculation (YYYY-MM-DD)
     */
    startDate: string;
    /**
     * End date for statistics calculation (YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Optional employee ID to filter statistics for specific employee. If not provided, returns statistics for all employees.
     */
    employeeId?: number;
};
