/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType';
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailSubject } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailSubject';
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailContent } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailContent';
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId200SmsContent } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId200SmsContent';
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId200ServicesItem } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId200ServicesItem';

export type GetApiServiceAdvancedReminderTemplatesReminderTemplateId200 = {
    reminderTemplateId: string;
    reminderTemplateName: string;
    reminderTemplateType: GetApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    reminderMinutes: number;
    emailSubject: GetApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailSubject;
    emailContent: GetApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailContent;
    smsContent: GetApiServiceAdvancedReminderTemplatesReminderTemplateId200SmsContent;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    services: GetApiServiceAdvancedReminderTemplatesReminderTemplateId200ServicesItem[];
};
