/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAddons200DataItemAddonsItem } from './getApiAddons200DataItemAddonsItem';

export type GetApiAddons200DataItem = {
    categoryId: number;
    category: string;
    addons: GetApiAddons200DataItemAddonsItem[];
};
