/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardOnlineId200Description } from './getApiGiftCardOnlineId200Description';
import type { GetApiGiftCardOnlineId200CreatedBy } from './getApiGiftCardOnlineId200CreatedBy';

export type GetApiGiftCardOnlineId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    /** @maxLength 255 */
    name: string;
    description: GetApiGiftCardOnlineId200Description;
    applicableServices?: string[];
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    price: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    expiryDays: number;
    sellOnline: boolean;
    createdBy: GetApiGiftCardOnlineId200CreatedBy;
    createdAt: string;
    updatedAt: string;
};
