/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsId200ConditionsItemDescription } from './getApiCampaignsId200ConditionsItemDescription';
import type { GetApiCampaignsId200ConditionsItemParentEntity } from './getApiCampaignsId200ConditionsItemParentEntity';
import type { GetApiCampaignsId200ConditionsItemJsonPath } from './getApiCampaignsId200ConditionsItemJsonPath';
import type { GetApiCampaignsId200ConditionsItemFieldValue } from './getApiCampaignsId200ConditionsItemFieldValue';
import type { GetApiCampaignsId200ConditionsItemValue } from './getApiCampaignsId200ConditionsItemValue';
import type { GetApiCampaignsId200ConditionsItemAggregateFn } from './getApiCampaignsId200ConditionsItemAggregateFn';
import type { GetApiCampaignsId200ConditionsItemAggregateGroup } from './getApiCampaignsId200ConditionsItemAggregateGroup';
import type { GetApiCampaignsId200ConditionsItemLogicalGroup } from './getApiCampaignsId200ConditionsItemLogicalGroup';
import type { GetApiCampaignsId200ConditionsItemConditionId } from './getApiCampaignsId200ConditionsItemConditionId';
import type { GetApiCampaignsId200ConditionsItemRenderId } from './getApiCampaignsId200ConditionsItemRenderId';
import type { GetApiCampaignsId200ConditionsItemDeletedAt } from './getApiCampaignsId200ConditionsItemDeletedAt';

export type GetApiCampaignsId200ConditionsItem = {
    id: string;
    description?: GetApiCampaignsId200ConditionsItemDescription;
    marketingCampaignId: string;
    entity: string;
    parentEntity?: GetApiCampaignsId200ConditionsItemParentEntity;
    jsonPath?: GetApiCampaignsId200ConditionsItemJsonPath;
    field: string;
    operator: string;
    fieldValue?: GetApiCampaignsId200ConditionsItemFieldValue;
    /** Value field that can be an array or any object with key-value pairs */
    value?: GetApiCampaignsId200ConditionsItemValue;
    aggregate_fn?: GetApiCampaignsId200ConditionsItemAggregateFn;
    aggregate_group?: GetApiCampaignsId200ConditionsItemAggregateGroup;
    logical_group?: GetApiCampaignsId200ConditionsItemLogicalGroup;
    outletId: number;
    createdAt: string;
    /** Sequence/order of condition */
    seqId: number;
    /** Sequence/order of condition (same as seqId) */
    sequenceId?: number;
    /** ID of the condition template used */
    conditionId?: GetApiCampaignsId200ConditionsItemConditionId;
    /** Render ID stored in the condition table */
    renderId?: GetApiCampaignsId200ConditionsItemRenderId;
    deletedAt?: GetApiCampaignsId200ConditionsItemDeletedAt;
};
