/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCards200ItemsItemCustomerAnyOfEmail } from './getApiGiftCards200ItemsItemCustomerAnyOfEmail';

export type GetApiGiftCards200ItemsItemCustomerAnyOf = {
    id: number;
    name: string;
    email: GetApiGiftCards200ItemsItemCustomerAnyOfEmail;
    phoneNumber: string;
};
