/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsBundleOffersSource =
    (typeof GetApiStatisticsBundleOffersSource)[keyof typeof GetApiStatisticsBundleOffersSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiStatisticsBundleOffersSource = {
    ALL: 'ALL',
    OFFLINE: 'OFFLINE',
    ONLINE: 'ONLINE',
} as const;
