/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTriggerTemplates200CampaignsItem } from './getApiTriggerTemplates200CampaignsItem';

export type GetApiTriggerTemplates200 = {
    campaigns: GetApiTriggerTemplates200CampaignsItem[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};
