/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBillyExportType = (typeof GetApiBillyExportType)[keyof typeof GetApiBillyExportType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBillyExportType = {
    itemized: 'itemized',
    simple: 'simple',
    typewise: 'typewise',
} as const;
