/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus } from './getApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus';
import type { GetApiServiceSubscriptionCustomer200DataItemSubscriptionCreatedByBookingId } from './getApiServiceSubscriptionCustomer200DataItemSubscriptionCreatedByBookingId';

export type GetApiServiceSubscriptionCustomer200DataItemSubscription = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    serviceId: number;
    serviceName: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletCustomerId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    subscriptionCredit: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    subscriptionCreditUsed: number;
    subscriptionStatus: GetApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus;
    subscriptionStartDate: string;
    subscriptionEndDate: string;
    createdByBookingId: GetApiServiceSubscriptionCustomer200DataItemSubscriptionCreatedByBookingId;
    createdAt: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    createdBy: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    updatedBy: number;
    updatedAt: string;
};
