/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceSubscriptionCustomer200DataItem } from './getApiServiceSubscriptionCustomer200DataItem';

export type GetApiServiceSubscriptionCustomer200 = {
    success: boolean;
    message: string;
    data: GetApiServiceSubscriptionCustomer200DataItem[];
};
