/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSupplierId400Error } from './getApiSupplierId400Error';

export type GetApiSupplierId400 = {
    statusCode: number;
    error: GetApiSupplierId400Error;
    message: string;
};
