/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookingsNoShowReminder200DataItem } from './getApiBookingsNoShowReminder200DataItem';

/**
 * No-show bookings for reminder
 */
export type GetApiBookingsNoShowReminder200 = {
    /** Operation success status */
    success: boolean;
    /** Array of no-show bookings that meet the reminder criteria */
    data: GetApiBookingsNoShowReminder200DataItem[];
    /** Human-readable response message */
    message: string;
};
