/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiListDiscounts200ItemAmount } from './getApiListDiscounts200ItemAmount';
import type { GetApiListDiscounts200ItemOptionMaxDiscountValue } from './getApiListDiscounts200ItemOptionMaxDiscountValue';
import type { GetApiListDiscounts200ItemCouponId } from './getApiListDiscounts200ItemCouponId';
import type { GetApiListDiscounts200ItemOutletId } from './getApiListDiscounts200ItemOutletId';
import type { GetApiListDiscounts200ItemAmountType } from './getApiListDiscounts200ItemAmountType';
import type { GetApiListDiscounts200ItemCreatedBy } from './getApiListDiscounts200ItemCreatedBy';
import type { GetApiListDiscounts200ItemUpdatedBy } from './getApiListDiscounts200ItemUpdatedBy';
import type { GetApiListDiscounts200ItemCreatedAt } from './getApiListDiscounts200ItemCreatedAt';
import type { GetApiListDiscounts200ItemUpdatedAt } from './getApiListDiscounts200ItemUpdatedAt';

export type GetApiListDiscounts200Item = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    amount: GetApiListDiscounts200ItemAmount;
    optionMaxDiscountValue: GetApiListDiscounts200ItemOptionMaxDiscountValue;
    couponId: GetApiListDiscounts200ItemCouponId;
    outletId: GetApiListDiscounts200ItemOutletId;
    amountType: GetApiListDiscounts200ItemAmountType;
    createdBy: GetApiListDiscounts200ItemCreatedBy;
    updatedBy: GetApiListDiscounts200ItemUpdatedBy;
    createdAt: GetApiListDiscounts200ItemCreatedAt;
    updatedAt: GetApiListDiscounts200ItemUpdatedAt;
};
