/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookingsExport500Error } from './getApiBookingsExport500Error';

export type GetApiBookingsExport500 = {
    statusCode: number;
    error: GetApiBookingsExport500Error;
    message: string;
};
