/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMobilepayPaymentStatusReference200DataAggregate } from './getApiMobilepayPaymentStatusReference200DataAggregate';
import type { GetApiMobilepayPaymentStatusReference200DataAmount } from './getApiMobilepayPaymentStatusReference200DataAmount';
import type { GetApiMobilepayPaymentStatusReference200DataPaymentMethod } from './getApiMobilepayPaymentStatusReference200DataPaymentMethod';
import type { GetApiMobilepayPaymentStatusReference200DataProfile } from './getApiMobilepayPaymentStatusReference200DataProfile';

export type GetApiMobilepayPaymentStatusReference200Data = {
    aggregate: GetApiMobilepayPaymentStatusReference200DataAggregate;
    amount: GetApiMobilepayPaymentStatusReference200DataAmount;
    state: string;
    paymentMethod: GetApiMobilepayPaymentStatusReference200DataPaymentMethod;
    profile: GetApiMobilepayPaymentStatusReference200DataProfile;
    pspReference: string;
    reference: string;
};
