/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiExpenseCategories500Error } from './getApiExpenseCategories500Error';

export type GetApiExpenseCategories500 = {
    statusCode: number;
    error: GetApiExpenseCategories500Error;
    message: string;
};
