/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2SearchResultFilterByItem =
    (typeof GetApiMarketplaceV2SearchResultFilterByItem)[keyof typeof GetApiMarketplaceV2SearchResultFilterByItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiMarketplaceV2SearchResultFilterByItem = {
    giftCard: 'giftCard',
    campaign: 'campaign',
    cancellationOffer: 'cancellationOffer',
} as const;
