/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiTerminalPaymentLogPaymentId200PaymentStatus =
    (typeof GetApiTerminalPaymentLogPaymentId200PaymentStatus)[keyof typeof GetApiTerminalPaymentLogPaymentId200PaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiTerminalPaymentLogPaymentId200PaymentStatus = {
    PENDING: 'PENDING',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    SUCCEEDED: 'SUCCEEDED',
    CANCELLED: 'CANCELLED',
} as const;
