/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiDoctorsPortalDoctors500Error } from './getApiDoctorsPortalDoctors500Error';

export type GetApiDoctorsPortalDoctors500 = {
    statusCode: number;
    error: GetApiDoctorsPortalDoctors500Error;
    message: string;
};
