/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiDineroRefreshToken200Data } from './getApiDineroRefreshToken200Data';

export type GetApiDineroRefreshToken200 = {
    success?: boolean;
    message?: string;
    data?: GetApiDineroRefreshToken200Data;
};
