/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSummaryItemTypeType200DataSummaryTotalCost } from './getApiInsightsSummaryItemTypeType200DataSummaryTotalCost';

export type GetApiInsightsSummaryItemTypeType200DataSummary = {
    totalRevenue: number;
    totalCost: GetApiInsightsSummaryItemTypeType200DataSummaryTotalCost;
    totalProfit: number;
    totalProfitPercentage: number;
    totalItems: number;
    totalQuantity: number;
};
