/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsAppointmentsResponseFormat } from './getApiStatisticsAppointmentsResponseFormat';

export type GetApiStatisticsAppointmentsParams = {
    page?: number;
    limit?: number;
    /**
     * YYYY-MM-DD
     */
    fromDate?: string;
    /**
     * YYYY-MM-DD
     */
    toDate?: string;
    responseFormat?: GetApiStatisticsAppointmentsResponseFormat;
};
