/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiNoShowIdType500Error } from './getApiNoShowIdType500Error';

export type GetApiNoShowIdType500 = {
    statusCode: number;
    error: GetApiNoShowIdType500Error;
    message: string;
};
