/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesList200SalesItem } from './getApiSalesList200SalesItem';

export type GetApiSalesList200 = {
    total?: number;
    currentPage?: number;
    totalPages?: number;
    limit?: number;
    sales?: GetApiSalesList200SalesItem[];
};
