/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGetcreditsales500Error =
    (typeof GetApiGetcreditsales500Error)[keyof typeof GetApiGetcreditsales500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiGetcreditsales500Error = {
    Bad_Request: 'Bad Request',
} as const;
