/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesDetailsId200TaxItemTaxName } from './getApiSalesDetailsId200TaxItemTaxName';
import type { GetApiSalesDetailsId200TaxItemCreatedBy } from './getApiSalesDetailsId200TaxItemCreatedBy';
import type { GetApiSalesDetailsId200TaxItemUpdatedBy } from './getApiSalesDetailsId200TaxItemUpdatedBy';

export type GetApiSalesDetailsId200TaxItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesId: string;
    taxId: string;
    taxName: GetApiSalesDetailsId200TaxItemTaxName;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    taxRate: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    taxAmount: number;
    isInclusive: boolean;
    createdBy: GetApiSalesDetailsId200TaxItemCreatedBy;
    updatedBy: GetApiSalesDetailsId200TaxItemUpdatedBy;
    createdAt: string;
    updatedAt: string;
};
