/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerId500Error = (typeof GetApiCustomerId500Error)[keyof typeof GetApiCustomerId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerId500Error = {
    Bad_Request: 'Bad Request',
} as const;
