/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGiftCardsListType500Error =
    (typeof GetApiGiftCardsListType500Error)[keyof typeof GetApiGiftCardsListType500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiGiftCardsListType500Error = {
    Bad_Request: 'Bad Request',
} as const;
