/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsListing200ServicesItemServicesItemHealthDeclarationAnyOf } from './getApiProductsListing200ServicesItemServicesItemHealthDeclarationAnyOf';

export type GetApiProductsListing200ServicesItemServicesItemHealthDeclaration =
    GetApiProductsListing200ServicesItemServicesItemHealthDeclarationAnyOf | null;
