/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarationTemplateId200DataDescription } from './getApiHealthDeclarationTemplateId200DataDescription';
import type { GetApiHealthDeclarationTemplateId200DataContent } from './getApiHealthDeclarationTemplateId200DataContent';

export type GetApiHealthDeclarationTemplateId200Data = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    description: GetApiHealthDeclarationTemplateId200DataDescription;
    content?: GetApiHealthDeclarationTemplateId200DataContent;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    createdAt: string;
    updatedAt: string;
};
