/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Services on which bundle offer can be applied
 */
export type GetApiBundleOffersId200ApplicableService = { [key: string]: unknown };
