/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsEmployeePaymentsType400Error =
    (typeof GetApiInsightsEmployeePaymentsType400Error)[keyof typeof GetApiInsightsEmployeePaymentsType400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsEmployeePaymentsType400Error = {
    Bad_Request: 'Bad Request',
} as const;
