/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiExpenses500Error = (typeof GetApiExpenses500Error)[keyof typeof GetApiExpenses500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiExpenses500Error = {
    Bad_Request: 'Bad Request',
} as const;
