/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsSalesDetailsItemTypeIdType400Error =
    (typeof GetApiInsightsSalesDetailsItemTypeIdType400Error)[keyof typeof GetApiInsightsSalesDetailsItemTypeIdType400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsSalesDetailsItemTypeIdType400Error = {
    Bad_Request: 'Bad Request',
} as const;
