/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataWeeksItemSundayDayName } from './getApiInsightsWeeklyTurnoverType200DataWeeksItemSundayDayName';

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemSunday = {
    date: string;
    dayName: GetApiInsightsWeeklyTurnoverType200DataWeeksItemSundayDayName;
    totalRevenue: number;
    totalCredit: number;
    transactionCount: number;
    averageTransactionValue: number;
};
