/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsBundleOffers200SoldBundleOffersItem = {
    bundleOfferName: string;
    soldBundleOfferName: string;
    originalPunches: number;
    residuePunches: number;
    amount: number;
    count: number;
};
