/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiHealthDeclarationTemplateId404Error =
    (typeof GetApiHealthDeclarationTemplateId404Error)[keyof typeof GetApiHealthDeclarationTemplateId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiHealthDeclarationTemplateId404Error = {
    Bad_Request: 'Bad Request',
} as const;
