/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCashDrawerEmployeeSummary200DataDetailedPaymentBreakdownItemItem } from './getApiCashDrawerEmployeeSummary200DataDetailedPaymentBreakdownItemItem';

export type GetApiCashDrawerEmployeeSummary200DataDetailedPaymentBreakdownItem = {
    [key: string]: GetApiCashDrawerEmployeeSummary200DataDetailedPaymentBreakdownItemItem[];
};
