/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiKlaviyoConfig500Error } from './getApiKlaviyoConfig500Error';

export type GetApiKlaviyoConfig500 = {
    statusCode: number;
    error: GetApiKlaviyoConfig500Error;
    message: string;
};
