/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerIdType400Error =
    (typeof GetApiCustomerIdType400Error)[keyof typeof GetApiCustomerIdType400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerIdType400Error = {
    Bad_Request: 'Bad Request',
} as const;
