/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Outlet200DataBadgesItem = {
    id?: number;
    name?: string;
    title?: string;
    description?: string;
    image?: string;
    created_at?: string;
    updated_at?: string;
    /** @nullable */
    deleted_at?: string | null;
};
