/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsServicesStatus } from './getApiStatisticsServicesStatus';

export type GetApiStatisticsServicesParams = {
    /**
     * YYYY-MM-DD
     */
    fromDate?: string;
    /**
     * YYYY-MM-DD
     */
    toDate?: string;
    status?: GetApiStatisticsServicesStatus;
};
