/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesEmployeeIdPaymentTypeType200Data } from './getApiInsightsSalesEmployeeIdPaymentTypeType200Data';

export type GetApiInsightsSalesEmployeeIdPaymentTypeType200 = {
    data: GetApiInsightsSalesEmployeeIdPaymentTypeType200Data;
    message: string;
};
