/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsId200SupplierAnyOf } from './getApiProductsId200SupplierAnyOf';

export type GetApiProductsId200Supplier = GetApiProductsId200SupplierAnyOf | null;
