/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Main/Primary booking with full details
 */
export type GetApiBooking200DataBooking = { [key: string]: unknown };
