/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiIotConnectionStatus500Error =
    (typeof GetApiIotConnectionStatus500Error)[keyof typeof GetApiIotConnectionStatus500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiIotConnectionStatus500Error = {
    Bad_Request: 'Bad Request',
} as const;
