/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarations200DataItemsItemReviewedByAnyOf } from './getApiHealthDeclarations200DataItemsItemReviewedByAnyOf';

/**
 * @nullable
 */
export type GetApiHealthDeclarations200DataItemsItemReviewedBy =
    null | GetApiHealthDeclarations200DataItemsItemReviewedByAnyOf | null;
