/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiRecipients200RecipientsItem } from './getApiRecipients200RecipientsItem';

export type GetApiRecipients200 = {
    /** Array of recipient objects */
    recipients: GetApiRecipients200RecipientsItem[];
};
