/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerIdType200OneOfThreeItemStatus =
    (typeof GetApiCustomerIdType200OneOfThreeItemStatus)[keyof typeof GetApiCustomerIdType200OneOfThreeItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerIdType200OneOfThreeItemStatus = {
    ACTIVE: 'ACTIVE',
    USED: 'USED',
    EXPIRED: 'EXPIRED',
} as const;
