/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiAddons500Error = (typeof GetApiAddons500Error)[keyof typeof GetApiAddons500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAddons500Error = {
    Bad_Request: 'Bad Request',
} as const;
