/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGiftCards200ItemsItemStatus =
    (typeof GetApiGiftCards200ItemsItemStatus)[keyof typeof GetApiGiftCards200ItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiGiftCards200ItemsItemStatus = {
    BLOCKED: 'BLOCKED',
    EXPIRED: 'EXPIRED',
    USED: 'USED',
    UNUSED: 'UNUSED',
    PARTIALLY_USED: 'PARTIALLY_USED',
} as const;
