/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSalesList500Error = (typeof GetApiSalesList500Error)[keyof typeof GetApiSalesList500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiSalesList500Error = {
    Bad_Request: 'Bad Request',
} as const;
