/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTrustpilotConfig200DataAnyOfTrustPilotAFSEmail } from './getApiTrustpilotConfig200DataAnyOfTrustPilotAFSEmail';

export type GetApiTrustpilotConfig200DataAnyOf = {
    id: string;
    outletId: number;
    enabled: boolean;
    trustPilotAFSEmail: GetApiTrustpilotConfig200DataAnyOfTrustPilotAFSEmail;
    createdAt: string;
    updatedAt: string;
};
