/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType } from './getApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType';

/**
 * @nullable
 */
export type GetApiBundleOffersSoldIdType200ItemBundleOffer = {
    id?: string;
    name?: string;
    /** @nullable */
    description?: string | null;
    bundleOfferType?: GetApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType;
    price?: number;
    expiryMonths?: number;
    /** @nullable */
    createdBy?: number | null;
    createdAt?: string;
    updatedAt?: string;
    /** @nullable */
    deletedAt?: string | null;
} | null;
