/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPreviousSalesItemsCustomerId500Error } from './getApiPreviousSalesItemsCustomerId500Error';

export type GetApiPreviousSalesItemsCustomerId500 = {
    statusCode: number;
    error: GetApiPreviousSalesItemsCustomerId500Error;
    message: string;
};
