/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesDetailsItemTypeIdType200Data } from './getApiInsightsSalesDetailsItemTypeIdType200Data';

export type GetApiInsightsSalesDetailsItemTypeIdType200 = {
    data: GetApiInsightsSalesDetailsItemTypeIdType200Data;
    message: string;
};
