/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerIdType200OneOfItemStatus } from './getApiCustomerIdType200OneOfItemStatus';

export type GetApiCustomerIdType200OneOfItem = {
    id: string;
    giftCardCode: string;
    residueValue: number;
    expiryDate: string;
    originalValue: number;
    status: GetApiCustomerIdType200OneOfItemStatus;
};
