/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesType200DataRecordsItemEmployeeAnyOf } from './getApiInsightsSalesType200DataRecordsItemEmployeeAnyOf';

export type GetApiInsightsSalesType200DataRecordsItemEmployee =
    GetApiInsightsSalesType200DataRecordsItemEmployeeAnyOf | null;
