/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDineroRefreshToken200Data = {
    access_token?: string;
    token_type?: string;
    expires_in?: number;
    scope?: string;
};
