/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceSubscriptionCustomer400Error } from './getApiServiceSubscriptionCustomer400Error';

export type GetApiServiceSubscriptionCustomer400 = {
    statusCode: number;
    error: GetApiServiceSubscriptionCustomer400Error;
    message: string;
};
