/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2Recommended200DataItem } from './getApiMarketplaceV2Recommended200DataItem';

export type GetApiMarketplaceV2Recommended200 = {
    success?: boolean;
    message?: string;
    data?: GetApiMarketplaceV2Recommended200DataItem[];
};
