/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiHealthDeclarationPrintIdType404Error =
    (typeof GetApiHealthDeclarationPrintIdType404Error)[keyof typeof GetApiHealthDeclarationPrintIdType404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiHealthDeclarationPrintIdType404Error = {
    Bad_Request: 'Bad Request',
} as const;
