/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceGroupsIdDrivingFees400Error =
    (typeof GetApiServiceGroupsIdDrivingFees400Error)[keyof typeof GetApiServiceGroupsIdDrivingFees400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceGroupsIdDrivingFees400Error = {
    Bad_Request: 'Bad Request',
} as const;
