/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Recommended200DataItemCategoriesItem = {
    id?: number;
    category?: string;
    /** @nullable */
    image?: string | null;
};
