/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod =
    (typeof GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod)[keyof typeof GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod = {
    cash: 'cash',
    card: 'card',
    punchCard: 'punchCard',
    giftCard: 'giftCard',
    outstanding: 'outstanding',
    bankTransfer: 'bankTransfer',
    mobilePay: 'mobilePay',
    receivable: 'receivable',
} as const;
