/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTopCustomers200DataItem } from './getApiInsightsTopCustomers200DataItem';

export type GetApiInsightsTopCustomers200 = {
    success: boolean;
    data: GetApiInsightsTopCustomers200DataItem[];
    message: string;
    statusCode: number;
};
