/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDoctorsPortalMessages500Error =
    (typeof GetApiDoctorsPortalMessages500Error)[keyof typeof GetApiDoctorsPortalMessages500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiDoctorsPortalMessages500Error = {
    Bad_Request: 'Bad Request',
} as const;
