/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerGroups500Error } from './getApiCustomerGroups500Error';

export type GetApiCustomerGroups500 = {
    statusCode: number;
    error: GetApiCustomerGroups500Error;
    message: string;
};
