/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGoogleCalendarBookingStatusByGroupUuid200Data } from './getApiGoogleCalendarBookingStatusByGroupUuid200Data';

export type GetApiGoogleCalendarBookingStatusByGroupUuid200 = {
    success?: boolean;
    data?: GetApiGoogleCalendarBookingStatusByGroupUuid200Data;
    message?: string;
};
