/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName =
    (typeof GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName)[keyof typeof GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName = {
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
} as const;
