/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsAppointmentsByTime200BarChartDataAnyOfItem } from './getApiStatisticsAppointmentsByTime200BarChartDataAnyOfItem';
import type { GetApiStatisticsAppointmentsByTime200BarChartDataAnyOfTwoItem } from './getApiStatisticsAppointmentsByTime200BarChartDataAnyOfTwoItem';

export type GetApiStatisticsAppointmentsByTime200BarChartData =
    | GetApiStatisticsAppointmentsByTime200BarChartDataAnyOfItem[]
    | GetApiStatisticsAppointmentsByTime200BarChartDataAnyOfTwoItem[];
