/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerIdType200OneOfThreeItemBundleOfferType =
    (typeof GetApiCustomerIdType200OneOfThreeItemBundleOfferType)[keyof typeof GetApiCustomerIdType200OneOfThreeItemBundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerIdType200OneOfThreeItemBundleOfferType = {
    FIXED: 'FIXED',
    VARIABLE: 'VARIABLE',
} as const;
