/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGetcreditsales200ItemShortInvoiceId } from './getApiGetcreditsales200ItemShortInvoiceId';
import type { GetApiGetcreditsales200ItemCustomerId } from './getApiGetcreditsales200ItemCustomerId';
import type { GetApiGetcreditsales200ItemCustomerName } from './getApiGetcreditsales200ItemCustomerName';
import type { GetApiGetcreditsales200ItemTips } from './getApiGetcreditsales200ItemTips';
import type { GetApiGetcreditsales200ItemSalesNote } from './getApiGetcreditsales200ItemSalesNote';
import type { GetApiGetcreditsales200ItemVoidId } from './getApiGetcreditsales200ItemVoidId';
import type { GetApiGetcreditsales200ItemSalesType } from './getApiGetcreditsales200ItemSalesType';
import type { GetApiGetcreditsales200ItemCreatedBy } from './getApiGetcreditsales200ItemCreatedBy';
import type { GetApiGetcreditsales200ItemUpdatedBy } from './getApiGetcreditsales200ItemUpdatedBy';
import type { GetApiGetcreditsales200ItemSellBy } from './getApiGetcreditsales200ItemSellBy';
import type { GetApiGetcreditsales200ItemSyncedWith } from './getApiGetcreditsales200ItemSyncedWith';
import type { GetApiGetcreditsales200ItemSyncId } from './getApiGetcreditsales200ItemSyncId';

export type GetApiGetcreditsales200Item = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    invAutoNumber: number;
    salesDate: string;
    invoiceId: string;
    shortInvoiceId: GetApiGetcreditsales200ItemShortInvoiceId;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    customerId: GetApiGetcreditsales200ItemCustomerId;
    customerName: GetApiGetcreditsales200ItemCustomerName;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    subTotal: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalTax: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalDiscount: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    netTotal: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    roundOff: number;
    tips: GetApiGetcreditsales200ItemTips;
    salesNote: GetApiGetcreditsales200ItemSalesNote;
    voidId: GetApiGetcreditsales200ItemVoidId;
    salesType: GetApiGetcreditsales200ItemSalesType;
    createdBy: GetApiGetcreditsales200ItemCreatedBy;
    updatedBy: GetApiGetcreditsales200ItemUpdatedBy;
    sellBy: GetApiGetcreditsales200ItemSellBy;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    sourceId: number;
    syncedWith: GetApiGetcreditsales200ItemSyncedWith;
    syncId: GetApiGetcreditsales200ItemSyncId;
    createdAt: string;
    updatedAt: string;
};
