/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiDoctorsPortalMessages200MessagesItem } from './getApiDoctorsPortalMessages200MessagesItem';

export type GetApiDoctorsPortalMessages200 = {
    messages: GetApiDoctorsPortalMessages200MessagesItem[];
};
