/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPublicHealthDeclarationsForm404Error } from './getApiPublicHealthDeclarationsForm404Error';

export type GetApiPublicHealthDeclarationsForm404 = {
    statusCode: number;
    error: GetApiPublicHealthDeclarationsForm404Error;
    message: string;
};
