/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsEmailOverview200TopCampaignsItemFirstTriggeredAt } from './getApiCampaignsEmailOverview200TopCampaignsItemFirstTriggeredAt';

export type GetApiCampaignsEmailOverview200TopCampaignsItem = {
    id: string;
    name: string;
    campaignType: string;
    recipients: number;
    revenue: string;
    /** First time the campaign was triggered */
    firstTriggeredAt: GetApiCampaignsEmailOverview200TopCampaignsItemFirstTriggeredAt;
};
