/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiExpenseId500Error = (typeof GetApiExpenseId500Error)[keyof typeof GetApiExpenseId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiExpenseId500Error = {
    Bad_Request: 'Bad Request',
} as const;
