/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItemAmount } from './getApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItemAmount';
import type { GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItemPaymentLogsItem } from './getApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItemPaymentLogsItem';

export type GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItem = {
    id?: string;
    outletId?: number;
    seqId?: number;
    status?: string;
    subscriptionType?: string;
    startDate?: string;
    durationMonths?: number;
    lastBillingDate?: string;
    amount?: GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItemAmount;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    paymentLogs?: GetApiPaymentsSubscriptionOutletOutletId200DataSubscriptionsItemPaymentLogsItem[];
};
