/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSalesDetailsId200TransactionsItemTxStatus =
    (typeof GetApiSalesDetailsId200TransactionsItemTxStatus)[keyof typeof GetApiSalesDetailsId200TransactionsItemTxStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiSalesDetailsId200TransactionsItemTxStatus = {
    PENDING: 'PENDING',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    SUCCEEDED: 'SUCCEEDED',
    CANCELLED: 'CANCELLED',
} as const;
