/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServicesDeposit500Error } from './getApiServicesDeposit500Error';

export type GetApiServicesDeposit500 = {
    statusCode: number;
    error: GetApiServicesDeposit500Error;
    message: string;
};
