/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsOnlineType200ItemsItem } from './getApiGiftCardsOnlineType200ItemsItem';

export type GetApiGiftCardsOnlineType200 = {
    id?: string;
    name?: string;
    /** @nullable */
    description?: string | null;
    price?: number;
    expiryDays?: number;
    sellOnline?: boolean;
    createdAt?: string;
    updatedAt?: string;
    currentPage?: number;
    limit?: number;
    totalItems?: number;
    totalPages?: number;
    items?: GetApiGiftCardsOnlineType200ItemsItem[];
};
