/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsStatus } from './getApiGiftCardsStatus';
import type { GetApiGiftCardsSource } from './getApiGiftCardsSource';

export type GetApiGiftCardsParams = {
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100000
     */
    limit?: number;
    status?: GetApiGiftCardsStatus;
    /**
     * Filter by gift card source: ALL, MANUAL (created manually), ONLINE (purchased from online template)
     */
    source?: GetApiGiftCardsSource;
    /**
     * Search by gift card code, customer email, customer name, or recipient name
     */
    keyword?: string;
    fromDate?: string;
    toDate?: string;
};
