/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsCustomers200OneOfDataItemEmail } from './getApiInsightsCustomers200OneOfDataItemEmail';

export type GetApiInsightsCustomers200OneOfDataItem = {
    id: number;
    name: string;
    phoneNumber?: string;
    email?: GetApiInsightsCustomers200OneOfDataItemEmail;
    createdAt?: string;
    blockBooking?: boolean;
    outstandingAmount?: number;
    receivableAmount?: number;
};
