/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsSalesSummary200Summary = {
    subTotal: number;
    tax: number;
    netTotal: number;
};
