/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTopCustomers200DataItemEmail } from './getApiInsightsTopCustomers200DataItemEmail';

export type GetApiInsightsTopCustomers200DataItem = {
    id: number;
    name: string;
    phoneNumber: string;
    email: GetApiInsightsTopCustomers200DataItemEmail;
    totalRevenue: number;
    transactionCount: number;
    averageTransactionValue: number;
};
