/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsZipcodeStatistics500Error =
    (typeof GetApiInsightsZipcodeStatistics500Error)[keyof typeof GetApiInsightsZipcodeStatistics500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsZipcodeStatistics500Error = {
    Bad_Request: 'Bad Request',
} as const;
