/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesType200DataRecordsItem } from './getApiInsightsSalesType200DataRecordsItem';
import type { GetApiInsightsSalesType200DataSummary } from './getApiInsightsSalesType200DataSummary';
import type { GetApiInsightsSalesType200DataPagination } from './getApiInsightsSalesType200DataPagination';

export type GetApiInsightsSalesType200Data = {
    records: GetApiInsightsSalesType200DataRecordsItem[];
    summary: GetApiInsightsSalesType200DataSummary;
    pagination: GetApiInsightsSalesType200DataPagination;
};
