/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDoctorsPortalDoctorsSortOrder =
    (typeof GetApiDoctorsPortalDoctorsSortOrder)[keyof typeof GetApiDoctorsPortalDoctorsSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiDoctorsPortalDoctorsSortOrder = {
    asc: 'asc',
    desc: 'desc',
} as const;
