/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGoogleCalendarAuthUrl200Data } from './getApiGoogleCalendarAuthUrl200Data';

export type GetApiGoogleCalendarAuthUrl200 = {
    success?: boolean;
    data?: GetApiGoogleCalendarAuthUrl200Data;
    message?: string;
};
