/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceAdvancedReminderTemplatesSortBy } from './getApiServiceAdvancedReminderTemplatesSortBy';
import type { GetApiServiceAdvancedReminderTemplatesSortOrder } from './getApiServiceAdvancedReminderTemplatesSortOrder';

export type GetApiServiceAdvancedReminderTemplatesParams = {
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    sortBy?: GetApiServiceAdvancedReminderTemplatesSortBy;
    sortOrder?: GetApiServiceAdvancedReminderTemplatesSortOrder;
    keyword?: string;
    /**
 * Comma-separated values: 

 EMAIL 

 SMS 

 EMAIL,SMS 

 SMS,EMAIL
 */
    reminderTemplateType?: string;
    isActive?: boolean;
};
