/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsSettings200PersonalMessage } from './getApiGiftCardsSettings200PersonalMessage';
import type { GetApiGiftCardsSettings200PredefinedAmountsItem } from './getApiGiftCardsSettings200PredefinedAmountsItem';
import type { GetApiGiftCardsSettings200OnlineSaleDescription } from './getApiGiftCardsSettings200OnlineSaleDescription';
import type { GetApiGiftCardsSettings200GiftCardAttachment } from './getApiGiftCardsSettings200GiftCardAttachment';

export type GetApiGiftCardsSettings200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    taxIds?: string[];
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    expiryMonths: number;
    sendDesignBySale: boolean;
    cardColor: string;
    personalMessage: GetApiGiftCardsSettings200PersonalMessage;
    predefinedAmounts?: GetApiGiftCardsSettings200PredefinedAmountsItem[];
    onlineSaleDescription: GetApiGiftCardsSettings200OnlineSaleDescription;
    showServiceOnDesign: boolean;
    createdAt: string;
    GiftCardAttachment?: GetApiGiftCardsSettings200GiftCardAttachment;
    updatedAt: string;
};
