/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMessageLogsOutletId200ItemSid } from './getApiMessageLogsOutletId200ItemSid';
import type { GetApiMessageLogsOutletId200ItemException } from './getApiMessageLogsOutletId200ItemException';
import type { GetApiMessageLogsOutletId200ItemEvent } from './getApiMessageLogsOutletId200ItemEvent';
import type { GetApiMessageLogsOutletId200ItemBookingId } from './getApiMessageLogsOutletId200ItemBookingId';
import type { GetApiMessageLogsOutletId200ItemCurrency } from './getApiMessageLogsOutletId200ItemCurrency';
import type { GetApiMessageLogsOutletId200ItemResponseObject } from './getApiMessageLogsOutletId200ItemResponseObject';
import type { GetApiMessageLogsOutletId200ItemCost } from './getApiMessageLogsOutletId200ItemCost';
import type { GetApiMessageLogsOutletId200ItemOutletId } from './getApiMessageLogsOutletId200ItemOutletId';
import type { GetApiMessageLogsOutletId200ItemMessageBy } from './getApiMessageLogsOutletId200ItemMessageBy';
import type { GetApiMessageLogsOutletId200ItemSalesId } from './getApiMessageLogsOutletId200ItemSalesId';

export type GetApiMessageLogsOutletId200Item = {
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    id: number;
    to: string;
    message: string;
    success: boolean;
    sid: GetApiMessageLogsOutletId200ItemSid;
    exception: GetApiMessageLogsOutletId200ItemException;
    event: GetApiMessageLogsOutletId200ItemEvent;
    bookingId: GetApiMessageLogsOutletId200ItemBookingId;
    isScheduled: boolean;
    currency: GetApiMessageLogsOutletId200ItemCurrency;
    responseObject: GetApiMessageLogsOutletId200ItemResponseObject;
    cost: GetApiMessageLogsOutletId200ItemCost;
    createdAt: string;
    outletId: GetApiMessageLogsOutletId200ItemOutletId;
    messageBy: GetApiMessageLogsOutletId200ItemMessageBy;
    salesId: GetApiMessageLogsOutletId200ItemSalesId;
};
