/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Outlet200DataDataFromClients = {
    name?: boolean;
    phoneNumber?: boolean;
    email?: boolean;
    address?: boolean;
    noteBox?: boolean;
    birthday?: boolean;
    cpr?: boolean;
};
