/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsAppointmentsByTime200ItemsItem = {
    id: number;
    timeSlot?: string;
    dayOfWeek?: string;
    count: number;
    percentage: number;
};
