/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiHealthDeclarationTemplatesSortBy =
    (typeof GetApiHealthDeclarationTemplatesSortBy)[keyof typeof GetApiHealthDeclarationTemplatesSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiHealthDeclarationTemplatesSortBy = {
    name: 'name',
    createdAt: 'createdAt',
} as const;
