/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiHealthDeclarations200DataItemsItemLogsItem = {
    id?: string;
    healthDeclarationId?: string;
    status?: string;
    outletId?: number;
    createdAt?: string;
    /** @nullable */
    deviceIpAddress?: string | null;
};
