/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceAdvancedReminderTemplates200TemplatesItemReminderTemplateType } from './getApiServiceAdvancedReminderTemplates200TemplatesItemReminderTemplateType';
import type { GetApiServiceAdvancedReminderTemplates200TemplatesItemEmailSubject } from './getApiServiceAdvancedReminderTemplates200TemplatesItemEmailSubject';
import type { GetApiServiceAdvancedReminderTemplates200TemplatesItemEmailContent } from './getApiServiceAdvancedReminderTemplates200TemplatesItemEmailContent';
import type { GetApiServiceAdvancedReminderTemplates200TemplatesItemSmsContent } from './getApiServiceAdvancedReminderTemplates200TemplatesItemSmsContent';
import type { GetApiServiceAdvancedReminderTemplates200TemplatesItemServicesItem } from './getApiServiceAdvancedReminderTemplates200TemplatesItemServicesItem';

export type GetApiServiceAdvancedReminderTemplates200TemplatesItem = {
    reminderTemplateId: string;
    reminderTemplateName: string;
    reminderTemplateType: GetApiServiceAdvancedReminderTemplates200TemplatesItemReminderTemplateType;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    reminderMinutes: number;
    emailSubject: GetApiServiceAdvancedReminderTemplates200TemplatesItemEmailSubject;
    emailContent: GetApiServiceAdvancedReminderTemplates200TemplatesItemEmailContent;
    smsContent: GetApiServiceAdvancedReminderTemplates200TemplatesItemSmsContent;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    services: GetApiServiceAdvancedReminderTemplates200TemplatesItemServicesItem[];
};
