/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesType200DataSummaryPeriodSummary } from './getApiInsightsSalesType200DataSummaryPeriodSummary';

export type GetApiInsightsSalesType200DataSummary = {
    totalRevenue: number;
    totalTransactions: number;
    averageTransactionValue: number;
    periodSummary: GetApiInsightsSalesType200DataSummaryPeriodSummary;
};
