/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsWeeklyTurnoverType500Error =
    (typeof GetApiInsightsWeeklyTurnoverType500Error)[keyof typeof GetApiInsightsWeeklyTurnoverType500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsWeeklyTurnoverType500Error = {
    Bad_Request: 'Bad Request',
} as const;
