/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGiftCardsListTypeSource =
    (typeof GetApiGiftCardsListTypeSource)[keyof typeof GetApiGiftCardsListTypeSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiGiftCardsListTypeSource = {
    ALL: 'ALL',
    MANUAL: 'MANUAL',
    ONLINE: 'ONLINE',
} as const;
