/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRecipients200RecipientsItem = {
    id?: number;
    email?: string;
    phoneNumber?: string;
    name?: string;
    createdAt?: string;
    [key: string]: unknown;
};
