/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSalesDetailsId500Error =
    (typeof GetApiSalesDetailsId500Error)[keyof typeof GetApiSalesDetailsId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiSalesDetailsId500Error = {
    Bad_Request: 'Bad Request',
} as const;
