/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2SearchResult200DataItemCategoriesItemImage } from './getApiMarketplaceV2SearchResult200DataItemCategoriesItemImage';

export type GetApiMarketplaceV2SearchResult200DataItemCategoriesItem = {
    id: number;
    category: string;
    image: GetApiMarketplaceV2SearchResult200DataItemCategoriesItemImage;
};
