/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiIotDevices200DevicesItem } from './getApiIotDevices200DevicesItem';

export type GetApiIotDevices200 = {
    devices?: GetApiIotDevices200DevicesItem[];
    total?: number;
};
