/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTaxReportsTypeTaxType } from './getApiInsightsTaxReportsTypeTaxType';

export type GetApiInsightsTaxReportsTypeParams = {
    fromDate?: string;
    toDate?: string;
    outletId?: number;
    employeeId?: number;
    taxType?: GetApiInsightsTaxReportsTypeTaxType;
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
};
