/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomersCustomerIdGroups200ItemDescription } from './getApiCustomersCustomerIdGroups200ItemDescription';

export type GetApiCustomersCustomerIdGroups200Item = {
    id?: string;
    name?: string;
    description?: GetApiCustomersCustomerIdGroups200ItemDescription;
    isActive?: boolean;
    createdAt?: string;
    joinedAt?: string;
};
