/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsAppointmentsByTimeGroupBy } from './getApiStatisticsAppointmentsByTimeGroupBy';
import type { GetApiStatisticsAppointmentsByTimeSource } from './getApiStatisticsAppointmentsByTimeSource';
import type { GetApiStatisticsAppointmentsByTimeDateFilterType } from './getApiStatisticsAppointmentsByTimeDateFilterType';
import type { GetApiStatisticsAppointmentsByTimeStatus } from './getApiStatisticsAppointmentsByTimeStatus';

export type GetApiStatisticsAppointmentsByTimeParams = {
    /**
     * Service ID or null for all services
     */
    serviceId?: number | null;
    /**
     * Group by time slots (24 hours) or week days
     */
    groupBy: GetApiStatisticsAppointmentsByTimeGroupBy;
    /**
     * Booking source filter
     */
    source: GetApiStatisticsAppointmentsByTimeSource;
    /**
     * Filter by booking date or created date
     */
    dateFilterType: GetApiStatisticsAppointmentsByTimeDateFilterType;
    /**
     * Start date in YYYY-MM-DD format
     */
    fromDate: string;
    /**
     * End date in YYYY-MM-DD format
     */
    toDate: string;
    status?: GetApiStatisticsAppointmentsByTimeStatus;
};
