/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2GetPaymentInfoOutletId200Data = {
    payment_enabled?: boolean;
    token_scope?: string;
    api_key?: string;
};
