/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceAdvancedReminderTemplatesSortBy =
    (typeof GetApiServiceAdvancedReminderTemplatesSortBy)[keyof typeof GetApiServiceAdvancedReminderTemplatesSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceAdvancedReminderTemplatesSortBy = {
    reminderTemplateName: 'reminderTemplateName',
    createdAt: 'createdAt',
    reminderMinutes: 'reminderMinutes',
} as const;
