/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsSalesGrouping =
    (typeof GetApiStatisticsSalesGrouping)[keyof typeof GetApiStatisticsSalesGrouping];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiStatisticsSalesGrouping = {
    daily: 'daily',
    weekly: 'weekly',
    monthly: 'monthly',
    yearly: 'yearly',
} as const;
