/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarations500Error } from './getApiHealthDeclarations500Error';

export type GetApiHealthDeclarations500 = {
    statusCode: number;
    error: GetApiHealthDeclarations500Error;
    message: string;
};
