/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiWebhooksEvent = (typeof GetApiWebhooksEvent)[keyof typeof GetApiWebhooksEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiWebhooksEvent = {
    customercreated: 'customer.created',
    customerupdated: 'customer.updated',
    customerdeleted: 'customer.deleted',
} as const;
