/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsGrouped200Grouping =
    (typeof GetApiStatisticsGrouped200Grouping)[keyof typeof GetApiStatisticsGrouped200Grouping];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiStatisticsGrouped200Grouping = {
    weekly: 'weekly',
    monthly: 'monthly',
    yearly: 'yearly',
} as const;
