/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerIdType500Error =
    (typeof GetApiCustomerIdType500Error)[keyof typeof GetApiCustomerIdType500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerIdType500Error = {
    Bad_Request: 'Bad Request',
} as const;
