/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiHealthDeclarationsSortBy =
    (typeof GetApiHealthDeclarationsSortBy)[keyof typeof GetApiHealthDeclarationsSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiHealthDeclarationsSortBy = {
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    status: 'status',
    submittedAt: 'submittedAt',
} as const;
