/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsExportAppointmentsByTimeSource =
    (typeof GetApiStatisticsExportAppointmentsByTimeSource)[keyof typeof GetApiStatisticsExportAppointmentsByTimeSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiStatisticsExportAppointmentsByTimeSource = {
    STOREAPP: 'STOREAPP',
    DIRECTWEBSTORE: 'DIRECTWEBSTORE',
    ALL: 'ALL',
} as const;
