/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCalendlyCallback400Error =
    (typeof GetApiCalendlyCallback400Error)[keyof typeof GetApiCalendlyCallback400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCalendlyCallback400Error = {
    Bad_Request: 'Bad Request',
} as const;
