/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesDetailsId200TransactionsItemCustomerId } from './getApiSalesDetailsId200TransactionsItemCustomerId';
import type { GetApiSalesDetailsId200TransactionsItemPaymentId } from './getApiSalesDetailsId200TransactionsItemPaymentId';
import type { GetApiSalesDetailsId200TransactionsItemCurrency } from './getApiSalesDetailsId200TransactionsItemCurrency';
import type { GetApiSalesDetailsId200TransactionsItemTxStatus } from './getApiSalesDetailsId200TransactionsItemTxStatus';
import type { GetApiSalesDetailsId200TransactionsItemTerminalId } from './getApiSalesDetailsId200TransactionsItemTerminalId';
import type { GetApiSalesDetailsId200TransactionsItemTerminalRefId } from './getApiSalesDetailsId200TransactionsItemTerminalRefId';
import type { GetApiSalesDetailsId200TransactionsItemTerminalStatus } from './getApiSalesDetailsId200TransactionsItemTerminalStatus';
import type { GetApiSalesDetailsId200TransactionsItemCardType } from './getApiSalesDetailsId200TransactionsItemCardType';
import type { GetApiSalesDetailsId200TransactionsItemCardFourDigit } from './getApiSalesDetailsId200TransactionsItemCardFourDigit';
import type { GetApiSalesDetailsId200TransactionsItemPaymentType } from './getApiSalesDetailsId200TransactionsItemPaymentType';
import type { GetApiSalesDetailsId200TransactionsItemTransactionType } from './getApiSalesDetailsId200TransactionsItemTransactionType';
import type { GetApiSalesDetailsId200TransactionsItemTerminalResponse } from './getApiSalesDetailsId200TransactionsItemTerminalResponse';
import type { GetApiSalesDetailsId200TransactionsItemCreatedAt } from './getApiSalesDetailsId200TransactionsItemCreatedAt';
import type { GetApiSalesDetailsId200TransactionsItemUpdatedAt } from './getApiSalesDetailsId200TransactionsItemUpdatedAt';

export type GetApiSalesDetailsId200TransactionsItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesId: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    customerId: GetApiSalesDetailsId200TransactionsItemCustomerId;
    paymentId: GetApiSalesDetailsId200TransactionsItemPaymentId;
    receiptId: string;
    currency: GetApiSalesDetailsId200TransactionsItemCurrency;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change: number;
    txStatus: GetApiSalesDetailsId200TransactionsItemTxStatus;
    terminalId: GetApiSalesDetailsId200TransactionsItemTerminalId;
    terminalRefId: GetApiSalesDetailsId200TransactionsItemTerminalRefId;
    terminalStatus: GetApiSalesDetailsId200TransactionsItemTerminalStatus;
    cardType: GetApiSalesDetailsId200TransactionsItemCardType;
    cardFourDigit: GetApiSalesDetailsId200TransactionsItemCardFourDigit;
    paymentType: GetApiSalesDetailsId200TransactionsItemPaymentType;
    transactionType: GetApiSalesDetailsId200TransactionsItemTransactionType;
    terminalResponse: GetApiSalesDetailsId200TransactionsItemTerminalResponse;
    createdAt: GetApiSalesDetailsId200TransactionsItemCreatedAt;
    updatedAt: GetApiSalesDetailsId200TransactionsItemUpdatedAt;
};
