/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType =
    (typeof GetApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType)[keyof typeof GetApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBundleOffersSoldIdType200ItemBundleOfferBundleOfferType = {
    PUNCH_BASED: 'PUNCH_BASED',
    SERVICE_BASED: 'SERVICE_BASED',
} as const;
