/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServicesDeposit200DataGroupedServicesItem } from './getApiServicesDeposit200DataGroupedServicesItem';
import type { GetApiServicesDeposit200DataDepositSetting } from './getApiServicesDeposit200DataDepositSetting';

export type GetApiServicesDeposit200Data = {
    groupedServices?: GetApiServicesDeposit200DataGroupedServicesItem[];
    depositSetting?: GetApiServicesDeposit200DataDepositSetting;
};
