/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Internal server error
 */
export type GetApiStatisticsExportAppointments500 = {
    error?: string;
    message?: string;
};
