/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSummaryItemTypeTypeEmployeeIdAnyOf } from './getApiInsightsSummaryItemTypeTypeEmployeeIdAnyOf';

export type GetApiInsightsSummaryItemTypeTypeParams = {
    employeeId?: GetApiInsightsSummaryItemTypeTypeEmployeeIdAnyOf | null;
    /**
     * Start date in DD-MM-YYYY or YYYY-MM-DD format
     */
    fromDate?: string;
    /**
     * End date in DD-MM-YYYY or YYYY-MM-DD format
     */
    toDate?: string;
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
};
