/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsCustomerStatistics200DataItem = {
    employeeId: number;
    employeeName: string;
    newCustomerCount: number;
    averageRevenuePerCustomer: number;
    totalRevenue: number;
    totalCustomers: number;
};
