/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsCampaignIdStatisticsRecipients200ItemEmail } from './getApiCampaignsCampaignIdStatisticsRecipients200ItemEmail';
import type { GetApiCampaignsCampaignIdStatisticsRecipients200ItemName } from './getApiCampaignsCampaignIdStatisticsRecipients200ItemName';
import type { GetApiCampaignsCampaignIdStatisticsRecipients200ItemPhoneNumber } from './getApiCampaignsCampaignIdStatisticsRecipients200ItemPhoneNumber';

export type GetApiCampaignsCampaignIdStatisticsRecipients200Item = {
    outletCustomerId: number;
    email?: GetApiCampaignsCampaignIdStatisticsRecipients200ItemEmail;
    name?: GetApiCampaignsCampaignIdStatisticsRecipients200ItemName;
    phoneNumber?: GetApiCampaignsCampaignIdStatisticsRecipients200ItemPhoneNumber;
    /** Delivery status of the message */
    status: string;
    /** Delivery status of the message */
    deliveryStatus: string;
    /** Whether the statistics was manually updated */
    isManuallyUpdated: boolean;
};
