/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBooking500Error } from './getApiBooking500Error';

export type GetApiBooking500 = {
    statusCode: number;
    error: GetApiBooking500Error;
    message: string;
};
