/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsId200CategoryAnyOf } from './getApiProductsId200CategoryAnyOf';

export type GetApiProductsId200Category = GetApiProductsId200CategoryAnyOf | null;
