/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSupplierListPrintType500Error } from './getApiSupplierListPrintType500Error';

export type GetApiSupplierListPrintType500 = {
    statusCode: number;
    error: GetApiSupplierListPrintType500Error;
    message: string;
};
