/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBookingsNoShowReminder500DataItem = {
    id?: number;
    status?: string;
    bookingDatetimeStart?: string;
    totalAmount?: string;
    serviceId?: number;
    /** @nullable */
    userId?: number | null;
    outletId?: number;
    createdAt?: string;
    updatedAt?: string;
    /** @nullable */
    deletedAt?: string | null;
    bookingDatetimeEnd?: string;
    /** @nullable */
    employeeId?: number | null;
    /** @nullable */
    salesId?: string | null;
    /** @nullable */
    serviceName?: string | null;
    /** @nullable */
    servicePrice?: string | null;
    /** @nullable */
    customerName?: string | null;
    /** @nullable */
    customerPhone?: string | null;
    /** @nullable */
    customerEmail?: string | null;
    /** @nullable */
    salesNetTotal?: string | null;
    /** @nullable */
    salesTenderAmount?: string | null;
    /** @nullable */
    transactionId?: string | null;
    /** @nullable */
    transactionStatus?: string | null;
    /** @nullable */
    transactionAmount?: string | null;
    /** @nullable */
    transactionPaymentType?: string | null;
};
