/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsMonday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsMonday';
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsTuesday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsTuesday';
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsWednesday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsWednesday';
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsThursday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsThursday';
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsFriday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsFriday';
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSaturday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSaturday';
import type { GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSunday } from './getApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSunday';

export type GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotals = {
    monday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsMonday;
    tuesday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsTuesday;
    wednesday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsWednesday;
    thursday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsThursday;
    friday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsFriday;
    saturday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSaturday;
    sunday: GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSunday;
};
