/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBooking200Data } from './getApiBooking200Data';

/**
 * Booking details with main booking and grouped bookings
 */
export type GetApiBooking200 = {
    success?: boolean;
    msg?: string;
    data?: GetApiBooking200Data;
};
