/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsId200Description } from './getApiCampaignsId200Description';
import type { GetApiCampaignsId200TestPhoneNumber } from './getApiCampaignsId200TestPhoneNumber';
import type { GetApiCampaignsId200TestEmail } from './getApiCampaignsId200TestEmail';
import type { GetApiCampaignsId200BccEmail } from './getApiCampaignsId200BccEmail';
import type { GetApiCampaignsId200ConditionsItem } from './getApiCampaignsId200ConditionsItem';
import type { GetApiCampaignsId200Content } from './getApiCampaignsId200Content';
import type { GetApiCampaignsId200Schedule } from './getApiCampaignsId200Schedule';

export type GetApiCampaignsId200 = {
    id?: string;
    outletId?: number;
    name?: string;
    description?: GetApiCampaignsId200Description;
    messageType?: string;
    campaignType?: string;
    campaignStatus?: string;
    testPhoneNumber?: GetApiCampaignsId200TestPhoneNumber;
    testEmail?: GetApiCampaignsId200TestEmail;
    bccEmail?: GetApiCampaignsId200BccEmail;
    createdAt?: string;
    updatedAt?: string;
    /** Total number of recipients for this campaign */
    totalRecipients?: number;
    /** Per-SMS charge when campaign type is SMS (0.70), otherwise 0 */
    perSmsCharge?: number;
    /** Per-email charge when campaign type is SMS (0.00), otherwise 0 */
    perEmailCharge?: number;
    conditions?: GetApiCampaignsId200ConditionsItem[];
    content?: GetApiCampaignsId200Content;
    schedule?: GetApiCampaignsId200Schedule;
};
