/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersBundleOfferType } from './getApiBundleOffersBundleOfferType';

export type GetApiBundleOffersParams = {
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    bundleOfferType?: GetApiBundleOffersBundleOfferType;
    /**
     * Search by bundle offer name or description
     */
    keyword?: string;
    /**
     * Start date in YYYY-MM-DD format
     */
    fromDate?: string;
    /**
     * End date in YYYY-MM-DD format
     */
    toDate?: string;
};
