/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAddons400Error } from './getApiAddons400Error';

export type GetApiAddons400 = {
    statusCode: number;
    error: GetApiAddons400Error;
    message: string;
};
