/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomersParams = {
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 10000
     */
    limit?: number;
    /**
     * Search by name, email, or phone number
     */
    search?: string;
    /**
     * Filter customers who have unused or partially used gift cards
     */
    hasUnusedGiftCards?: boolean;
};
