/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSaleId200ShortInvoiceId } from './getApiSaleId200ShortInvoiceId';
import type { GetApiSaleId200CustomerId } from './getApiSaleId200CustomerId';
import type { GetApiSaleId200CustomerName } from './getApiSaleId200CustomerName';
import type { GetApiSaleId200Tips } from './getApiSaleId200Tips';
import type { GetApiSaleId200SalesNote } from './getApiSaleId200SalesNote';
import type { GetApiSaleId200VoidId } from './getApiSaleId200VoidId';
import type { GetApiSaleId200SalesType } from './getApiSaleId200SalesType';
import type { GetApiSaleId200CreatedBy } from './getApiSaleId200CreatedBy';
import type { GetApiSaleId200UpdatedBy } from './getApiSaleId200UpdatedBy';
import type { GetApiSaleId200SellBy } from './getApiSaleId200SellBy';
import type { GetApiSaleId200SyncedWith } from './getApiSaleId200SyncedWith';
import type { GetApiSaleId200SyncId } from './getApiSaleId200SyncId';

export type GetApiSaleId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    invAutoNumber: number;
    salesDate: string;
    invoiceId: string;
    shortInvoiceId: GetApiSaleId200ShortInvoiceId;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    customerId: GetApiSaleId200CustomerId;
    customerName: GetApiSaleId200CustomerName;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    subTotal: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalTax: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalDiscount: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    netTotal: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    roundOff: number;
    tips: GetApiSaleId200Tips;
    salesNote: GetApiSaleId200SalesNote;
    voidId: GetApiSaleId200VoidId;
    salesType: GetApiSaleId200SalesType;
    createdBy: GetApiSaleId200CreatedBy;
    updatedBy: GetApiSaleId200UpdatedBy;
    sellBy: GetApiSaleId200SellBy;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    sourceId: number;
    syncedWith: GetApiSaleId200SyncedWith;
    syncId: GetApiSaleId200SyncId;
    createdAt: string;
    updatedAt: string;
};
