/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerGroupsId200OutletId } from './getApiCustomerGroupsId200OutletId';
import type { GetApiCustomerGroupsId200Description } from './getApiCustomerGroupsId200Description';
import type { GetApiCustomerGroupsId200CreatedBy } from './getApiCustomerGroupsId200CreatedBy';
import type { GetApiCustomerGroupsId200UpdatedBy } from './getApiCustomerGroupsId200UpdatedBy';
import type { GetApiCustomerGroupsId200DeletedAt } from './getApiCustomerGroupsId200DeletedAt';
import type { GetApiCustomerGroupsId200MembersItem } from './getApiCustomerGroupsId200MembersItem';

export type GetApiCustomerGroupsId200 = {
    id: string;
    outletId?: GetApiCustomerGroupsId200OutletId;
    name: string;
    description?: GetApiCustomerGroupsId200Description;
    createdAt: string;
    createdBy?: GetApiCustomerGroupsId200CreatedBy;
    updatedAt: string;
    updatedBy?: GetApiCustomerGroupsId200UpdatedBy;
    deletedAt?: GetApiCustomerGroupsId200DeletedAt;
    isActive: boolean;
    customerCount?: number;
    members?: GetApiCustomerGroupsId200MembersItem[];
    memberCount?: number;
};
