/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetApiBundleOffersCodeBundleOfferCode200Employee = {
    id: number;
    name: string;
    /** @nullable */
    phoneNumber?: string | null;
} | null;
