/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiDoctorsPortalMessages403Error } from './getApiDoctorsPortalMessages403Error';

export type GetApiDoctorsPortalMessages403 = {
    statusCode: number;
    error: GetApiDoctorsPortalMessages403Error;
    message: string;
};
