/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarationPrintIdType400Error } from './getApiHealthDeclarationPrintIdType400Error';

export type GetApiHealthDeclarationPrintIdType400 = {
    statusCode: number;
    error: GetApiHealthDeclarationPrintIdType400Error;
    message: string;
};
