/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerIdType200OneOfItemStatus =
    (typeof GetApiCustomerIdType200OneOfItemStatus)[keyof typeof GetApiCustomerIdType200OneOfItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerIdType200OneOfItemStatus = {
    UNUSED: 'UNUSED',
    PARTIALLY_USED: 'PARTIALLY_USED',
    USED: 'USED',
} as const;
