/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerIdType200OneOfItem } from './getApiCustomerIdType200OneOfItem';
import type { GetApiCustomerIdType200OneOfThreeItem } from './getApiCustomerIdType200OneOfThreeItem';
import type { GetApiCustomerIdType200OneOfOnefourItem } from './getApiCustomerIdType200OneOfOnefourItem';
import type { GetApiCustomerIdType200OneOfOnefiveItem } from './getApiCustomerIdType200OneOfOnefiveItem';

export type GetApiCustomerIdType200 =
    | GetApiCustomerIdType200OneOfItem[]
    | GetApiCustomerIdType200OneOfThreeItem[]
    | GetApiCustomerIdType200OneOfOnefourItem[]
    | GetApiCustomerIdType200OneOfOnefiveItem[];
