/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceGroupsIdDrivingFees500Error =
    (typeof GetApiServiceGroupsIdDrivingFees500Error)[keyof typeof GetApiServiceGroupsIdDrivingFees500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceGroupsIdDrivingFees500Error = {
    Bad_Request: 'Bad Request',
} as const;
