/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomers200CustomersItemBundleOffersItemBundleOfferType =
    (typeof GetApiCustomers200CustomersItemBundleOffersItemBundleOfferType)[keyof typeof GetApiCustomers200CustomersItemBundleOffersItemBundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomers200CustomersItemBundleOffersItemBundleOfferType = {
    FIXED: 'FIXED',
    VARIABLE: 'VARIABLE',
} as const;
