/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomers200CustomersItemGiftCardsItemExpiryDate } from './getApiCustomers200CustomersItemGiftCardsItemExpiryDate';
import type { GetApiCustomers200CustomersItemGiftCardsItemStatus } from './getApiCustomers200CustomersItemGiftCardsItemStatus';

export type GetApiCustomers200CustomersItemGiftCardsItem = {
    id: string;
    giftCardCode: string;
    residueValue: number;
    expiryDate?: GetApiCustomers200CustomersItemGiftCardsItemExpiryDate;
    originalValue: number;
    status: GetApiCustomers200CustomersItemGiftCardsItemStatus;
};
