/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Outlet200DataSchedulesItem = {
    day?: string;
    open_time?: string;
    close_time?: string;
    is_closed?: boolean;
    open_by_appointment?: boolean;
};
