/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPaymentsSubscriptionOutletOutletId200Data } from './getApiPaymentsSubscriptionOutletOutletId200Data';

export type GetApiPaymentsSubscriptionOutletOutletId200 = {
    success?: boolean;
    data?: GetApiPaymentsSubscriptionOutletOutletId200Data;
};
