/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod } from './getApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod';

export type GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItem = {
    paymentMethod: GetApiInsightsEmployeePaymentsType200DataEmployeesItemPaymentMethodsItemPaymentMethod;
    paid: number;
    credited: number;
    total: number;
};
