/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceSubscriptionCustomer500Error =
    (typeof GetApiServiceSubscriptionCustomer500Error)[keyof typeof GetApiServiceSubscriptionCustomer500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceSubscriptionCustomer500Error = {
    Bad_Request: 'Bad Request',
} as const;
