/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiListSuppliers500Error } from './getApiListSuppliers500Error';

export type GetApiListSuppliers500 = {
    statusCode: number;
    error: GetApiListSuppliers500Error;
    message: string;
};
