/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsCodeCode200CustomerAnyOfEmail } from './getApiGiftCardsCodeCode200CustomerAnyOfEmail';

export type GetApiGiftCardsCodeCode200CustomerAnyOf = {
    id: number;
    name: string;
    email: GetApiGiftCardsCodeCode200CustomerAnyOfEmail;
    phoneNumber: string;
};
