/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsAppointmentsByTime200BarChartData } from './getApiStatisticsAppointmentsByTime200BarChartData';
import type { GetApiStatisticsAppointmentsByTime200ListData } from './getApiStatisticsAppointmentsByTime200ListData';
import type { GetApiStatisticsAppointmentsByTime200ItemsItem } from './getApiStatisticsAppointmentsByTime200ItemsItem';
import type { GetApiStatisticsAppointmentsByTime200GroupBy } from './getApiStatisticsAppointmentsByTime200GroupBy';
import type { GetApiStatisticsAppointmentsByTime200Summary } from './getApiStatisticsAppointmentsByTime200Summary';

/**
 * Successfully retrieved appointment by time statistics
 */
export type GetApiStatisticsAppointmentsByTime200 = {
    barChartData: GetApiStatisticsAppointmentsByTime200BarChartData;
    listData: GetApiStatisticsAppointmentsByTime200ListData;
    items: GetApiStatisticsAppointmentsByTime200ItemsItem[];
    totalCount: number;
    groupBy: GetApiStatisticsAppointmentsByTime200GroupBy;
    summary: GetApiStatisticsAppointmentsByTime200Summary;
};
