/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductCategories500Error } from './getApiProductCategories500Error';

export type GetApiProductCategories500 = {
    statusCode: number;
    error: GetApiProductCategories500Error;
    message: string;
};
