/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiDoctorsPortalMessages500Error } from './getApiDoctorsPortalMessages500Error';

export type GetApiDoctorsPortalMessages500 = {
    statusCode: number;
    error: GetApiDoctorsPortalMessages500Error;
    message: string;
};
