/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBillyExport500Error = (typeof GetApiBillyExport500Error)[keyof typeof GetApiBillyExport500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBillyExport500Error = {
    Bad_Request: 'Bad Request',
} as const;
