/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAddons200DataItemAddonsItemMeta } from './getApiAddons200DataItemAddonsItemMeta';

export type GetApiAddons200DataItemAddonsItem = {
    id: number;
    label: string;
    isActive: boolean;
    meta?: GetApiAddons200DataItemAddonsItemMeta;
};
