/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBundleOffersSoldIdType200ItemBundleOfferType =
    (typeof GetApiBundleOffersSoldIdType200ItemBundleOfferType)[keyof typeof GetApiBundleOffersSoldIdType200ItemBundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBundleOffersSoldIdType200ItemBundleOfferType = {
    PUNCH_BASED: 'PUNCH_BASED',
    SERVICE_BASED: 'SERVICE_BASED',
} as const;
