/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGoogleCalendarBookingStatusByGroupUuid200DataBookingsItem = {
    bookingId?: number;
    /** @nullable */
    bookingUuid?: string | null;
    status?: string;
};
