/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiExpensesSortBy = (typeof GetApiExpensesSortBy)[keyof typeof GetApiExpensesSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiExpensesSortBy = {
    amount: 'amount',
    createdAt: 'createdAt',
} as const;
