/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProductCategories500Error =
    (typeof GetApiProductCategories500Error)[keyof typeof GetApiProductCategories500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiProductCategories500Error = {
    Bad_Request: 'Bad Request',
} as const;
