/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus =
    (typeof GetApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus)[keyof typeof GetApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceSubscriptionCustomer200DataItemSubscriptionSubscriptionStatus = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
} as const;
