/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBooking500Error = (typeof GetApiBooking500Error)[keyof typeof GetApiBooking500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBooking500Error = {
    Bad_Request: 'Bad Request',
} as const;
