/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBookingsExport400Error =
    (typeof GetApiBookingsExport400Error)[keyof typeof GetApiBookingsExport400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookingsExport400Error = {
    Bad_Request: 'Bad Request',
} as const;
