/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiKlaviyoConfig200DataAnyOf } from './getApiKlaviyoConfig200DataAnyOf';

export type GetApiKlaviyoConfig200Data = GetApiKlaviyoConfig200DataAnyOf | null;
