/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMobilepayPaymentStatusReference200Data } from './getApiMobilepayPaymentStatusReference200Data';

export type GetApiMobilepayPaymentStatusReference200 = {
    success: boolean;
    data: GetApiMobilepayPaymentStatusReference200Data;
};
