/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTrustpilotConfig500Error } from './getApiTrustpilotConfig500Error';

export type GetApiTrustpilotConfig500 = {
    statusCode: number;
    error: GetApiTrustpilotConfig500Error;
    message: string;
};
