/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiPaymentsSubscriptionOutletOutletId400Error =
    (typeof GetApiPaymentsSubscriptionOutletOutletId400Error)[keyof typeof GetApiPaymentsSubscriptionOutletOutletId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiPaymentsSubscriptionOutletOutletId400Error = {
    Bad_Request: 'Bad Request',
} as const;
