/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTaxReportsType500Error } from './getApiInsightsTaxReportsType500Error';

export type GetApiInsightsTaxReportsType500 = {
    statusCode: number;
    error: GetApiInsightsTaxReportsType500Error;
    message: string;
};
