/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceSubscriptionCustomer200DataItemTransactionsItemDeletedAt } from './getApiServiceSubscriptionCustomer200DataItemTransactionsItemDeletedAt';

export type GetApiServiceSubscriptionCustomer200DataItemTransactionsItem = {
    id: string;
    serviceSubscriptionId: string;
    bookingId: number;
    outletId: number;
    salesId: string;
    invoiceNo: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: GetApiServiceSubscriptionCustomer200DataItemTransactionsItemDeletedAt;
};
