/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiHealthDeclarationPrintIdType400Error =
    (typeof GetApiHealthDeclarationPrintIdType400Error)[keyof typeof GetApiHealthDeclarationPrintIdType400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiHealthDeclarationPrintIdType400Error = {
    Bad_Request: 'Bad Request',
} as const;
