/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPaymentsSubscriptionOutletOutletId500Error } from './getApiPaymentsSubscriptionOutletOutletId500Error';

export type GetApiPaymentsSubscriptionOutletOutletId500 = {
    statusCode: number;
    error: GetApiPaymentsSubscriptionOutletOutletId500Error;
    message: string;
};
