/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsExportAppointmentsParams = {
    fromDate?: string;
    toDate?: string;
    /**
     * Array of booking statuses to filter by
     */
    status?: string[];
};
