/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiExpenses200ExpensesItem } from './getApiExpenses200ExpensesItem';

export type GetApiExpenses200 = {
    currentPage: number;
    totalPages: number;
    limit: number;
    total: number;
    expenses: GetApiExpenses200ExpensesItem[];
};
