/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPublicHealthDeclarationsForm200Data } from './getApiPublicHealthDeclarationsForm200Data';

export type GetApiPublicHealthDeclarationsForm200 = {
    statusCode: number;
    message: string;
    success: boolean;
    data: GetApiPublicHealthDeclarationsForm200Data;
};
