/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSupplierId200Address } from './getApiSupplierId200Address';
import type { GetApiSupplierId200City } from './getApiSupplierId200City';
import type { GetApiSupplierId200ZipCode } from './getApiSupplierId200ZipCode';
import type { GetApiSupplierId200Country } from './getApiSupplierId200Country';
import type { GetApiSupplierId200Email } from './getApiSupplierId200Email';
import type { GetApiSupplierId200CountryCode } from './getApiSupplierId200CountryCode';
import type { GetApiSupplierId200Phone } from './getApiSupplierId200Phone';
import type { GetApiSupplierId200CountryISOCode } from './getApiSupplierId200CountryISOCode';
import type { GetApiSupplierId200Website } from './getApiSupplierId200Website';
import type { GetApiSupplierId200Description } from './getApiSupplierId200Description';
import type { GetApiSupplierId200CvrNumber } from './getApiSupplierId200CvrNumber';
import type { GetApiSupplierId200ContactPersonName } from './getApiSupplierId200ContactPersonName';
import type { GetApiSupplierId200ContactPersonEmail } from './getApiSupplierId200ContactPersonEmail';
import type { GetApiSupplierId200ContactPersonPhone } from './getApiSupplierId200ContactPersonPhone';
import type { GetApiSupplierId200OutletId } from './getApiSupplierId200OutletId';

export type GetApiSupplierId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    address: GetApiSupplierId200Address;
    city: GetApiSupplierId200City;
    zipCode: GetApiSupplierId200ZipCode;
    country: GetApiSupplierId200Country;
    email: GetApiSupplierId200Email;
    countryCode: GetApiSupplierId200CountryCode;
    phone: GetApiSupplierId200Phone;
    countryISOCode: GetApiSupplierId200CountryISOCode;
    website: GetApiSupplierId200Website;
    description: GetApiSupplierId200Description;
    cvrNumber: GetApiSupplierId200CvrNumber;
    contactPersonName: GetApiSupplierId200ContactPersonName;
    contactPersonEmail: GetApiSupplierId200ContactPersonEmail;
    contactPersonPhone: GetApiSupplierId200ContactPersonPhone;
    outletId: GetApiSupplierId200OutletId;
    createdAt: string;
    updatedAt: string;
};
