/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2Recommended500Error } from './getApiMarketplaceV2Recommended500Error';

export type GetApiMarketplaceV2Recommended500 = {
    statusCode: number;
    error: GetApiMarketplaceV2Recommended500Error;
    message: string;
};
