/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGoogleCalendarCallback400Error } from './getApiGoogleCalendarCallback400Error';

export type GetApiGoogleCalendarCallback400 = {
    statusCode: number;
    error: GetApiGoogleCalendarCallback400Error;
    message: string;
};
