/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTax500Error } from './getApiTax500Error';

export type GetApiTax500 = {
    statusCode: number;
    error: GetApiTax500Error;
    message: string;
};
