/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Outlet200DataServicesItemServicesItemEmployeesItem = {
    id?: number;
    name?: string;
    /** @nullable */
    image?: string | null;
    price?: string;
};
