/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBundleOfferServiceList500Error =
    (typeof GetApiBundleOfferServiceList500Error)[keyof typeof GetApiBundleOfferServiceList500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBundleOfferServiceList500Error = {
    Bad_Request: 'Bad Request',
} as const;
