/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookingsExport400Error } from './getApiBookingsExport400Error';

export type GetApiBookingsExport400 = {
    statusCode: number;
    error: GetApiBookingsExport400Error;
    message: string;
};
