/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSalesDetailsId200ItemsItemDiscountsItemAmountType =
    (typeof GetApiSalesDetailsId200ItemsItemDiscountsItemAmountType)[keyof typeof GetApiSalesDetailsId200ItemsItemDiscountsItemAmountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiSalesDetailsId200ItemsItemDiscountsItemAmountType = {
    AMOUNT: 'AMOUNT',
    PERCENTAGE: 'PERCENTAGE',
    VARIABLE_AMOUNT: 'VARIABLE_AMOUNT',
    VARIABLE_PERCENTAGE: 'VARIABLE_PERCENTAGE',
} as const;
