/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiWebhooks500Error } from './getApiWebhooks500Error';

export type GetApiWebhooks500 = {
    statusCode: number;
    error: GetApiWebhooks500Error;
    message: string;
};
