/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesDetailsItemTypeIdType400Error } from './getApiInsightsSalesDetailsItemTypeIdType400Error';

export type GetApiInsightsSalesDetailsItemTypeIdType400 = {
    statusCode: number;
    error: GetApiInsightsSalesDetailsItemTypeIdType400Error;
    message: string;
};
