/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarations200DataItemsItemReviewedByAnyOfEmployeeName } from './getApiHealthDeclarations200DataItemsItemReviewedByAnyOfEmployeeName';

/**
 * @nullable
 */
export type GetApiHealthDeclarations200DataItemsItemReviewedByAnyOf = {
    employeeId?: number;
    employeeName?: GetApiHealthDeclarations200DataItemsItemReviewedByAnyOfEmployeeName;
} | null;
