/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBundleOffersId200BundleOfferType =
    (typeof GetApiBundleOffersId200BundleOfferType)[keyof typeof GetApiBundleOffersId200BundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBundleOffersId200BundleOfferType = {
    PUNCH_BASED: 'PUNCH_BASED',
    SERVICE_BASED: 'SERVICE_BASED',
} as const;
