/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTaxReportsType400Error } from './getApiInsightsTaxReportsType400Error';

export type GetApiInsightsTaxReportsType400 = {
    statusCode: number;
    error: GetApiInsightsTaxReportsType400Error;
    message: string;
};
