/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomers200CustomersItemBundleOffersItemApplicableServicesServices } from './getApiCustomers200CustomersItemBundleOffersItemApplicableServicesServices';
import type { GetApiCustomers200CustomersItemBundleOffersItemApplicableServicesResiduePunch } from './getApiCustomers200CustomersItemBundleOffersItemApplicableServicesResiduePunch';
import type { GetApiCustomers200CustomersItemBundleOffersItemApplicableServicesOriginalPunch } from './getApiCustomers200CustomersItemBundleOffersItemApplicableServicesOriginalPunch';

export type GetApiCustomers200CustomersItemBundleOffersItemApplicableServices = {
    services: GetApiCustomers200CustomersItemBundleOffersItemApplicableServicesServices;
    residuePunch: GetApiCustomers200CustomersItemBundleOffersItemApplicableServicesResiduePunch;
    originalPunch: GetApiCustomers200CustomersItemBundleOffersItemApplicableServicesOriginalPunch;
};
