/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2SearchResult500Error =
    (typeof GetApiMarketplaceV2SearchResult500Error)[keyof typeof GetApiMarketplaceV2SearchResult500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiMarketplaceV2SearchResult500Error = {
    Bad_Request: 'Bad Request',
} as const;
