/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataWeeksItemTuesdayDayName } from './getApiInsightsWeeklyTurnoverType200DataWeeksItemTuesdayDayName';

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemTuesday = {
    date: string;
    dayName: GetApiInsightsWeeklyTurnoverType200DataWeeksItemTuesdayDayName;
    totalRevenue: number;
    totalCredit: number;
    transactionCount: number;
    averageTransactionValue: number;
};
