/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsId200ScheduleTriggerDaysAnyOfItem } from './getApiCampaignsId200ScheduleTriggerDaysAnyOfItem';

export type GetApiCampaignsId200ScheduleTriggerDays = null | GetApiCampaignsId200ScheduleTriggerDaysAnyOfItem[];
