/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsCodeCode200HistoryItemInvoiceNumber } from './getApiGiftCardsCodeCode200HistoryItemInvoiceNumber';

export type GetApiGiftCardsCodeCode200HistoryItem = {
    salesId: string;
    invoiceNumber: GetApiGiftCardsCodeCode200HistoryItemInvoiceNumber;
    amountUsed: number;
    dateTime: string;
};
