/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDineroOrganizations200DataItem = {
    Id: string;
    Name: string;
    CompanyTypeKey: string;
    IsVatFree: boolean;
    Email: string;
    Phone: string;
    Street: string;
    City: string;
    ZipCode: string;
    AttPerson: string;
    IsTaxFreeUnion: boolean;
    VatNumber: string;
    CountryKey: string;
    Website: string;
    RoleKey: string;
};
