/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemCustomerId } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemCustomerId';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemCustomerName } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemCustomerName';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemProductId } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemProductId';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemServiceId } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemServiceId';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemItemType } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemItemType';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemEmployeeId } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemEmployeeId';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemEmployeeName } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemEmployeeName';

export type GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItem = {
    salesId: string;
    invoiceId: string;
    salesDate: string;
    salesTime: string;
    customerId: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemCustomerId;
    customerName: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemCustomerName;
    productId: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemProductId;
    serviceId: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemServiceId;
    itemName: string;
    itemType: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemItemType;
    quantity: number;
    amount: number;
    price: number;
    employeeId: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemEmployeeId;
    employeeName: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItemEmployeeName;
};
