/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerGroupsId500Error } from './getApiCustomerGroupsId500Error';

export type GetApiCustomerGroupsId500 = {
    statusCode: number;
    error: GetApiCustomerGroupsId500Error;
    message: string;
};
