/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSummaryItemTypeType200DataItemsItem } from './getApiInsightsSummaryItemTypeType200DataItemsItem';
import type { GetApiInsightsSummaryItemTypeType200DataSummary } from './getApiInsightsSummaryItemTypeType200DataSummary';
import type { GetApiInsightsSummaryItemTypeType200DataPagination } from './getApiInsightsSummaryItemTypeType200DataPagination';

export type GetApiInsightsSummaryItemTypeType200Data = {
    items: GetApiInsightsSummaryItemTypeType200DataItemsItem[];
    summary: GetApiInsightsSummaryItemTypeType200DataSummary;
    pagination: GetApiInsightsSummaryItemTypeType200DataPagination;
};
