/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName } from './getApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName';

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursday = {
    date: string;
    dayName: GetApiInsightsWeeklyTurnoverType200DataWeeksItemThursdayDayName;
    totalRevenue: number;
    totalCredit: number;
    transactionCount: number;
    averageTransactionValue: number;
};
