/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersId200ApplicableService } from './getApiBundleOffersId200ApplicableService';
import type { GetApiBundleOffersId200BundleOfferType } from './getApiBundleOffersId200BundleOfferType';

export type GetApiBundleOffersId200 = {
    id: string;
    seqId: number;
    outletId: number;
    name: string;
    /** @nullable */
    description: string | null;
    price?: number;
    expiryMonths?: number;
    /** Services on which bundle offer can be applied */
    applicableService: GetApiBundleOffersId200ApplicableService;
    bundleOfferType: GetApiBundleOffersId200BundleOfferType;
    sellOnline: boolean;
    createdAt: string;
    updatedAt: string;
    /** @nullable */
    deletedAt: string | null;
};
