/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTaxReportsType200DataItemsItemEmployee } from './getApiInsightsTaxReportsType200DataItemsItemEmployee';
import type { GetApiInsightsTaxReportsType200DataItemsItemCustomer } from './getApiInsightsTaxReportsType200DataItemsItemCustomer';

export type GetApiInsightsTaxReportsType200DataItemsItem = {
    salesId: string;
    invoiceId: string;
    salesDate: string;
    totalAmount: number;
    totalTaxAmount: number;
    totalQuantity: number;
    itemCount: number;
    employee?: GetApiInsightsTaxReportsType200DataItemsItemEmployee;
    customer?: GetApiInsightsTaxReportsType200DataItemsItemCustomer;
};
