/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCampaignsEmailOverviewParams = {
    /**
     * Start date for filtering (YYYY-MM-DD)
     */
    fromDate?: string;
    /**
     * End date for filtering (YYYY-MM-DD)
     */
    toDate?: string;
};
