/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSaleId500Error } from './getApiSaleId500Error';

export type GetApiSaleId500 = {
    statusCode: number;
    error: GetApiSaleId500Error;
    message: string;
};
