/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAddons200DataItemAddonsItemMetaAnyOf } from './getApiAddons200DataItemAddonsItemMetaAnyOf';

export type GetApiAddons200DataItemAddonsItemMeta = GetApiAddons200DataItemAddonsItemMetaAnyOf | null;
