/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersSoldIdType200ItemApplicableServicesServicesAnyOf } from './getApiBundleOffersSoldIdType200ItemApplicableServicesServicesAnyOf';

export type GetApiBundleOffersSoldIdType200ItemApplicableServicesServices =
    null | GetApiBundleOffersSoldIdType200ItemApplicableServicesServicesAnyOf;
