/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsId200ConditionsItemJsonPathAnyOf } from './getApiCampaignsId200ConditionsItemJsonPathAnyOf';

export type GetApiCampaignsId200ConditionsItemJsonPath =
    | GetApiCampaignsId200ConditionsItemJsonPathAnyOf
    | unknown[]
    | null;
