/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSummaryItemTypeType500Error } from './getApiInsightsSummaryItemTypeType500Error';

export type GetApiInsightsSummaryItemTypeType500 = {
    statusCode: number;
    error: GetApiInsightsSummaryItemTypeType500Error;
    message: string;
};
