/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBillyExport200 = {
    /** CSV content as string */
    csvContent?: string;
    /** Suggested filename for download */
    filename?: string;
    /** Number of records in the export */
    totalRecords?: number;
};
