/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCardsId200CustomerAnyOf } from './getApiGiftCardsId200CustomerAnyOf';

export type GetApiGiftCardsId200Customer = GetApiGiftCardsId200CustomerAnyOf | null;
