/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiGiftCards200ItemsItemEmployeeAnyOfPhoneNumber } from './getApiGiftCards200ItemsItemEmployeeAnyOfPhoneNumber';

export type GetApiGiftCards200ItemsItemEmployeeAnyOf = {
    id: number;
    name: string;
    phoneNumber: GetApiGiftCards200ItemsItemEmployeeAnyOfPhoneNumber;
};
