/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServiceAdvancedReminderTemplatesSortOrder =
    (typeof GetApiServiceAdvancedReminderTemplatesSortOrder)[keyof typeof GetApiServiceAdvancedReminderTemplatesSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServiceAdvancedReminderTemplatesSortOrder = {
    asc: 'asc',
    desc: 'desc',
} as const;
