/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2Outlet200DataServicesItemServicesItemEmployeesItem } from './getApiMarketplaceV2Outlet200DataServicesItemServicesItemEmployeesItem';

export type GetApiMarketplaceV2Outlet200DataServicesItemServicesItem = {
    id?: number;
    name?: string;
    /** @nullable */
    description?: string | null;
    /** @nullable */
    durationText?: string | null;
    durationMin?: number;
    price?: string;
    /** @nullable */
    image?: string | null;
    /** @nullable */
    isSpecial?: boolean | null;
    /** @nullable */
    specialPrice?: string | null;
    /** @nullable */
    groupId?: number | null;
    sequence?: number;
    isPriceStartsWith?: boolean;
    specialPercentage?: string;
    enableOnlineBooking?: boolean;
    /** @nullable */
    maxAddon?: number | null;
    canBookAlone?: boolean;
    requireCustomerForm?: boolean;
    enablePopupMsg?: boolean;
    /** @nullable */
    popupMsgTitle?: string | null;
    marketplace_hidden?: boolean;
    /** @nullable */
    detailId?: number | null;
    /** @nullable */
    specialOfferStartDate?: string | null;
    /** @nullable */
    specialOfferEndDate?: string | null;
    isCancellationOffer?: boolean;
    /** @nullable */
    cancellationOfferPrice?: string | null;
    /** @nullable */
    cancellationOfferSlotStart?: string | null;
    /** @nullable */
    cancellationOfferSlotEnd?: string | null;
    /** @nullable */
    popupMsgDesc?: string | null;
    /** @nullable */
    popupMsgBtnText?: string | null;
    /** Whether this service is an addon service */
    is_addon?: boolean;
    /** Array of addon service IDs that can be booked with this service */
    addon_ids?: number[];
    employees?: GetApiMarketplaceV2Outlet200DataServicesItemServicesItemEmployeesItem[];
    /** @nullable */
    depositType?: string | null;
    /** @nullable */
    depositValue?: number | null;
};
