/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGiftCardsSource = (typeof GetApiGiftCardsSource)[keyof typeof GetApiGiftCardsSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiGiftCardsSource = {
    ALL: 'ALL',
    MANUAL: 'MANUAL',
    ONLINE: 'ONLINE',
} as const;
