/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiTax200ItemTaxType = (typeof GetApiTax200ItemTaxType)[keyof typeof GetApiTax200ItemTaxType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiTax200ItemTaxType = {
    PERCENTAGE: 'PERCENTAGE',
    AMOUNT: 'AMOUNT',
} as const;
