/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerGroups200GroupsItem } from './getApiCustomerGroups200GroupsItem';

export type GetApiCustomerGroups200 = {
    groups: GetApiCustomerGroups200GroupsItem[];
    total: number;
};
