/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsGrouped200BarChartDataItem = {
    period: string;
    count: number;
    duration?: number;
    revenue?: number;
    startDate: string;
    endDate: string;
};
