/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerGroupsIdMembers500Error =
    (typeof GetApiCustomerGroupsIdMembers500Error)[keyof typeof GetApiCustomerGroupsIdMembers500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerGroupsIdMembers500Error = {
    Bad_Request: 'Bad Request',
} as const;
