/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookingsNoShowReminder500DataItem } from './getApiBookingsNoShowReminder500DataItem';

/**
 * Internal server error
 */
export type GetApiBookingsNoShowReminder500 = {
    success?: boolean;
    data?: GetApiBookingsNoShowReminder500DataItem[];
    message?: string;
};
