/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiExpenses200ExpensesItemCashDrawerId } from './getApiExpenses200ExpensesItemCashDrawerId';
import type { GetApiExpenses200ExpensesItemDescription } from './getApiExpenses200ExpensesItemDescription';
import type { GetApiExpenses200ExpensesItemCreatedAt } from './getApiExpenses200ExpensesItemCreatedAt';
import type { GetApiExpenses200ExpensesItemExpenseCategory } from './getApiExpenses200ExpensesItemExpenseCategory';
import type { GetApiExpenses200ExpensesItemEmployee } from './getApiExpenses200ExpensesItemEmployee';

export type GetApiExpenses200ExpensesItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    cashDrawerId?: GetApiExpenses200ExpensesItemCashDrawerId;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount: number;
    description: GetApiExpenses200ExpensesItemDescription;
    createdAt: GetApiExpenses200ExpensesItemCreatedAt;
    updatedAt: string;
    expenseCategory: GetApiExpenses200ExpensesItemExpenseCategory;
    employee: GetApiExpenses200ExpensesItemEmployee;
};
