/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersCodeBundleOfferCode200BundleOfferApplicableService } from './getApiBundleOffersCodeBundleOfferCode200BundleOfferApplicableService';
import type { GetApiBundleOffersCodeBundleOfferCode200BundleOfferBundleOfferType } from './getApiBundleOffersCodeBundleOfferCode200BundleOfferBundleOfferType';

export type GetApiBundleOffersCodeBundleOfferCode200BundleOffer = {
    id: string;
    seqId: number;
    outletId: number;
    name: string;
    /** @nullable */
    description: string | null;
    price?: number;
    expiryMonths?: number;
    /** Services on which bundle offer can be applied */
    applicableService: GetApiBundleOffersCodeBundleOfferCode200BundleOfferApplicableService;
    bundleOfferType: GetApiBundleOffersCodeBundleOfferCode200BundleOfferBundleOfferType;
    sellOnline: boolean;
    createdAt: string;
    updatedAt: string;
    /** @nullable */
    deletedAt: string | null;
};
