/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiIotDevices200DevicesItemStatus } from './getApiIotDevices200DevicesItemStatus';
import type { GetApiIotDevices200DevicesItemDeletedAt } from './getApiIotDevices200DevicesItemDeletedAt';

export type GetApiIotDevices200DevicesItem = {
    id?: string;
    outletId?: number;
    outletName?: string;
    deviceType?: string;
    deviceMAC?: string;
    apiKey?: string;
    status?: GetApiIotDevices200DevicesItemStatus;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: GetApiIotDevices200DevicesItemDeletedAt;
};
