/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStatisticsExportAppointmentsByTimeGroupBy =
    (typeof GetApiStatisticsExportAppointmentsByTimeGroupBy)[keyof typeof GetApiStatisticsExportAppointmentsByTimeGroupBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiStatisticsExportAppointmentsByTimeGroupBy = {
    time: 'time',
    week: 'week',
} as const;
