/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProductsId500Error = (typeof GetApiProductsId500Error)[keyof typeof GetApiProductsId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiProductsId500Error = {
    Bad_Request: 'Bad Request',
} as const;
