/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsCustomersStatus =
    (typeof GetApiInsightsCustomersStatus)[keyof typeof GetApiInsightsCustomersStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsCustomersStatus = {
    BLOCKED: 'BLOCKED',
    UNBLOCKED: 'UNBLOCKED',
    ALL: 'ALL',
} as const;
