/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsCustomersType } from './getApiInsightsCustomersType';
import type { GetApiInsightsCustomersStatus } from './getApiInsightsCustomersStatus';

export type GetApiInsightsCustomersParams = {
    /**
     * Search by name, email, or phone number
     */
    search?: string;
    /**
     * Response format - json for list view, csv for download
     */
    type?: GetApiInsightsCustomersType;
    /**
     * Filter customers by blocked status - BLOCKED, UNBLOCKED, or ALL
     */
    status?: GetApiInsightsCustomersStatus;
};
