/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTerminalPaymentLogPaymentId404Error } from './getApiTerminalPaymentLogPaymentId404Error';

export type GetApiTerminalPaymentLogPaymentId404 = {
    statusCode: number;
    error: GetApiTerminalPaymentLogPaymentId404Error;
    message: string;
};
