/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsWeeklyTurnoverType200DataSummaryDayTotalsSunday = {
    totalRevenue: number;
    totalCredit: number;
    totalTurnover: number;
};
