/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiPaymentsSubscriptionOutletOutletId500Error =
    (typeof GetApiPaymentsSubscriptionOutletOutletId500Error)[keyof typeof GetApiPaymentsSubscriptionOutletOutletId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiPaymentsSubscriptionOutletOutletId500Error = {
    Bad_Request: 'Bad Request',
} as const;
