/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataWeeksItemFridayDayName } from './getApiInsightsWeeklyTurnoverType200DataWeeksItemFridayDayName';

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemFriday = {
    date: string;
    dayName: GetApiInsightsWeeklyTurnoverType200DataWeeksItemFridayDayName;
    totalRevenue: number;
    totalCredit: number;
    transactionCount: number;
    averageTransactionValue: number;
};
