/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsId500Error } from './getApiProductsId500Error';

export type GetApiProductsId500 = {
    statusCode: number;
    error: GetApiProductsId500Error;
    message: string;
};
