/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsEmployeePaymentsType200DataEmployeesItemSummary = {
    totalPaid: number;
    totalCredited: number;
    grandTotal: number;
};
