/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsTopCustomersParams = {
    /**
     * Start date for revenue calculation (YYYY-MM-DD)
     */
    startDate: string;
    /**
     * End date for revenue calculation (YYYY-MM-DD)
     */
    endDate: string;
};
