/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiExpenseId200CashDrawerId } from './getApiExpenseId200CashDrawerId';
import type { GetApiExpenseId200Description } from './getApiExpenseId200Description';
import type { GetApiExpenseId200CreatedAt } from './getApiExpenseId200CreatedAt';
import type { GetApiExpenseId200ExpenseCategory } from './getApiExpenseId200ExpenseCategory';
import type { GetApiExpenseId200Employee } from './getApiExpenseId200Employee';

export type GetApiExpenseId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    cashDrawerId?: GetApiExpenseId200CashDrawerId;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount: number;
    description: GetApiExpenseId200Description;
    createdAt: GetApiExpenseId200CreatedAt;
    updatedAt: string;
    expenseCategory: GetApiExpenseId200ExpenseCategory;
    employee: GetApiExpenseId200Employee;
};
