/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPaymentsSubscriptionOutletOutletId400Error } from './getApiPaymentsSubscriptionOutletOutletId400Error';

export type GetApiPaymentsSubscriptionOutletOutletId400 = {
    statusCode: number;
    error: GetApiPaymentsSubscriptionOutletOutletId400Error;
    message: string;
};
