/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerIdType400Error } from './getApiCustomerIdType400Error';

export type GetApiCustomerIdType400 = {
    statusCode: number;
    error: GetApiCustomerIdType400Error;
    message: string;
};
