/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsTaxReportsType400Error =
    (typeof GetApiInsightsTaxReportsType400Error)[keyof typeof GetApiInsightsTaxReportsType400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiInsightsTaxReportsType400Error = {
    Bad_Request: 'Bad Request',
} as const;
