/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBundleOffers200ItemsItemBundleOfferType =
    (typeof GetApiBundleOffers200ItemsItemBundleOfferType)[keyof typeof GetApiBundleOffers200ItemsItemBundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBundleOffers200ItemsItemBundleOfferType = {
    PUNCH_BASED: 'PUNCH_BASED',
    SERVICE_BASED: 'SERVICE_BASED',
} as const;
