/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiExpenseCategories200CategoriesItem } from './getApiExpenseCategories200CategoriesItem';

export type GetApiExpenseCategories200 = {
    currentPage: number;
    totalPages: number;
    limit: number;
    total: number;
    categories: GetApiExpenseCategories200CategoriesItem[];
};
