/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsId400Error } from './getApiProductsId400Error';

export type GetApiProductsId400 = {
    statusCode: number;
    error: GetApiProductsId400Error;
    message: string;
};
