/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetApiHealthDeclarations200DataItemsItemResponseContent = { [key: string]: unknown } | null;
