/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerGroupsId200MembersItemEmail } from './getApiCustomerGroupsId200MembersItemEmail';
import type { GetApiCustomerGroupsId200MembersItemCountryCode } from './getApiCustomerGroupsId200MembersItemCountryCode';
import type { GetApiCustomerGroupsId200MembersItemCountryISOCode } from './getApiCustomerGroupsId200MembersItemCountryISOCode';

export type GetApiCustomerGroupsId200MembersItem = {
    id: number;
    name: string;
    email?: GetApiCustomerGroupsId200MembersItemEmail;
    phoneNumber: string;
    countryCode?: GetApiCustomerGroupsId200MembersItemCountryCode;
    countryISOCode?: GetApiCustomerGroupsId200MembersItemCountryISOCode;
    membershipId: string;
    joinedAt: string;
};
