/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOffersCodeBundleOfferCode200BundleOffer } from './getApiBundleOffersCodeBundleOfferCode200BundleOffer';
import type { GetApiBundleOffersCodeBundleOfferCode200SoldBundleOffer } from './getApiBundleOffersCodeBundleOfferCode200SoldBundleOffer';
import type { GetApiBundleOffersCodeBundleOfferCode200Customer } from './getApiBundleOffersCodeBundleOfferCode200Customer';
import type { GetApiBundleOffersCodeBundleOfferCode200Employee } from './getApiBundleOffersCodeBundleOfferCode200Employee';

export type GetApiBundleOffersCodeBundleOfferCode200 = {
    bundleOffer: GetApiBundleOffersCodeBundleOfferCode200BundleOffer;
    soldBundleOffer: GetApiBundleOffersCodeBundleOfferCode200SoldBundleOffer;
    /** @nullable */
    customer?: GetApiBundleOffersCodeBundleOfferCode200Customer;
    /** @nullable */
    employee?: GetApiBundleOffersCodeBundleOfferCode200Employee;
};
