/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiKlaviyoConfig200Data } from './getApiKlaviyoConfig200Data';

export type GetApiKlaviyoConfig200 = {
    success: boolean;
    data: GetApiKlaviyoConfig200Data;
    message?: string;
};
