/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarationTemplates500Error } from './getApiHealthDeclarationTemplates500Error';

export type GetApiHealthDeclarationTemplates500 = {
    statusCode: number;
    error: GetApiHealthDeclarationTemplates500Error;
    message: string;
};
