/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesList200SalesItemCustomerAnyOfEmail } from './getApiSalesList200SalesItemCustomerAnyOfEmail';
import type { GetApiSalesList200SalesItemCustomerAnyOfDeletedAt } from './getApiSalesList200SalesItemCustomerAnyOfDeletedAt';
import type { GetApiSalesList200SalesItemCustomerAnyOfCpr } from './getApiSalesList200SalesItemCustomerAnyOfCpr';
import type { GetApiSalesList200SalesItemCustomerAnyOfBirthday } from './getApiSalesList200SalesItemCustomerAnyOfBirthday';
import type { GetApiSalesList200SalesItemCustomerAnyOfAddress } from './getApiSalesList200SalesItemCustomerAnyOfAddress';
import type { GetApiSalesList200SalesItemCustomerAnyOfCountryCode } from './getApiSalesList200SalesItemCustomerAnyOfCountryCode';
import type { GetApiSalesList200SalesItemCustomerAnyOfCountryISOCode } from './getApiSalesList200SalesItemCustomerAnyOfCountryISOCode';
import type { GetApiSalesList200SalesItemCustomerAnyOfCountryCode2 } from './getApiSalesList200SalesItemCustomerAnyOfCountryCode2';
import type { GetApiSalesList200SalesItemCustomerAnyOfCountryISOCode2 } from './getApiSalesList200SalesItemCustomerAnyOfCountryISOCode2';
import type { GetApiSalesList200SalesItemCustomerAnyOfPhoneNumber2 } from './getApiSalesList200SalesItemCustomerAnyOfPhoneNumber2';
import type { GetApiSalesList200SalesItemCustomerAnyOfMarketplacePointer } from './getApiSalesList200SalesItemCustomerAnyOfMarketplacePointer';
import type { GetApiSalesList200SalesItemCustomerAnyOfZipCode } from './getApiSalesList200SalesItemCustomerAnyOfZipCode';
import type { GetApiSalesList200SalesItemCustomerAnyOfCity } from './getApiSalesList200SalesItemCustomerAnyOfCity';
import type { GetApiSalesList200SalesItemCustomerAnyOfAttachments } from './getApiSalesList200SalesItemCustomerAnyOfAttachments';
import type { GetApiSalesList200SalesItemCustomerAnyOfUserId } from './getApiSalesList200SalesItemCustomerAnyOfUserId';
import type { GetApiSalesList200SalesItemCustomerAnyOfNote } from './getApiSalesList200SalesItemCustomerAnyOfNote';

export type GetApiSalesList200SalesItemCustomerAnyOf = {
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    id: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    name: string;
    phoneNumber: string;
    email: GetApiSalesList200SalesItemCustomerAnyOfEmail;
    createdAt: string;
    updatedAt: string;
    deletedAt: GetApiSalesList200SalesItemCustomerAnyOfDeletedAt;
    cpr: GetApiSalesList200SalesItemCustomerAnyOfCpr;
    birthday: GetApiSalesList200SalesItemCustomerAnyOfBirthday;
    address: GetApiSalesList200SalesItemCustomerAnyOfAddress;
    countryCode: GetApiSalesList200SalesItemCustomerAnyOfCountryCode;
    countryISOCode: GetApiSalesList200SalesItemCustomerAnyOfCountryISOCode;
    countryCode2: GetApiSalesList200SalesItemCustomerAnyOfCountryCode2;
    countryISOCode2: GetApiSalesList200SalesItemCustomerAnyOfCountryISOCode2;
    phoneNumber2: GetApiSalesList200SalesItemCustomerAnyOfPhoneNumber2;
    marketplacePointer: GetApiSalesList200SalesItemCustomerAnyOfMarketplacePointer;
    zipCode: GetApiSalesList200SalesItemCustomerAnyOfZipCode;
    city: GetApiSalesList200SalesItemCustomerAnyOfCity;
    attachments: GetApiSalesList200SalesItemCustomerAnyOfAttachments;
    marketingPermission: boolean;
    userId: GetApiSalesList200SalesItemCustomerAnyOfUserId;
    blockBooking: boolean;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    bonus: number;
    note: GetApiSalesList200SalesItemCustomerAnyOfNote;
};
