/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiDoctorsPortalDoctorsSortBy } from './getApiDoctorsPortalDoctorsSortBy';
import type { GetApiDoctorsPortalDoctorsSortOrder } from './getApiDoctorsPortalDoctorsSortOrder';
import type { GetApiDoctorsPortalDoctorsConnectionStatus } from './getApiDoctorsPortalDoctorsConnectionStatus';

export type GetApiDoctorsPortalDoctorsParams = {
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    sortBy?: GetApiDoctorsPortalDoctorsSortBy;
    sortOrder?: GetApiDoctorsPortalDoctorsSortOrder;
    keyword?: string;
    active?: boolean | 'true' | 'false';
    connectionStatus?: GetApiDoctorsPortalDoctorsConnectionStatus;
};
