/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItem } from './getApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItem';
import type { GetApiInsightsSalesDetailsItemTypeIdType200DataPagination } from './getApiInsightsSalesDetailsItemTypeIdType200DataPagination';

export type GetApiInsightsSalesDetailsItemTypeIdType200Data = {
    salesDetails: GetApiInsightsSalesDetailsItemTypeIdType200DataSalesDetailsItem[];
    pagination: GetApiInsightsSalesDetailsItemTypeIdType200DataPagination;
};
