/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2SearchSuggestions200Data } from './getApiMarketplaceV2SearchSuggestions200Data';

export type GetApiMarketplaceV2SearchSuggestions200 = {
    message?: string;
    data?: GetApiMarketplaceV2SearchSuggestions200Data;
};
