/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsWeeklyTurnoverType200DataWeeksItemWednesdayDayName } from './getApiInsightsWeeklyTurnoverType200DataWeeksItemWednesdayDayName';

export type GetApiInsightsWeeklyTurnoverType200DataWeeksItemWednesday = {
    date: string;
    dayName: GetApiInsightsWeeklyTurnoverType200DataWeeksItemWednesdayDayName;
    totalRevenue: number;
    totalCredit: number;
    transactionCount: number;
    averageTransactionValue: number;
};
