/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiListDiscounts200ItemAmountType =
    (typeof GetApiListDiscounts200ItemAmountType)[keyof typeof GetApiListDiscounts200ItemAmountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiListDiscounts200ItemAmountType = {
    AMOUNT: 'AMOUNT',
    PERCENTAGE: 'PERCENTAGE',
    VARIABLE_AMOUNT: 'VARIABLE_AMOUNT',
    VARIABLE_PERCENTAGE: 'VARIABLE_PERCENTAGE',
} as const;
