/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiExpenseCategoriesSortBy } from './getApiExpenseCategoriesSortBy';
import type { GetApiExpenseCategoriesSortOrder } from './getApiExpenseCategoriesSortOrder';

export type GetApiExpenseCategoriesParams = {
    /**
     * @minimum 1
     */
    page?: number;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    sortBy?: GetApiExpenseCategoriesSortBy;
    sortOrder?: GetApiExpenseCategoriesSortOrder;
    keyword?: string;
};
