/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiInsightsTaxReportsType200DataItemsItem } from './getApiInsightsTaxReportsType200DataItemsItem';
import type { GetApiInsightsTaxReportsType200DataSummary } from './getApiInsightsTaxReportsType200DataSummary';
import type { GetApiInsightsTaxReportsType200DataPagination } from './getApiInsightsTaxReportsType200DataPagination';

export type GetApiInsightsTaxReportsType200Data = {
    items: GetApiInsightsTaxReportsType200DataItemsItem[];
    summary: GetApiInsightsTaxReportsType200DataSummary;
    pagination: GetApiInsightsTaxReportsType200DataPagination;
};
