/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTriggerTemplates200CampaignsItemDescription } from './getApiTriggerTemplates200CampaignsItemDescription';

export type GetApiTriggerTemplates200CampaignsItem = {
    id: string;
    name: string;
    description?: GetApiTriggerTemplates200CampaignsItemDescription;
    customerGroup: string;
    createdAt: string;
    openRate: string;
    recipients: number;
    revenue: string;
    campaignStatus: string;
};
