/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetApiMarketplaceV2SearchResultBoundAnyOfSouthWest } from './_getApiMarketplaceV2SearchResultBoundAnyOfSouthWest';
import type { _GetApiMarketplaceV2SearchResultBoundAnyOfNorthEast } from './_getApiMarketplaceV2SearchResultBoundAnyOfNorthEast';

export type GetApiMarketplaceV2SearchResultBoundAnyOf = {
    _southWest: _GetApiMarketplaceV2SearchResultBoundAnyOfSouthWest;
    _northEast: _GetApiMarketplaceV2SearchResultBoundAnyOfNorthEast;
};
