/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiServiceAdvancedReminderTemplatesReminderTemplateId500Error } from './getApiServiceAdvancedReminderTemplatesReminderTemplateId500Error';

export type GetApiServiceAdvancedReminderTemplatesReminderTemplateId500 = {
    statusCode: number;
    error: GetApiServiceAdvancedReminderTemplatesReminderTemplateId500Error;
    message: string;
};
