/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInsightsEmployeePaymentsType200DataPagination = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};
