/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSaleId400Error = (typeof GetApiSaleId400Error)[keyof typeof GetApiSaleId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiSaleId400Error = {
    Bad_Request: 'Bad Request',
} as const;
