/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarationTemplateId200Data } from './getApiHealthDeclarationTemplateId200Data';

export type GetApiHealthDeclarationTemplateId200 = {
    statusCode: number;
    message: string;
    success: boolean;
    data: GetApiHealthDeclarationTemplateId200Data;
};
