/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesListPrintType500Error } from './getApiSalesListPrintType500Error';

export type GetApiSalesListPrintType500 = {
    statusCode: number;
    error: GetApiSalesListPrintType500Error;
    message: string;
};
