/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomers500Error } from './getApiCustomers500Error';

export type GetApiCustomers500 = {
    statusCode: number;
    error: GetApiCustomers500Error;
    message: string;
};
