/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemProductId } from './getApiPreviousSalesItemsCustomerId200ItemsItemProductId';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemServiceId } from './getApiPreviousSalesItemsCustomerId200ItemsItemServiceId';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemItemImageUrl } from './getApiPreviousSalesItemsCustomerId200ItemsItemItemImageUrl';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemUnitId } from './getApiPreviousSalesItemsCustomerId200ItemsItemUnitId';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemUnitName } from './getApiPreviousSalesItemsCustomerId200ItemsItemUnitName';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemUnitAbbreviation } from './getApiPreviousSalesItemsCustomerId200ItemsItemUnitAbbreviation';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemCategoryId } from './getApiPreviousSalesItemsCustomerId200ItemsItemCategoryId';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemDeletedAt } from './getApiPreviousSalesItemsCustomerId200ItemsItemDeletedAt';
import type { GetApiPreviousSalesItemsCustomerId200ItemsItemEmployee } from './getApiPreviousSalesItemsCustomerId200ItemsItemEmployee';

export type GetApiPreviousSalesItemsCustomerId200ItemsItem = {
    id: string;
    seqId: number;
    salesId: string;
    outletId: number;
    productId: GetApiPreviousSalesItemsCustomerId200ItemsItemProductId;
    serviceId: GetApiPreviousSalesItemsCustomerId200ItemsItemServiceId;
    itemName: string;
    quantity: number;
    amount: number;
    price: number;
    note: string;
    description: string;
    itemImageUrl: GetApiPreviousSalesItemsCustomerId200ItemsItemItemImageUrl;
    unitId: GetApiPreviousSalesItemsCustomerId200ItemsItemUnitId;
    unitName: GetApiPreviousSalesItemsCustomerId200ItemsItemUnitName;
    unitAbbreviation: GetApiPreviousSalesItemsCustomerId200ItemsItemUnitAbbreviation;
    categoryId: GetApiPreviousSalesItemsCustomerId200ItemsItemCategoryId;
    categoryName: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: GetApiPreviousSalesItemsCustomerId200ItemsItemDeletedAt;
    salesDate: string;
    sellBy: number;
    discountAmount: number;
    employee: GetApiPreviousSalesItemsCustomerId200ItemsItemEmployee;
};
