/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2SearchSuggestions500Error } from './getApiMarketplaceV2SearchSuggestions500Error';

export type GetApiMarketplaceV2SearchSuggestions500 = {
    statusCode: number;
    error: GetApiMarketplaceV2SearchSuggestions500Error;
    message: string;
};
