/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCustomerId404Error = (typeof GetApiCustomerId404Error)[keyof typeof GetApiCustomerId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCustomerId404Error = {
    Bad_Request: 'Bad Request',
} as const;
