/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2Outlet200DataServicesItemServicesItem } from './getApiMarketplaceV2Outlet200DataServicesItemServicesItem';

export type GetApiMarketplaceV2Outlet200DataServicesItem = {
    /** @nullable */
    id?: number | null;
    sequence?: number;
    /** Group name, can be "Special Offers" for non-campaign special services */
    groupName?: string;
    /** Whether the group is hidden from marketplace */
    marketplace_hidden?: boolean;
    /** True for campaign groups, false for regular groups and special offers */
    is_campaign?: boolean;
    services?: GetApiMarketplaceV2Outlet200DataServicesItemServicesItem[];
};
