/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDoctorsPortalDoctorsSortBy =
    (typeof GetApiDoctorsPortalDoctorsSortBy)[keyof typeof GetApiDoctorsPortalDoctorsSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiDoctorsPortalDoctorsSortBy = {
    createdAt: 'createdAt',
    firstName: 'firstName',
    lastName: 'lastName',
    email: 'email',
} as const;
