/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCalendlyCallback200Data } from './getApiCalendlyCallback200Data';

export type GetApiCalendlyCallback200 = {
    success?: boolean;
    data?: GetApiCalendlyCallback200Data;
    message?: string;
};
