/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesList500Error } from './getApiSalesList500Error';

export type GetApiSalesList500 = {
    statusCode: number;
    error: GetApiSalesList500Error;
    message: string;
};
