/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMarketplaceV2Outlet200DataBranchesItem = {
    id?: number;
    name?: string;
    /** @nullable */
    profile_image?: string | null;
    address?: string;
    /** @nullable */
    contact_country_code?: string | null;
    /** @nullable */
    contact_number?: string | null;
    /** @nullable */
    webStoreName?: string | null;
    /** @nullable */
    avg_rating?: number | null;
    /** @nullable */
    total_reviews?: number | null;
    geo_location?: string;
};
