/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiCampaignsId200ScheduleTriggerDaysAnyOfItem =
    (typeof GetApiCampaignsId200ScheduleTriggerDaysAnyOfItem)[keyof typeof GetApiCampaignsId200ScheduleTriggerDaysAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiCampaignsId200ScheduleTriggerDaysAnyOfItem = {
    sunday: 'sunday',
    monday: 'monday',
    tuesday: 'tuesday',
    wednesday: 'wednesday',
    thursday: 'thursday',
    friday: 'friday',
    saturday: 'saturday',
} as const;
