/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Deposit type
 * @nullable
 */
export type GetApiServicesDeposit200DataGroupedServicesItemServicesItemDepositType =
    | (typeof GetApiServicesDeposit200DataGroupedServicesItemServicesItemDepositType)[keyof typeof GetApiServicesDeposit200DataGroupedServicesItemServicesItemDepositType]
    | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServicesDeposit200DataGroupedServicesItemServicesItemDepositType = {
    PERCENTAGE: 'PERCENTAGE',
    AMOUNT: 'AMOUNT',
} as const;
