/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHealthDeclarationPrintIdType404Error } from './getApiHealthDeclarationPrintIdType404Error';

export type GetApiHealthDeclarationPrintIdType404 = {
    statusCode: number;
    error: GetApiHealthDeclarationPrintIdType404Error;
    message: string;
};
