/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiServicesExport500Error =
    (typeof GetApiServicesExport500Error)[keyof typeof GetApiServicesExport500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiServicesExport500Error = {
    Bad_Request: 'Bad Request',
} as const;
