/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMarketplaceV2SearchResult200DataItem } from './getApiMarketplaceV2SearchResult200DataItem';

export type GetApiMarketplaceV2SearchResult200 = {
    message: string;
    totalPages: number;
    totalItems: number;
    currentPage: number;
    limit: number;
    data: GetApiMarketplaceV2SearchResult200DataItem[];
};
