/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBundleOfferServiceList500Error } from './getApiBundleOfferServiceList500Error';

export type GetApiBundleOfferServiceList500 = {
    statusCode: number;
    error: GetApiBundleOfferServiceList500Error;
    message: string;
};
