/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSalesDetailsId200SalesSyncAnyOfOrgId } from './getApiSalesDetailsId200SalesSyncAnyOfOrgId';

export type GetApiSalesDetailsId200SalesSyncAnyOf = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    salesId: string;
    /** @maxLength 255 */
    syncSalesId: string;
    orgId: GetApiSalesDetailsId200SalesSyncAnyOfOrgId;
    email_sent: boolean;
    syncedAt: string;
    /** @maxLength 255 */
    type: string;
};
