/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsId200ScheduleSendDateTime } from './getApiCampaignsId200ScheduleSendDateTime';
import type { GetApiCampaignsId200ScheduleTriggerDays } from './getApiCampaignsId200ScheduleTriggerDays';
import type { GetApiCampaignsId200ScheduleTriggerTime } from './getApiCampaignsId200ScheduleTriggerTime';
import type { GetApiCampaignsId200ScheduleWaitingPeriod } from './getApiCampaignsId200ScheduleWaitingPeriod';
import type { GetApiCampaignsId200ScheduleSpamPeriod } from './getApiCampaignsId200ScheduleSpamPeriod';

export type GetApiCampaignsId200Schedule = {
    id?: string;
    sendDateTime?: GetApiCampaignsId200ScheduleSendDateTime;
    isManualTrigger?: boolean;
    triggerDays?: GetApiCampaignsId200ScheduleTriggerDays;
    triggerTime?: GetApiCampaignsId200ScheduleTriggerTime;
    waitingPeriod?: GetApiCampaignsId200ScheduleWaitingPeriod;
    spamPeriod?: GetApiCampaignsId200ScheduleSpamPeriod;
};
