/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAddons200DataItem } from './getApiAddons200DataItem';
import type { GetApiAddons200SelectedAddon } from './getApiAddons200SelectedAddon';

export type GetApiAddons200 = {
    success: boolean;
    message: string;
    data?: GetApiAddons200DataItem[];
    selectedAddon?: GetApiAddons200SelectedAddon;
    error?: string;
};
