/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiWebhooks200WebhooksItemSecret } from './getApiWebhooks200WebhooksItemSecret';

export type GetApiWebhooks200WebhooksItem = {
    id: number;
    outletId: number;
    event: string;
    webhookUrl: string;
    secret?: GetApiWebhooks200WebhooksItemSecret;
    active: boolean;
};
