/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomerId500Error } from './getApiCustomerId500Error';

export type GetApiCustomerId500 = {
    statusCode: number;
    error: GetApiCustomerId500Error;
    message: string;
};
