/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsListing200ServicesItemServicesItemServiceTypeId } from './getApiProductsListing200ServicesItemServicesItemServiceTypeId';
import type { GetApiProductsListing200ServicesItemServicesItemDescription } from './getApiProductsListing200ServicesItemServicesItemDescription';
import type { GetApiProductsListing200ServicesItemServicesItemDurationText } from './getApiProductsListing200ServicesItemServicesItemDurationText';
import type { GetApiProductsListing200ServicesItemServicesItemImage } from './getApiProductsListing200ServicesItemServicesItemImage';
import type { GetApiProductsListing200ServicesItemServicesItemServes } from './getApiProductsListing200ServicesItemServicesItemServes';
import type { GetApiProductsListing200ServicesItemServicesItemIsSpecial } from './getApiProductsListing200ServicesItemServicesItemIsSpecial';
import type { GetApiProductsListing200ServicesItemServicesItemSpecialPrice } from './getApiProductsListing200ServicesItemServicesItemSpecialPrice';
import type { GetApiProductsListing200ServicesItemServicesItemSpecialSourceId } from './getApiProductsListing200ServicesItemServicesItemSpecialSourceId';
import type { GetApiProductsListing200ServicesItemServicesItemGroupId } from './getApiProductsListing200ServicesItemServicesItemGroupId';
import type { GetApiProductsListing200ServicesItemServicesItemIsCertified } from './getApiProductsListing200ServicesItemServicesItemIsCertified';
import type { GetApiProductsListing200ServicesItemServicesItemCancellationOfferBookingSourceId } from './getApiProductsListing200ServicesItemServicesItemCancellationOfferBookingSourceId';
import type { GetApiProductsListing200ServicesItemServicesItemCancellationOfferSlotStart } from './getApiProductsListing200ServicesItemServicesItemCancellationOfferSlotStart';
import type { GetApiProductsListing200ServicesItemServicesItemCancellationOfferSlotEnd } from './getApiProductsListing200ServicesItemServicesItemCancellationOfferSlotEnd';
import type { GetApiProductsListing200ServicesItemServicesItemServiceTypeIdsItem } from './getApiProductsListing200ServicesItemServicesItemServiceTypeIdsItem';
import type { GetApiProductsListing200ServicesItemServicesItemSequence } from './getApiProductsListing200ServicesItemServicesItemSequence';
import type { GetApiProductsListing200ServicesItemServicesItemMaxAddon } from './getApiProductsListing200ServicesItemServicesItemMaxAddon';
import type { GetApiProductsListing200ServicesItemServicesItemPopupMsgTitle } from './getApiProductsListing200ServicesItemServicesItemPopupMsgTitle';
import type { GetApiProductsListing200ServicesItemServicesItemPopupMsgDesc } from './getApiProductsListing200ServicesItemServicesItemPopupMsgDesc';
import type { GetApiProductsListing200ServicesItemServicesItemPopupMsgBtnText } from './getApiProductsListing200ServicesItemServicesItemPopupMsgBtnText';
import type { GetApiProductsListing200ServicesItemServicesItemOnlineBookingColor } from './getApiProductsListing200ServicesItemServicesItemOnlineBookingColor';
import type { GetApiProductsListing200ServicesItemServicesItemManualBookingColor } from './getApiProductsListing200ServicesItemServicesItemManualBookingColor';
import type { GetApiProductsListing200ServicesItemServicesItemDepositType } from './getApiProductsListing200ServicesItemServicesItemDepositType';
import type { GetApiProductsListing200ServicesItemServicesItemAdditionalData } from './getApiProductsListing200ServicesItemServicesItemAdditionalData';
import type { GetApiProductsListing200ServicesItemServicesItemSyncId } from './getApiProductsListing200ServicesItemServicesItemSyncId';
import type { GetApiProductsListing200ServicesItemServicesItemHealthDeclaration } from './getApiProductsListing200ServicesItemServicesItemHealthDeclaration';

export type GetApiProductsListing200ServicesItemServicesItem = {
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    id: number;
    name: string;
    serviceTypeId: GetApiProductsListing200ServicesItemServicesItemServiceTypeId;
    description: GetApiProductsListing200ServicesItemServicesItemDescription;
    durationText: GetApiProductsListing200ServicesItemServicesItemDurationText;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    durationMin: number;
    price: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    createdAt: string;
    updatedAt: string;
    image: GetApiProductsListing200ServicesItemServicesItemImage;
    serves: GetApiProductsListing200ServicesItemServicesItemServes;
    isSpecial: GetApiProductsListing200ServicesItemServicesItemIsSpecial;
    specialPrice: GetApiProductsListing200ServicesItemServicesItemSpecialPrice;
    isEquipmentService: boolean;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    noOfEquipments: number;
    specialSourceId: GetApiProductsListing200ServicesItemServicesItemSpecialSourceId;
    groupId: GetApiProductsListing200ServicesItemServicesItemGroupId;
    isCertified: GetApiProductsListing200ServicesItemServicesItemIsCertified;
    isCancellationOffer: boolean;
    cancellationOfferPrice: string;
    cancellationOfferBookingSourceId: GetApiProductsListing200ServicesItemServicesItemCancellationOfferBookingSourceId;
    cancellationOfferSlotStart: GetApiProductsListing200ServicesItemServicesItemCancellationOfferSlotStart;
    cancellationOfferSlotEnd: GetApiProductsListing200ServicesItemServicesItemCancellationOfferSlotEnd;
    isPriceStartsWith: boolean;
    specialPercentage: string;
    serviceTypeIds: GetApiProductsListing200ServicesItemServicesItemServiceTypeIdsItem[];
    isConsultation: boolean;
    isBundleOffer: boolean;
    cancellationOfferBooked: boolean;
    sequence: GetApiProductsListing200ServicesItemServicesItemSequence;
    isNewService: boolean;
    isOfferToNewClients: boolean;
    isOfferToRegularClients: boolean;
    isFollowUpTreatment: boolean;
    isAddon: boolean;
    maxAddon: GetApiProductsListing200ServicesItemServicesItemMaxAddon;
    canBookAlone: boolean;
    enableOnlineBooking: boolean;
    enablePopupMsg: boolean;
    popupMsgTitle: GetApiProductsListing200ServicesItemServicesItemPopupMsgTitle;
    popupMsgDesc: GetApiProductsListing200ServicesItemServicesItemPopupMsgDesc;
    popupMsgBtnText: GetApiProductsListing200ServicesItemServicesItemPopupMsgBtnText;
    onlineBookingColor: GetApiProductsListing200ServicesItemServicesItemOnlineBookingColor;
    manualBookingColor: GetApiProductsListing200ServicesItemServicesItemManualBookingColor;
    requireCustomerForm: boolean;
    marketplaceHidden: boolean;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    onlineBookingGap: number;
    isGhostImport: boolean;
    depositType: GetApiProductsListing200ServicesItemServicesItemDepositType;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    depositValue: number;
    additionalData?: GetApiProductsListing200ServicesItemServicesItemAdditionalData;
    syncId: GetApiProductsListing200ServicesItemServicesItemSyncId;
    syncService: boolean;
    healthDeclaration?: GetApiProductsListing200ServicesItemServicesItemHealthDeclaration;
};
