/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomers200CustomersItem } from './getApiCustomers200CustomersItem';

export type GetApiCustomers200 = {
    customers?: GetApiCustomers200CustomersItem[];
    total?: number;
    page?: number;
    limit?: number;
    totalPages?: number;
};
