/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCustomersCustomerIdGroups500Error } from './getApiCustomersCustomerIdGroups500Error';

export type GetApiCustomersCustomerIdGroups500 = {
    statusCode: number;
    error: GetApiCustomersCustomerIdGroups500Error;
    message: string;
};
