/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStatisticsSales200ListDataItem } from './getApiStatisticsSales200ListDataItem';
import type { GetApiStatisticsSales200Grouping } from './getApiStatisticsSales200Grouping';

/**
 * Successfully retrieved sales statistics
 */
export type GetApiStatisticsSales200 = {
    listData: GetApiStatisticsSales200ListDataItem[];
    totalSalesCount: number;
    totalAmount: number;
    grouping: GetApiStatisticsSales200Grouping;
};
