/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGiftCardsStatus = (typeof GetApiGiftCardsStatus)[keyof typeof GetApiGiftCardsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiGiftCardsStatus = {
    ALL: 'ALL',
    USED: 'USED',
    UNUSED: 'UNUSED',
    PURCHASED_ONLINE: 'PURCHASED_ONLINE',
} as const;
