/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCampaignsId200ConditionsItemValueAnyOf } from './getApiCampaignsId200ConditionsItemValueAnyOf';

/**
 * Value field that can be an array or any object with key-value pairs
 */
export type GetApiCampaignsId200ConditionsItemValue =
    | string
    | number
    | boolean
    | unknown[]
    | GetApiCampaignsId200ConditionsItemValueAnyOf
    | null;
