/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSalesDetailsId200ItemsItemItemType =
    | 'SERVICE'
    | 'PRODUCT'
    | 'GIFT_CARD'
    | 'OUTSTANDING'
    | 'CUT_CARD'
    | 'BONUS'
    | null;
