/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error =
    (typeof PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error)[keyof typeof PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error = {
    Bad_Request: 'Bad Request',
} as const;
