/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiGoogleCalendarSettings400Error =
    (typeof PatchApiGoogleCalendarSettings400Error)[keyof typeof PatchApiGoogleCalendarSettings400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiGoogleCalendarSettings400Error = {
    Bad_Request: 'Bad Request',
} as const;
