/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiServiceGroupsIdDrivingFees400Error =
    (typeof PatchApiServiceGroupsIdDrivingFees400Error)[keyof typeof PatchApiServiceGroupsIdDrivingFees400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiServiceGroupsIdDrivingFees400Error = {
    Bad_Request: 'Bad Request',
} as const;
