/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiServiceAdvancedReminderTemplatesReminderTemplateId404Error =
    (typeof PatchApiServiceAdvancedReminderTemplatesReminderTemplateId404Error)[keyof typeof PatchApiServiceAdvancedReminderTemplatesReminderTemplateId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiServiceAdvancedReminderTemplatesReminderTemplateId404Error = {
    Bad_Request: 'Bad Request',
} as const;
