/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiBookingsNoShowId200Data } from './patchApiBookingsNoShowId200Data';

export type PatchApiBookingsNoShowId200 = {
    success?: boolean;
    data?: PatchApiBookingsNoShowId200Data;
    message?: string;
};
