/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiEmployeeOpeningHoursEmployeeId500Error } from './patchApiEmployeeOpeningHoursEmployeeId500Error';

export type PatchApiEmployeeOpeningHoursEmployeeId500 = {
    statusCode: number;
    error: PatchApiEmployeeOpeningHoursEmployeeId500Error;
    message: string;
};
