/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiBookingsNoShowId400Data } from './patchApiBookingsNoShowId400Data';

export type PatchApiBookingsNoShowId400 = {
    success?: boolean;
    data?: PatchApiBookingsNoShowId400Data;
    message?: string;
};
