/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceGroupsIdDrivingFeesBodyDistanceChargesItem } from './patchApiServiceGroupsIdDrivingFeesBodyDistanceChargesItem';

export type PatchApiServiceGroupsIdDrivingFeesBody = {
    distance_charges: PatchApiServiceGroupsIdDrivingFeesBodyDistanceChargesItem[];
};
