/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiGoogleCalendarSettings401Error =
    (typeof PatchApiGoogleCalendarSettings401Error)[keyof typeof PatchApiGoogleCalendarSettings401Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiGoogleCalendarSettings401Error = {
    Bad_Request: 'Bad Request',
} as const;
