/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType =
    (typeof PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType)[keyof typeof PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType = {
    SMS: 'SMS',
    EMAIL: 'EMAIL',
    EMAIL_AND_SMS: 'EMAIL_AND_SMS',
} as const;
