/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiEmployeeOpeningHoursEmployeeId200ItemEndDate } from './patchApiEmployeeOpeningHoursEmployeeId200ItemEndDate';
import type { PatchApiEmployeeOpeningHoursEmployeeId200ItemRepeat } from './patchApiEmployeeOpeningHoursEmployeeId200ItemRepeat';
import type { PatchApiEmployeeOpeningHoursEmployeeId200ItemStartBreakTime } from './patchApiEmployeeOpeningHoursEmployeeId200ItemStartBreakTime';
import type { PatchApiEmployeeOpeningHoursEmployeeId200ItemEndBreakTime } from './patchApiEmployeeOpeningHoursEmployeeId200ItemEndBreakTime';
import type { PatchApiEmployeeOpeningHoursEmployeeId200ItemAdditionalDays } from './patchApiEmployeeOpeningHoursEmployeeId200ItemAdditionalDays';

export type PatchApiEmployeeOpeningHoursEmployeeId200Item = {
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    id: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    employeeId: number;
    startDate: string;
    startTime: string;
    endTime: string;
    endDate: PatchApiEmployeeOpeningHoursEmployeeId200ItemEndDate;
    repeat: PatchApiEmployeeOpeningHoursEmployeeId200ItemRepeat;
    addBreak: boolean;
    startBreakTime: PatchApiEmployeeOpeningHoursEmployeeId200ItemStartBreakTime;
    endBreakTime: PatchApiEmployeeOpeningHoursEmployeeId200ItemEndBreakTime;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    startDay: string;
    createdAt: string;
    updatedAt: string;
    offDays: string[];
    additionalDays: PatchApiEmployeeOpeningHoursEmployeeId200ItemAdditionalDays;
};
