/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiDoctorsPortalMessagesMessageIdRead500Error } from './patchApiDoctorsPortalMessagesMessageIdRead500Error';

export type PatchApiDoctorsPortalMessagesMessageIdRead500 = {
    statusCode: number;
    error: PatchApiDoctorsPortalMessagesMessageIdRead500Error;
    message: string;
};
