/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiEmployeeOpeningHoursEmployeeId404Error } from './patchApiEmployeeOpeningHoursEmployeeId404Error';

export type PatchApiEmployeeOpeningHoursEmployeeId404 = {
    statusCode: number;
    error: PatchApiEmployeeOpeningHoursEmployeeId404Error;
    message: string;
};
