/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceGroupsIdDrivingFees200DistanceChargesItem } from './patchApiServiceGroupsIdDrivingFees200DistanceChargesItem';

export type PatchApiServiceGroupsIdDrivingFees200 = {
    distance_charges?: PatchApiServiceGroupsIdDrivingFees200DistanceChargesItem[];
};
