/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiGiftCardsId200CustomerAnyOfEmail } from './patchApiGiftCardsId200CustomerAnyOfEmail';

export type PatchApiGiftCardsId200CustomerAnyOf = {
    id: number;
    name: string;
    email: PatchApiGiftCardsId200CustomerAnyOfEmail;
    phoneNumber: string;
};
