/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiDoctorsPortalMessagesMessageIdRead404Error } from './patchApiDoctorsPortalMessagesMessageIdRead404Error';

export type PatchApiDoctorsPortalMessagesMessageIdRead404 = {
    statusCode: number;
    error: PatchApiDoctorsPortalMessagesMessageIdRead404Error;
    message: string;
};
