/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiBookingStatusUpdateParams = {
    /**
     * JWT token containing outlet ID (sub), employee ID (emp_id), role, and group booking UUID (group_booking_uuid)
     */
    token: string;
};
