/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiGoogleCalendarSettingsBody = {
    /** Whether to sync opening hours (schedules and holidays) to Google Calendar */
    syncOpeningHours: boolean;
    /** When turning off (syncOpeningHours: false), if true deletes synced opening-hours events from Google Calendar and sets deletedAt on sync records; if false or omitted, only updates the flag */
    deleteSyncedOpeningHours?: boolean;
};
