/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiBookingsNoShowIdBody = {
    /** Amount to be charged for the no-show booking */
    noShowAmount?: number;
    /** Description for the no-show booking */
    noShowNote?: string;
    /** Send SMS notification for the no-show booking */
    sendSms?: boolean;
    /** Send email notification for the no-show booking */
    sendEmail?: boolean;
};
