/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType';
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailSubject } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailSubject';
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailContent } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailContent';
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200SmsContent } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId200SmsContent';
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ServicesItem } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId200ServicesItem';

export type PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200 = {
    reminderTemplateId: string;
    reminderTemplateName: string;
    reminderTemplateType: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ReminderTemplateType;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    reminderMinutes: number;
    emailSubject: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailSubject;
    emailContent: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200EmailContent;
    smsContent: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200SmsContent;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    services: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId200ServicesItem[];
};
