/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiSoldBundleOffersIdBodyStatus } from './patchApiSoldBundleOffersIdBodyStatus';
import type { PatchApiSoldBundleOffersIdBodyServices } from './patchApiSoldBundleOffersIdBodyServices';

export type PatchApiSoldBundleOffersIdBody = {
    /**
     * Original punches for the bundle offer
     * @minimum 0
     */
    orignalPunches?: number;
    /**
     * Remaining punches for the bundle offer
     * @minimum 0
     */
    residuePunches?: number;
    /** Status of the sold bundle offer */
    status?: PatchApiSoldBundleOffersIdBodyStatus;
    /** Optional note about the bundle offer */
    note?: string;
    /** Expiry date for the bundle offer (YYYY-MM-DD format) */
    expiryDate?: string;
    /** Personal message for the bundle offer */
    personalMessage?: string;
    /** Services configuration for the bundle offer */
    services?: PatchApiSoldBundleOffersIdBodyServices;
};
