/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error';

export type PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500 = {
    statusCode: number;
    error: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId500Error;
    message: string;
};
