/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiGoogleCalendarSettings200Data = {
    syncOpeningHours?: boolean;
    /** When turning off: number of events removed from Google Calendar */
    eventsDeleted?: number;
    /** When turning on: number of schedule events synced */
    schedulesSynced?: number;
    /** When turning on: number of holiday events synced */
    holidaysSynced?: number;
};
