/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiGiftCardsIdStatus200HistoryItemInvoiceNumber } from './patchApiGiftCardsIdStatus200HistoryItemInvoiceNumber';

export type PatchApiGiftCardsIdStatus200HistoryItem = {
    salesId: string;
    invoiceNumber: PatchApiGiftCardsIdStatus200HistoryItemInvoiceNumber;
    amountUsed: number;
    dateTime: string;
};
