/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiServicesDeposit500Error =
    (typeof PatchApiServicesDeposit500Error)[keyof typeof PatchApiServicesDeposit500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiServicesDeposit500Error = {
    Bad_Request: 'Bad Request',
} as const;
