/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiDoctorsPortalMessagesMessageIdRead500Error =
    (typeof PatchApiDoctorsPortalMessagesMessageIdRead500Error)[keyof typeof PatchApiDoctorsPortalMessagesMessageIdRead500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiDoctorsPortalMessagesMessageIdRead500Error = {
    Bad_Request: 'Bad Request',
} as const;
