/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiGiftCardsIdStatus200CustomerAnyOfEmail } from './patchApiGiftCardsIdStatus200CustomerAnyOfEmail';

export type PatchApiGiftCardsIdStatus200CustomerAnyOf = {
    id: number;
    name: string;
    email: PatchApiGiftCardsIdStatus200CustomerAnyOfEmail;
    phoneNumber: string;
};
