/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiBundleOffersIdStatus200Status =
    (typeof PatchApiBundleOffersIdStatus200Status)[keyof typeof PatchApiBundleOffersIdStatus200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiBundleOffersIdStatus200Status = {
    BLOCKED: 'BLOCKED',
    EXPIRED: 'EXPIRED',
    USED: 'USED',
    UNUSED: 'UNUSED',
    PARTIALLY_USED: 'PARTIALLY_USED',
} as const;
