/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceGroupsIdDrivingFees400Error } from './patchApiServiceGroupsIdDrivingFees400Error';

export type PatchApiServiceGroupsIdDrivingFees400 = {
    statusCode: number;
    error: PatchApiServiceGroupsIdDrivingFees400Error;
    message: string;
};
