/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiServicesDeposit200DataUpdatedServicesItemDepositType =
    (typeof PatchApiServicesDeposit200DataUpdatedServicesItemDepositType)[keyof typeof PatchApiServicesDeposit200DataUpdatedServicesItemDepositType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiServicesDeposit200DataUpdatedServicesItemDepositType = {
    PERCENTAGE: 'PERCENTAGE',
    AMOUNT: 'AMOUNT',
} as const;
