/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiBookingStatusUpdate500Error =
    (typeof PatchApiBookingStatusUpdate500Error)[keyof typeof PatchApiBookingStatusUpdate500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiBookingStatusUpdate500Error = {
    Bad_Request: 'Bad Request',
} as const;
