/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServicesDeposit500Error } from './patchApiServicesDeposit500Error';

export type PatchApiServicesDeposit500 = {
    statusCode: number;
    error: PatchApiServicesDeposit500Error;
    message: string;
};
