/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiBundleOffersIdStatusBodyStatus } from './patchApiBundleOffersIdStatusBodyStatus';

export type PatchApiBundleOffersIdStatusBody = {
    /** New status for the bundle offer */
    status: PatchApiBundleOffersIdStatusBodyStatus;
    /** Optional note about the status change */
    note?: string;
};
