/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServicesDepositBodyServicesItemDepositType } from './patchApiServicesDepositBodyServicesItemDepositType';

export type PatchApiServicesDepositBodyServicesItem = {
    /** Service ID */
    id: number;
    /** Type of deposit: PERCENTAGE or AMOUNT */
    depositType?: PatchApiServicesDepositBodyServicesItemDepositType;
    /**
     * Deposit value. For PERCENTAGE: 0-100, for AMOUNT: fixed amount in currency units. Set to 0 to effectively disable deposit.
     * @minimum 0
     */
    depositValue?: number;
};
