/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiBookingsNoShowId500Error } from './patchApiBookingsNoShowId500Error';

export type PatchApiBookingsNoShowId500 = {
    statusCode: number;
    error: PatchApiBookingsNoShowId500Error;
    message: string;
};
