/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiGiftCardsId200CustomerAnyOf } from './patchApiGiftCardsId200CustomerAnyOf';

export type PatchApiGiftCardsId200Customer = PatchApiGiftCardsId200CustomerAnyOf | null;
