/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiEmployeeOpeningHoursEmployeeId500Error =
    (typeof PatchApiEmployeeOpeningHoursEmployeeId500Error)[keyof typeof PatchApiEmployeeOpeningHoursEmployeeId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiEmployeeOpeningHoursEmployeeId500Error = {
    Bad_Request: 'Bad Request',
} as const;
