/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServicesDeposit200DataUpdatedServicesItemDepositType } from './patchApiServicesDeposit200DataUpdatedServicesItemDepositType';

export type PatchApiServicesDeposit200DataUpdatedServicesItem = {
    id?: number;
    name?: string;
    sequence?: number;
    depositType?: PatchApiServicesDeposit200DataUpdatedServicesItemDepositType;
    depositValue?: number;
};
