/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceAdvancedReminderTemplatesReminderTemplateId400Error } from './patchApiServiceAdvancedReminderTemplatesReminderTemplateId400Error';

export type PatchApiServiceAdvancedReminderTemplatesReminderTemplateId400 = {
    statusCode: number;
    error: PatchApiServiceAdvancedReminderTemplatesReminderTemplateId400Error;
    message: string;
};
