/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiGoogleCalendarSettings200Data } from './patchApiGoogleCalendarSettings200Data';

export type PatchApiGoogleCalendarSettings200 = {
    success?: boolean;
    data?: PatchApiGoogleCalendarSettings200Data;
    message?: string;
};
