/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiGoogleCalendarSettings400Error } from './patchApiGoogleCalendarSettings400Error';

export type PatchApiGoogleCalendarSettings400 = {
    statusCode: number;
    error: PatchApiGoogleCalendarSettings400Error;
    message: string;
};
