/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServicesDeposit200DataUpdatedServicesItem } from './patchApiServicesDeposit200DataUpdatedServicesItem';
import type { PatchApiServicesDeposit200DataDepositSetting } from './patchApiServicesDeposit200DataDepositSetting';

export type PatchApiServicesDeposit200Data = {
    updatedServices: PatchApiServicesDeposit200DataUpdatedServicesItem[];
    depositSetting: PatchApiServicesDeposit200DataDepositSetting;
};
