/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiServiceGroupsIdDrivingFees500Error } from './patchApiServiceGroupsIdDrivingFees500Error';

export type PatchApiServiceGroupsIdDrivingFees500 = {
    statusCode: number;
    error: PatchApiServiceGroupsIdDrivingFees500Error;
    message: string;
};
