/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAbortCardPayment400Error =
    (typeof PostApiAbortCardPayment400Error)[keyof typeof PostApiAbortCardPayment400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAbortCardPayment400Error = {
    Bad_Request: 'Bad Request',
} as const;
