/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSale201DataPaymentItemTxStatus =
    (typeof PostApiSale201DataPaymentItemTxStatus)[keyof typeof PostApiSale201DataPaymentItemTxStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSale201DataPaymentItemTxStatus = {
    PENDING: 'PENDING',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    SUCCEEDED: 'SUCCEEDED',
    CANCELLED: 'CANCELLED',
} as const;
