/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationTemplates201Data } from './postApiHealthDeclarationTemplates201Data';

export type PostApiHealthDeclarationTemplates201 = {
    statusCode: number;
    message: string;
    success: boolean;
    data: PostApiHealthDeclarationTemplates201Data;
};
