/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiFilesUpload201FilesItem } from './postApiFilesUpload201FilesItem';

export type PostApiFilesUpload201 = {
    files: PostApiFilesUpload201FilesItem[];
};
