/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiDoctorsPortalInviteDoctorUuid500Error } from './postApiDoctorsPortalInviteDoctorUuid500Error';

export type PostApiDoctorsPortalInviteDoctorUuid500 = {
    statusCode: number;
    error: PostApiDoctorsPortalInviteDoctorUuid500Error;
    message: string;
};
