/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiProduct500Error } from './postApiProduct500Error';

export type PostApiProduct500 = {
    statusCode: number;
    error: PostApiProduct500Error;
    message: string;
};
