/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSale500Error = (typeof PostApiSale500Error)[keyof typeof PostApiSale500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSale500Error = {
    Bad_Request: 'Bad Request',
} as const;
