/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiExpense201CashDrawerId } from './postApiExpense201CashDrawerId';
import type { PostApiExpense201Description } from './postApiExpense201Description';
import type { PostApiExpense201CreatedAt } from './postApiExpense201CreatedAt';
import type { PostApiExpense201ExpenseCategory } from './postApiExpense201ExpenseCategory';
import type { PostApiExpense201Employee } from './postApiExpense201Employee';

export type PostApiExpense201 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    cashDrawerId?: PostApiExpense201CashDrawerId;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount: number;
    description: PostApiExpense201Description;
    createdAt: PostApiExpense201CreatedAt;
    updatedAt: string;
    expenseCategory: PostApiExpense201ExpenseCategory;
    employee: PostApiExpense201Employee;
};
