/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiWebhooks500Error = (typeof PostApiWebhooks500Error)[keyof typeof PostApiWebhooks500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiWebhooks500Error = {
    Bad_Request: 'Bad Request',
} as const;
