/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiItemTax500Error = (typeof PostApiItemTax500Error)[keyof typeof PostApiItemTax500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiItemTax500Error = {
    Bad_Request: 'Bad Request',
} as const;
