/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGiftCardsIdUse200GiftCardCode } from './postApiGiftCardsIdUse200GiftCardCode';
import type { PostApiGiftCardsIdUse200RecipientName } from './postApiGiftCardsIdUse200RecipientName';
import type { PostApiGiftCardsIdUse200Status } from './postApiGiftCardsIdUse200Status';
import type { PostApiGiftCardsIdUse200ExpiryDate } from './postApiGiftCardsIdUse200ExpiryDate';
import type { PostApiGiftCardsIdUse200PersonalMessage } from './postApiGiftCardsIdUse200PersonalMessage';
import type { PostApiGiftCardsIdUse200SoldBy } from './postApiGiftCardsIdUse200SoldBy';
import type { PostApiGiftCardsIdUse200Note } from './postApiGiftCardsIdUse200Note';
import type { PostApiGiftCardsIdUse200CustomerId } from './postApiGiftCardsIdUse200CustomerId';
import type { PostApiGiftCardsIdUse200GiftCardOnlineId } from './postApiGiftCardsIdUse200GiftCardOnlineId';
import type { PostApiGiftCardsIdUse200Customer } from './postApiGiftCardsIdUse200Customer';
import type { PostApiGiftCardsIdUse200HistoryItem } from './postApiGiftCardsIdUse200HistoryItem';

export type PostApiGiftCardsIdUse200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    giftCardCode: PostApiGiftCardsIdUse200GiftCardCode;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    originalValue: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    residueValue: number;
    recipientName: PostApiGiftCardsIdUse200RecipientName;
    status: PostApiGiftCardsIdUse200Status;
    applicableServiceIds?: string[];
    expiryDate: PostApiGiftCardsIdUse200ExpiryDate;
    taxIds?: string[];
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    taxAmount: number;
    personalMessage: PostApiGiftCardsIdUse200PersonalMessage;
    soldBy: PostApiGiftCardsIdUse200SoldBy;
    createdAt: string;
    note: PostApiGiftCardsIdUse200Note;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    sourceId: number;
    customerId: PostApiGiftCardsIdUse200CustomerId;
    giftCardOnlineId: PostApiGiftCardsIdUse200GiftCardOnlineId;
    updatedAt: string;
    customer?: PostApiGiftCardsIdUse200Customer;
    history?: PostApiGiftCardsIdUse200HistoryItem[];
};
