/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOfEmployeeName } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOfEmployeeName';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOf = {
    employeeId: number;
    employeeName?: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOfEmployeeName;
};
