/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCalendlyDisconnect500Error } from './postApiCalendlyDisconnect500Error';

export type PostApiCalendlyDisconnect500 = {
    statusCode: number;
    error: PostApiCalendlyDisconnect500Error;
    message: string;
};
