/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiHealthDeclarationBookingBookingIdSendEmail500Error =
    (typeof PostApiHealthDeclarationBookingBookingIdSendEmail500Error)[keyof typeof PostApiHealthDeclarationBookingBookingIdSendEmail500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiHealthDeclarationBookingBookingIdSendEmail500Error = {
    Bad_Request: 'Bad Request',
} as const;
