/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSupplier201Address } from './postApiSupplier201Address';
import type { PostApiSupplier201City } from './postApiSupplier201City';
import type { PostApiSupplier201ZipCode } from './postApiSupplier201ZipCode';
import type { PostApiSupplier201Country } from './postApiSupplier201Country';
import type { PostApiSupplier201Email } from './postApiSupplier201Email';
import type { PostApiSupplier201CountryCode } from './postApiSupplier201CountryCode';
import type { PostApiSupplier201Phone } from './postApiSupplier201Phone';
import type { PostApiSupplier201CountryISOCode } from './postApiSupplier201CountryISOCode';
import type { PostApiSupplier201Website } from './postApiSupplier201Website';
import type { PostApiSupplier201Description } from './postApiSupplier201Description';
import type { PostApiSupplier201CvrNumber } from './postApiSupplier201CvrNumber';
import type { PostApiSupplier201ContactPersonName } from './postApiSupplier201ContactPersonName';
import type { PostApiSupplier201ContactPersonEmail } from './postApiSupplier201ContactPersonEmail';
import type { PostApiSupplier201ContactPersonPhone } from './postApiSupplier201ContactPersonPhone';
import type { PostApiSupplier201OutletId } from './postApiSupplier201OutletId';

export type PostApiSupplier201 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    address: PostApiSupplier201Address;
    city: PostApiSupplier201City;
    zipCode: PostApiSupplier201ZipCode;
    country: PostApiSupplier201Country;
    email: PostApiSupplier201Email;
    countryCode: PostApiSupplier201CountryCode;
    phone: PostApiSupplier201Phone;
    countryISOCode: PostApiSupplier201CountryISOCode;
    website: PostApiSupplier201Website;
    description: PostApiSupplier201Description;
    cvrNumber: PostApiSupplier201CvrNumber;
    contactPersonName: PostApiSupplier201ContactPersonName;
    contactPersonEmail: PostApiSupplier201ContactPersonEmail;
    contactPersonPhone: PostApiSupplier201ContactPersonPhone;
    outletId: PostApiSupplier201OutletId;
    createdAt: string;
    updatedAt: string;
};
