/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Render ID that will be stored in the condition table (optional)
 */
export type PostApiCampaignsBodyConditionsItemRenderId = string | null;
