/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPaymentsSubscriptionStart201Data } from './postApiPaymentsSubscriptionStart201Data';

export type PostApiPaymentsSubscriptionStart201 = {
    success?: boolean;
    data?: PostApiPaymentsSubscriptionStart201Data;
};
