/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSale201DataShortInvoiceId } from './postApiSale201DataShortInvoiceId';
import type { PostApiSale201DataCustomerId } from './postApiSale201DataCustomerId';
import type { PostApiSale201DataCustomerName } from './postApiSale201DataCustomerName';
import type { PostApiSale201DataTips } from './postApiSale201DataTips';
import type { PostApiSale201DataSalesNote } from './postApiSale201DataSalesNote';
import type { PostApiSale201DataVoidId } from './postApiSale201DataVoidId';
import type { PostApiSale201DataSalesType } from './postApiSale201DataSalesType';
import type { PostApiSale201DataCreatedBy } from './postApiSale201DataCreatedBy';
import type { PostApiSale201DataUpdatedBy } from './postApiSale201DataUpdatedBy';
import type { PostApiSale201DataSellBy } from './postApiSale201DataSellBy';
import type { PostApiSale201DataSyncedWith } from './postApiSale201DataSyncedWith';
import type { PostApiSale201DataSyncId } from './postApiSale201DataSyncId';
import type { PostApiSale201DataItemsItem } from './postApiSale201DataItemsItem';
import type { PostApiSale201DataSalesTaxesItem } from './postApiSale201DataSalesTaxesItem';
import type { PostApiSale201DataSalesDiscountsItem } from './postApiSale201DataSalesDiscountsItem';
import type { PostApiSale201DataPaymentItem } from './postApiSale201DataPaymentItem';

export type PostApiSale201Data = {
    id?: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId?: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    invAutoNumber?: number;
    salesDate?: string;
    invoiceId?: string;
    shortInvoiceId?: PostApiSale201DataShortInvoiceId;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId?: number;
    customerId?: PostApiSale201DataCustomerId;
    customerName?: PostApiSale201DataCustomerName;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    subTotal?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalTax?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalDiscount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    netTotal?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    roundOff?: number;
    tips?: PostApiSale201DataTips;
    salesNote?: PostApiSale201DataSalesNote;
    voidId?: PostApiSale201DataVoidId;
    salesType?: PostApiSale201DataSalesType;
    createdBy?: PostApiSale201DataCreatedBy;
    updatedBy?: PostApiSale201DataUpdatedBy;
    sellBy?: PostApiSale201DataSellBy;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    sourceId?: number;
    syncedWith?: PostApiSale201DataSyncedWith;
    syncId?: PostApiSale201DataSyncId;
    createdAt?: string;
    updatedAt?: string;
    items: PostApiSale201DataItemsItem[];
    salesTaxes: PostApiSale201DataSalesTaxesItem[];
    salesDiscounts: PostApiSale201DataSalesDiscountsItem[];
    payment: PostApiSale201DataPaymentItem[];
};
