/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsBodyConditionsItemFieldValue } from './postApiCampaignsBodyConditionsItemFieldValue';
import type { PostApiCampaignsBodyConditionsItemParentEntity } from './postApiCampaignsBodyConditionsItemParentEntity';
import type { PostApiCampaignsBodyConditionsItemJsonPath } from './postApiCampaignsBodyConditionsItemJsonPath';
import type { PostApiCampaignsBodyConditionsItemAggregateFn } from './postApiCampaignsBodyConditionsItemAggregateFn';
import type { PostApiCampaignsBodyConditionsItemAggregateGroup } from './postApiCampaignsBodyConditionsItemAggregateGroup';
import type { PostApiCampaignsBodyConditionsItemDescription } from './postApiCampaignsBodyConditionsItemDescription';
import type { PostApiCampaignsBodyConditionsItemRenderId } from './postApiCampaignsBodyConditionsItemRenderId';

export type PostApiCampaignsBodyConditionsItem = {
    /** ID of predefined condition template (1-10) */
    condition_id?: number;
    /** Value for the condition (e.g., "18,30" for age range, 50 for days) */
    field_value?: PostApiCampaignsBodyConditionsItemFieldValue;
    /** Entity to query (required for custom conditions) */
    entity?: string;
    /** Field to filter on (required for custom conditions) */
    field?: string;
    /** Operator (BETWEEN, =, IN, etc.) */
    operator?: string;
    parent_entity?: PostApiCampaignsBodyConditionsItemParentEntity;
    json_path?: PostApiCampaignsBodyConditionsItemJsonPath;
    aggregate_fn?: PostApiCampaignsBodyConditionsItemAggregateFn;
    aggregate_group?: PostApiCampaignsBodyConditionsItemAggregateGroup;
    description?: PostApiCampaignsBodyConditionsItemDescription;
    logical_group?: string;
    /** Sequence/order of condition (also accepts sequenceId) */
    seq_id?: number;
    /** Sequence/order of condition (alias for seq_id) */
    sequenceId?: number;
    /** Render ID that will be stored in the condition table (optional) */
    render_id?: PostApiCampaignsBodyConditionsItemRenderId;
};
