/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPublicHealthDeclarationsSubmit200DataResendByAnyOfEmployeeName } from './postApiPublicHealthDeclarationsSubmit200DataResendByAnyOfEmployeeName';

/**
 * @nullable
 */
export type PostApiPublicHealthDeclarationsSubmit200DataResendByAnyOf = {
    employeeId?: number;
    employeeName?: PostApiPublicHealthDeclarationsSubmit200DataResendByAnyOfEmployeeName;
} | null;
