/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationTemplatesBodyDescription } from './postApiHealthDeclarationTemplatesBodyDescription';

export type PostApiHealthDeclarationTemplatesBody = {
    /** @minLength 1 */
    name: string;
    description?: PostApiHealthDeclarationTemplatesBodyDescription;
    content?: unknown;
};
