/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiKlaviyoDisconnect500Error =
    (typeof PostApiKlaviyoDisconnect500Error)[keyof typeof PostApiKlaviyoDisconnect500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiKlaviyoDisconnect500Error = {
    Bad_Request: 'Bad Request',
} as const;
