/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * BCC email address for campaign
 */
export type PostApiCampaignsBodyBccEmail = string | null;
