/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Hour of the day (0-23) when campaign should trigger. Optional.
 * @minimum 0
 * @maximum 23
 */
export type PostApiCampaignsBodyScheduleTriggerTime = number | null;
