/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGoogleCalendarBookingSync200DataGoogleEvent } from './postApiGoogleCalendarBookingSync200DataGoogleEvent';
import type { PostApiGoogleCalendarBookingSync200DataBooking } from './postApiGoogleCalendarBookingSync200DataBooking';

export type PostApiGoogleCalendarBookingSync200Data = {
    googleEventId?: string;
    googleEvent?: PostApiGoogleCalendarBookingSync200DataGoogleEvent;
    booking?: PostApiGoogleCalendarBookingSync200DataBooking;
    /** True if new event created, false if updated */
    isNew?: boolean;
    /** True if event was deleted from Google Calendar */
    isDeleted?: boolean;
    /** Timezone used for the event */
    timeZone?: string;
};
