/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataItemsItemProductId } from './postApiCreateSalesOnline201DataItemsItemProductId';
import type { PostApiCreateSalesOnline201DataItemsItemBundleOfferId } from './postApiCreateSalesOnline201DataItemsItemBundleOfferId';
import type { PostApiCreateSalesOnline201DataItemsItemServiceId } from './postApiCreateSalesOnline201DataItemsItemServiceId';
import type { PostApiCreateSalesOnline201DataItemsItemEmployeeId } from './postApiCreateSalesOnline201DataItemsItemEmployeeId';
import type { PostApiCreateSalesOnline201DataItemsItemItemType } from './postApiCreateSalesOnline201DataItemsItemItemType';
import type { PostApiCreateSalesOnline201DataItemsItemSaleType } from './postApiCreateSalesOnline201DataItemsItemSaleType';
import type { PostApiCreateSalesOnline201DataItemsItemItemImageUrl } from './postApiCreateSalesOnline201DataItemsItemItemImageUrl';
import type { PostApiCreateSalesOnline201DataItemsItemUnitId } from './postApiCreateSalesOnline201DataItemsItemUnitId';
import type { PostApiCreateSalesOnline201DataItemsItemUnitName } from './postApiCreateSalesOnline201DataItemsItemUnitName';
import type { PostApiCreateSalesOnline201DataItemsItemUnitAbbreviation } from './postApiCreateSalesOnline201DataItemsItemUnitAbbreviation';
import type { PostApiCreateSalesOnline201DataItemsItemCategoryId } from './postApiCreateSalesOnline201DataItemsItemCategoryId';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountType } from './postApiCreateSalesOnline201DataItemsItemDiscountType';
import type { PostApiCreateSalesOnline201DataItemsItemTaxesItem } from './postApiCreateSalesOnline201DataItemsItemTaxesItem';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItem } from './postApiCreateSalesOnline201DataItemsItemDiscountsItem';

export type PostApiCreateSalesOnline201DataItemsItem = {
    productId?: PostApiCreateSalesOnline201DataItemsItemProductId;
    bundleOfferId?: PostApiCreateSalesOnline201DataItemsItemBundleOfferId;
    serviceId?: PostApiCreateSalesOnline201DataItemsItemServiceId;
    employeeId?: PostApiCreateSalesOnline201DataItemsItemEmployeeId;
    itemName?: string;
    itemType?: PostApiCreateSalesOnline201DataItemsItemItemType;
    saleType?: PostApiCreateSalesOnline201DataItemsItemSaleType;
    quantity: number;
    amount?: number;
    discountAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    taxAmount?: number;
    price: number;
    note?: string;
    description?: string;
    itemImageUrl?: PostApiCreateSalesOnline201DataItemsItemItemImageUrl;
    unitId?: PostApiCreateSalesOnline201DataItemsItemUnitId;
    unitName?: PostApiCreateSalesOnline201DataItemsItemUnitName;
    unitAbbreviation?: PostApiCreateSalesOnline201DataItemsItemUnitAbbreviation;
    categoryId?: PostApiCreateSalesOnline201DataItemsItemCategoryId;
    categoryName?: string;
    discountType?: PostApiCreateSalesOnline201DataItemsItemDiscountType;
    taxes?: PostApiCreateSalesOnline201DataItemsItemTaxesItem[];
    discounts?: PostApiCreateSalesOnline201DataItemsItemDiscountsItem[];
};
