/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsBodyScheduleTriggerDaysAnyOfItem } from './postApiCampaignsBodyScheduleTriggerDaysAnyOfItem';

/**
 * Array of days when campaign should trigger (e.g., ["sunday", "monday"]). Optional, can be null.
 */
export type PostApiCampaignsBodyScheduleTriggerDays = PostApiCampaignsBodyScheduleTriggerDaysAnyOfItem[] | null;
