/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSupplier500Error } from './postApiSupplier500Error';

export type PostApiSupplier500 = {
    statusCode: number;
    error: PostApiSupplier500Error;
    message: string;
};
