/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiProductCategories500Error =
    (typeof PostApiProductCategories500Error)[keyof typeof PostApiProductCategories500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiProductCategories500Error = {
    Bad_Request: 'Bad Request',
} as const;
