/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPaymentsWebhook400Error =
    (typeof PostApiPaymentsWebhook400Error)[keyof typeof PostApiPaymentsWebhook400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPaymentsWebhook400Error = {
    Bad_Request: 'Bad Request',
} as const;
