/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiServiceAdvancedReminderTemplates400Error } from './postApiServiceAdvancedReminderTemplates400Error';

export type PostApiServiceAdvancedReminderTemplates400 = {
    statusCode: number;
    error: PostApiServiceAdvancedReminderTemplates400Error;
    message: string;
};
