/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiServiceSubscription400Error =
    (typeof PostApiServiceSubscription400Error)[keyof typeof PostApiServiceSubscription400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiServiceSubscription400Error = {
    Bad_Request: 'Bad Request',
} as const;
