/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPaymentsSubscriptionStart400Error } from './postApiPaymentsSubscriptionStart400Error';

export type PostApiPaymentsSubscriptionStart400 = {
    statusCode: number;
    error: PostApiPaymentsSubscriptionStart400Error;
    message: string;
};
