/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiServiceAdvancedReminderTemplatesBodyReminderTemplateType } from './postApiServiceAdvancedReminderTemplatesBodyReminderTemplateType';
import type { PostApiServiceAdvancedReminderTemplatesBodyEmailSubject } from './postApiServiceAdvancedReminderTemplatesBodyEmailSubject';
import type { PostApiServiceAdvancedReminderTemplatesBodyEmailContent } from './postApiServiceAdvancedReminderTemplatesBodyEmailContent';
import type { PostApiServiceAdvancedReminderTemplatesBodySmsContent } from './postApiServiceAdvancedReminderTemplatesBodySmsContent';

export type PostApiServiceAdvancedReminderTemplatesBody = {
    /** @minLength 1 */
    reminderTemplateName: string;
    reminderTemplateType: PostApiServiceAdvancedReminderTemplatesBodyReminderTemplateType;
    /** @minimum 1 */
    reminderMinutes: number;
    emailSubject?: PostApiServiceAdvancedReminderTemplatesBodyEmailSubject;
    emailContent?: PostApiServiceAdvancedReminderTemplatesBodyEmailContent;
    smsContent?: PostApiServiceAdvancedReminderTemplatesBodySmsContent;
    isActive?: boolean;
    serviceIds?: number[];
};
