/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnlineBodyDataPaymentItemPaymentId } from './postApiCreateSalesOnlineBodyDataPaymentItemPaymentId';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemTxStatus } from './postApiCreateSalesOnlineBodyDataPaymentItemTxStatus';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemTerminalId } from './postApiCreateSalesOnlineBodyDataPaymentItemTerminalId';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemTerminalRefId } from './postApiCreateSalesOnlineBodyDataPaymentItemTerminalRefId';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemTerminalStatus } from './postApiCreateSalesOnlineBodyDataPaymentItemTerminalStatus';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemCardType } from './postApiCreateSalesOnlineBodyDataPaymentItemCardType';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemCardFourDigit } from './postApiCreateSalesOnlineBodyDataPaymentItemCardFourDigit';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemPaymentType } from './postApiCreateSalesOnlineBodyDataPaymentItemPaymentType';
import type { PostApiCreateSalesOnlineBodyDataPaymentItemBunddleOffer } from './postApiCreateSalesOnlineBodyDataPaymentItemBunddleOffer';

export type PostApiCreateSalesOnlineBodyDataPaymentItem = {
    paymentId?: PostApiCreateSalesOnlineBodyDataPaymentItemPaymentId;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change?: number;
    txStatus?: PostApiCreateSalesOnlineBodyDataPaymentItemTxStatus;
    terminalId?: PostApiCreateSalesOnlineBodyDataPaymentItemTerminalId;
    terminalRefId?: PostApiCreateSalesOnlineBodyDataPaymentItemTerminalRefId;
    terminalStatus?: PostApiCreateSalesOnlineBodyDataPaymentItemTerminalStatus;
    cardType?: PostApiCreateSalesOnlineBodyDataPaymentItemCardType;
    cardFourDigit?: PostApiCreateSalesOnlineBodyDataPaymentItemCardFourDigit;
    paymentType?: PostApiCreateSalesOnlineBodyDataPaymentItemPaymentType;
    terminalResponse?: string;
    currency?: string;
    giftCardId?: string;
    bunddleOffer?: PostApiCreateSalesOnlineBodyDataPaymentItemBunddleOffer;
};
