/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiServiceAdvancedReminderTemplates400Error =
    (typeof PostApiServiceAdvancedReminderTemplates400Error)[keyof typeof PostApiServiceAdvancedReminderTemplates400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiServiceAdvancedReminderTemplates400Error = {
    Bad_Request: 'Bad Request',
} as const;
