/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPublicHealthDeclarationsSubmit400Error =
    (typeof PostApiPublicHealthDeclarationsSubmit400Error)[keyof typeof PostApiPublicHealthDeclarationsSubmit400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPublicHealthDeclarationsSubmit400Error = {
    Bad_Request: 'Bad Request',
} as const;
