/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional test email address. If not provided, uses the test email from the campaign database.
 */
export type PostApiCampaignsIdSendTestEmailBodyTestEmail = string | null;
