/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiFilesUpload400Error } from './postApiFilesUpload400Error';

export type PostApiFilesUpload400 = {
    statusCode: number;
    error: PostApiFilesUpload400Error;
    message: string;
};
