/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiCustomerGroupsIdCustomersBody = {
    /** @minItems 1 */
    customerIds: number[];
};
