/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSale201DataSalesDiscountsItemSalesId } from './postApiSale201DataSalesDiscountsItemSalesId';
import type { PostApiSale201DataSalesDiscountsItemDiscountId } from './postApiSale201DataSalesDiscountsItemDiscountId';
import type { PostApiSale201DataSalesDiscountsItemCouponId } from './postApiSale201DataSalesDiscountsItemCouponId';
import type { PostApiSale201DataSalesDiscountsItemDiscountName } from './postApiSale201DataSalesDiscountsItemDiscountName';
import type { PostApiSale201DataSalesDiscountsItemDiscountAmount } from './postApiSale201DataSalesDiscountsItemDiscountAmount';
import type { PostApiSale201DataSalesDiscountsItemAmountType } from './postApiSale201DataSalesDiscountsItemAmountType';
import type { PostApiSale201DataSalesDiscountsItemAmount } from './postApiSale201DataSalesDiscountsItemAmount';
import type { PostApiSale201DataSalesDiscountsItemCreatedAt } from './postApiSale201DataSalesDiscountsItemCreatedAt';
import type { PostApiSale201DataSalesDiscountsItemUpdatedAt } from './postApiSale201DataSalesDiscountsItemUpdatedAt';

export type PostApiSale201DataSalesDiscountsItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesId: PostApiSale201DataSalesDiscountsItemSalesId;
    discountId: PostApiSale201DataSalesDiscountsItemDiscountId;
    couponId: PostApiSale201DataSalesDiscountsItemCouponId;
    discountName: PostApiSale201DataSalesDiscountsItemDiscountName;
    discountAmount: PostApiSale201DataSalesDiscountsItemDiscountAmount;
    amountType: PostApiSale201DataSalesDiscountsItemAmountType;
    amount: PostApiSale201DataSalesDiscountsItemAmount;
    createdAt: PostApiSale201DataSalesDiscountsItemCreatedAt;
    updatedAt: PostApiSale201DataSalesDiscountsItemUpdatedAt;
};
