/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiCashDrawerOpen201DataPaymentBreakdown = {
    cashAmount?: number;
    cardAmount?: number;
    mobilePayAmount?: number;
    bankTransferAmount?: number;
    creditAmount?: number;
    otherAmount?: number;
    outstandingAmount?: number;
    paidOutstandingAmount?: number;
    giftCardAmount?: number;
    bonusAmount?: number;
    outlayAmount?: number;
};
