/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaigns201Description } from './postApiCampaigns201Description';

export type PostApiCampaigns201 = {
    id?: string;
    outletId?: number;
    name?: string;
    description?: PostApiCampaigns201Description;
    messageType?: string;
    campaignType?: string;
    campaignStatus?: string;
    createdAt?: string;
    updatedAt?: string;
    /** Number of recipients for this campaign */
    recipientCount?: number;
};
