/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiServiceSubscription500Error =
    (typeof PostApiServiceSubscription500Error)[keyof typeof PostApiServiceSubscription500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiServiceSubscription500Error = {
    Bad_Request: 'Bad Request',
} as const;
