/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataShortInvoiceId } from './postApiCreateSalesOnline201DataShortInvoiceId';
import type { PostApiCreateSalesOnline201DataCustomerId } from './postApiCreateSalesOnline201DataCustomerId';
import type { PostApiCreateSalesOnline201DataCustomerName } from './postApiCreateSalesOnline201DataCustomerName';
import type { PostApiCreateSalesOnline201DataTips } from './postApiCreateSalesOnline201DataTips';
import type { PostApiCreateSalesOnline201DataSalesNote } from './postApiCreateSalesOnline201DataSalesNote';
import type { PostApiCreateSalesOnline201DataVoidId } from './postApiCreateSalesOnline201DataVoidId';
import type { PostApiCreateSalesOnline201DataSalesType } from './postApiCreateSalesOnline201DataSalesType';
import type { PostApiCreateSalesOnline201DataCreatedBy } from './postApiCreateSalesOnline201DataCreatedBy';
import type { PostApiCreateSalesOnline201DataUpdatedBy } from './postApiCreateSalesOnline201DataUpdatedBy';
import type { PostApiCreateSalesOnline201DataSellBy } from './postApiCreateSalesOnline201DataSellBy';
import type { PostApiCreateSalesOnline201DataSyncedWith } from './postApiCreateSalesOnline201DataSyncedWith';
import type { PostApiCreateSalesOnline201DataSyncId } from './postApiCreateSalesOnline201DataSyncId';
import type { PostApiCreateSalesOnline201DataItemsItem } from './postApiCreateSalesOnline201DataItemsItem';
import type { PostApiCreateSalesOnline201DataSalesTaxesItem } from './postApiCreateSalesOnline201DataSalesTaxesItem';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItem } from './postApiCreateSalesOnline201DataSalesDiscountsItem';
import type { PostApiCreateSalesOnline201DataPaymentItem } from './postApiCreateSalesOnline201DataPaymentItem';

export type PostApiCreateSalesOnline201Data = {
    id?: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId?: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    invAutoNumber?: number;
    salesDate?: string;
    invoiceId?: string;
    shortInvoiceId?: PostApiCreateSalesOnline201DataShortInvoiceId;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId?: number;
    customerId?: PostApiCreateSalesOnline201DataCustomerId;
    customerName?: PostApiCreateSalesOnline201DataCustomerName;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    subTotal?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalTax?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    totalDiscount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    netTotal?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    roundOff?: number;
    tips?: PostApiCreateSalesOnline201DataTips;
    salesNote?: PostApiCreateSalesOnline201DataSalesNote;
    voidId?: PostApiCreateSalesOnline201DataVoidId;
    salesType?: PostApiCreateSalesOnline201DataSalesType;
    createdBy?: PostApiCreateSalesOnline201DataCreatedBy;
    updatedBy?: PostApiCreateSalesOnline201DataUpdatedBy;
    sellBy?: PostApiCreateSalesOnline201DataSellBy;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    sourceId?: number;
    syncedWith?: PostApiCreateSalesOnline201DataSyncedWith;
    syncId?: PostApiCreateSalesOnline201DataSyncId;
    createdAt?: string;
    updatedAt?: string;
    items: PostApiCreateSalesOnline201DataItemsItem[];
    salesTaxes: PostApiCreateSalesOnline201DataSalesTaxesItem[];
    salesDiscounts: PostApiCreateSalesOnline201DataSalesDiscountsItem[];
    payment: PostApiCreateSalesOnline201DataPaymentItem[];
};
