/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGatewayapiWebhook200Updated } from './postApiGatewayapiWebhook200Updated';

export type PostApiGatewayapiWebhook200 = {
    success?: boolean;
    message?: string;
    updated?: PostApiGatewayapiWebhook200Updated;
};
