/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiKlaviyoDisconnect500Error } from './postApiKlaviyoDisconnect500Error';

export type PostApiKlaviyoDisconnect500 = {
    statusCode: number;
    error: PostApiKlaviyoDisconnect500Error;
    message: string;
};
