/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPaymentsWebhook404Error =
    (typeof PostApiPaymentsWebhook404Error)[keyof typeof PostApiPaymentsWebhook404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPaymentsWebhook404Error = {
    Bad_Request: 'Bad Request',
} as const;
