/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGoogleCalendarDisconnect500Error =
    (typeof PostApiGoogleCalendarDisconnect500Error)[keyof typeof PostApiGoogleCalendarDisconnect500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiGoogleCalendarDisconnect500Error = {
    Bad_Request: 'Bad Request',
} as const;
