/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendByAnyOfEmployeeName } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendByAnyOfEmployeeName';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendByAnyOf = {
    employeeId: number;
    employeeName?: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendByAnyOfEmployeeName;
};
