/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationTemplates201DataContentAnyOf } from './postApiHealthDeclarationTemplates201DataContentAnyOf';

export type PostApiHealthDeclarationTemplates201DataContent =
    PostApiHealthDeclarationTemplates201DataContentAnyOf | null;
