/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMakeCardPayment500Error =
    (typeof PostApiMakeCardPayment500Error)[keyof typeof PostApiMakeCardPayment500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiMakeCardPayment500Error = {
    Bad_Request: 'Bad Request',
} as const;
