/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPublicHealthDeclarationsSubmit401Error =
    (typeof PostApiPublicHealthDeclarationsSubmit401Error)[keyof typeof PostApiPublicHealthDeclarationsSubmit401Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPublicHealthDeclarationsSubmit401Error = {
    Bad_Request: 'Bad Request',
} as const;
