/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerCloseBodyCurrencyBreakdownItem } from './postApiCashDrawerCloseBodyCurrencyBreakdownItem';
import type { PostApiCashDrawerCloseBodyCardBreakdownItem } from './postApiCashDrawerCloseBodyCardBreakdownItem';
import type { PostApiCashDrawerCloseBodySalesBreakdownItem } from './postApiCashDrawerCloseBodySalesBreakdownItem';
import type { PostApiCashDrawerCloseBodyPaymentBreakdown } from './postApiCashDrawerCloseBodyPaymentBreakdown';

export type PostApiCashDrawerCloseBody = {
    closingCash: number;
    /** Currency breakdown array, e.g., [{1kr: 2, 5kr: 10}] */
    currencyBreakdown: PostApiCashDrawerCloseBodyCurrencyBreakdownItem[];
    /** Card breakdown array, e.g., [{visa: 4}, {mastercard: 10}] */
    cardBreakdown: PostApiCashDrawerCloseBodyCardBreakdownItem[];
    /** Sales breakdown array, e.g., [{productSale: 100, serviceSale: 200}] */
    salesBreakdown: PostApiCashDrawerCloseBodySalesBreakdownItem[];
    transferToBank: number;
    /** @minimum 1 */
    closedBy: number;
    /** Difference between expected and actual cash */
    difference: number;
    totalInDrawer: number;
    actualCash: number;
    /** Difference in card payments */
    cardDifference: number;
    /** Additional payment breakdown information */
    paymentBreakdown: PostApiCashDrawerCloseBodyPaymentBreakdown;
    cashDrawerId: string;
    /** Optional note for the closed drawer */
    note?: string;
    /** Date and time the drawer was closed */
    closeDate?: string;
};
