/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGatewayapiWebhookBodyId } from './postApiGatewayapiWebhookBodyId';
import type { PostApiGatewayapiWebhookBodyMsisdn } from './postApiGatewayapiWebhookBodyMsisdn';
import type { PostApiGatewayapiWebhookBodyTime } from './postApiGatewayapiWebhookBodyTime';
import type { PostApiGatewayapiWebhookBodyError } from './postApiGatewayapiWebhookBodyError';
import type { PostApiGatewayapiWebhookBodyCode } from './postApiGatewayapiWebhookBodyCode';
import type { PostApiGatewayapiWebhookBodyUserref } from './postApiGatewayapiWebhookBodyUserref';
import type { PostApiGatewayapiWebhookBodyCountryCode } from './postApiGatewayapiWebhookBodyCountryCode';
import type { PostApiGatewayapiWebhookBodyCountryPrefix } from './postApiGatewayapiWebhookBodyCountryPrefix';
import type { PostApiGatewayapiWebhookBodyMcc } from './postApiGatewayapiWebhookBodyMcc';
import type { PostApiGatewayapiWebhookBodyMnc } from './postApiGatewayapiWebhookBodyMnc';
import type { PostApiGatewayapiWebhookBodyChargeStatus } from './postApiGatewayapiWebhookBodyChargeStatus';

export type PostApiGatewayapiWebhookBody = {
    /** The ID of the SMS the notification concerns */
    id: PostApiGatewayapiWebhookBodyId;
    /** The MSISDN (phone number) of the mobile recipient */
    msisdn: PostApiGatewayapiWebhookBodyMsisdn;
    /** The UNIX Timestamp for the delivery status event */
    time?: PostApiGatewayapiWebhookBodyTime;
    /** One of the states: DELIVERED, UNDELIVERED, EXPIRED, DELETED, ACCEPTED, REJECTED, SKIPPED, BUFFERED, SCHEDULED, ENROUTE, UNKNOWN */
    status: string;
    /** Optional error description, if available */
    error?: PostApiGatewayapiWebhookBodyError;
    /** Optional numeric code, in hex, if available */
    code?: PostApiGatewayapiWebhookBodyCode;
    /** If you specified a reference when sending the message, it is returned to you */
    userref?: PostApiGatewayapiWebhookBodyUserref;
    /** Optional country code of the msisdn (e.g., "DK") */
    country_code?: PostApiGatewayapiWebhookBodyCountryCode;
    /** Optional country prefix of the msisdn (e.g., 45) */
    country_prefix?: PostApiGatewayapiWebhookBodyCountryPrefix;
    /** Optional Mobile Country Code */
    mcc?: PostApiGatewayapiWebhookBodyMcc;
    /** Optional Mobile Network Code */
    mnc?: PostApiGatewayapiWebhookBodyMnc;
    /** Charge status for overcharged SMS (e.g., CAPTURED) */
    charge_status?: PostApiGatewayapiWebhookBodyChargeStatus;
    [key: string]: unknown;
};
