/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiServiceSubscription400Error } from './postApiServiceSubscription400Error';

export type PostApiServiceSubscription400 = {
    statusCode: number;
    error: PostApiServiceSubscription400Error;
    message: string;
};
