/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAddonsUpsert200Data } from './postApiAddonsUpsert200Data';

export type PostApiAddonsUpsert200 = {
    success: boolean;
    message: string;
    data?: PostApiAddonsUpsert200Data;
    error?: string;
};
