/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiTrustpilot400Error = (typeof PostApiTrustpilot400Error)[keyof typeof PostApiTrustpilot400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiTrustpilot400Error = {
    Bad_Request: 'Bad Request',
} as const;
