/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiTax500Error = (typeof PostApiTax500Error)[keyof typeof PostApiTax500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiTax500Error = {
    Bad_Request: 'Bad Request',
} as const;
