/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGoogleCalendarSyncSchedule500Error =
    (typeof PostApiGoogleCalendarSyncSchedule500Error)[keyof typeof PostApiGoogleCalendarSyncSchedule500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiGoogleCalendarSyncSchedule500Error = {
    Bad_Request: 'Bad Request',
} as const;
