/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPublicHealthDeclarationsSubmit404Error } from './postApiPublicHealthDeclarationsSubmit404Error';

export type PostApiPublicHealthDeclarationsSubmit404 = {
    statusCode: number;
    error: PostApiPublicHealthDeclarationsSubmit404Error;
    message: string;
};
