/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiStockBodyType } from './postApiStockBodyType';

export type PostApiStockBody = {
    /** @minimum 1 */
    quantity: number;
    productId: string;
    type: PostApiStockBodyType;
};
