/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiCreateSalesOnline201DataItemsItemDiscountType =
    (typeof PostApiCreateSalesOnline201DataItemsItemDiscountType)[keyof typeof PostApiCreateSalesOnline201DataItemsItemDiscountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiCreateSalesOnline201DataItemsItemDiscountType = {
    AMOUNT: 'AMOUNT',
    PERCENTAGE: 'PERCENTAGE',
    VARIABLE_AMOUNT: 'VARIABLE_AMOUNT',
    VARIABLE_PERCENTAGE: 'VARIABLE_PERCENTAGE',
} as const;
