/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsIdSendTestEmail200MessageId } from './postApiCampaignsIdSendTestEmail200MessageId';

export type PostApiCampaignsIdSendTestEmail200 = {
    /** Whether the test email was sent successfully */
    success: boolean;
    /** Status message */
    message: string;
    /** Mailgun message ID for the sent email */
    messageId?: PostApiCampaignsIdSendTestEmail200MessageId;
};
