/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiServicesSync404Error =
    (typeof PostApiServicesSync404Error)[keyof typeof PostApiServicesSync404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiServicesSync404Error = {
    Bad_Request: 'Bad Request',
} as const;
