/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerOpen201Data } from './postApiCashDrawerOpen201Data';

export type PostApiCashDrawerOpen201 = {
    data: PostApiCashDrawerOpen201Data;
    message: string;
};
