/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBundleOffersUseBodyServicesItem } from './postApiBundleOffersUseBodyServicesItem';

export type PostApiBundleOffersUseBody = {
    /** Sold bundle offer ID to use */
    soldBundleOfferId: string;
    /**
     * Array of services to use with their quantities
     * @minItems 1
     */
    services: PostApiBundleOffersUseBodyServicesItem[];
};
