/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPaymentsWebhook400Error } from './postApiPaymentsWebhook400Error';

export type PostApiPaymentsWebhook400 = {
    statusCode: number;
    error: PostApiPaymentsWebhook400Error;
    message: string;
};
