/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAddonsUpsert400Error =
    (typeof PostApiAddonsUpsert400Error)[keyof typeof PostApiAddonsUpsert400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAddonsUpsert400Error = {
    Bad_Request: 'Bad Request',
} as const;
