/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerOpen201DataDetailedPaymentBreakdownItemItem } from './postApiCashDrawerOpen201DataDetailedPaymentBreakdownItemItem';

export type PostApiCashDrawerOpen201DataDetailedPaymentBreakdownItem = {
    [key: string]: PostApiCashDrawerOpen201DataDetailedPaymentBreakdownItemItem[];
};
