/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPublicHealthDeclarationsSubmit200DataResendByAnyOf } from './postApiPublicHealthDeclarationsSubmit200DataResendByAnyOf';

/**
 * @nullable
 */
export type PostApiPublicHealthDeclarationsSubmit200DataResendBy =
    null | PostApiPublicHealthDeclarationsSubmit200DataResendByAnyOf | null;
