/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional Mobile Network Code
 */
export type PostApiGatewayapiWebhookBodyMnc = string | null;
