/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsBodyDescription } from './postApiCampaignsBodyDescription';
import type { PostApiCampaignsBodyMessageType } from './postApiCampaignsBodyMessageType';
import type { PostApiCampaignsBodyCampaignType } from './postApiCampaignsBodyCampaignType';
import type { PostApiCampaignsBodyTestPhoneNumber } from './postApiCampaignsBodyTestPhoneNumber';
import type { PostApiCampaignsBodyTestEmail } from './postApiCampaignsBodyTestEmail';
import type { PostApiCampaignsBodyBccEmail } from './postApiCampaignsBodyBccEmail';
import type { PostApiCampaignsBodyConditionsItem } from './postApiCampaignsBodyConditionsItem';
import type { PostApiCampaignsBodyContent } from './postApiCampaignsBodyContent';
import type { PostApiCampaignsBodySchedule } from './postApiCampaignsBodySchedule';

export type PostApiCampaignsBody = {
    /** @minLength 1 */
    name: string;
    description?: PostApiCampaignsBodyDescription;
    messageType: PostApiCampaignsBodyMessageType;
    campaignType: PostApiCampaignsBodyCampaignType;
    /** Test phone number for campaign testing */
    testPhoneNumber?: PostApiCampaignsBodyTestPhoneNumber;
    /** Test email for campaign testing */
    testEmail?: PostApiCampaignsBodyTestEmail;
    /** BCC email address for campaign */
    bccEmail?: PostApiCampaignsBodyBccEmail;
    /** Conditions for targeting customers. Use either template-based (condition_id + field_value + operator + seq_id + render_id) or custom conditions (entity + field + operator + field_value) */
    conditions?: PostApiCampaignsBodyConditionsItem[];
    content: PostApiCampaignsBodyContent;
    schedule: PostApiCampaignsBodySchedule;
};
