/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiWebhooks400Error = (typeof PostApiWebhooks400Error)[keyof typeof PostApiWebhooks400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiWebhooks400Error = {
    Bad_Request: 'Bad Request',
} as const;
