/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMobilepayWebhookBodyAmount } from './postApiMobilepayWebhookBodyAmount';

export type PostApiMobilepayWebhookBody = {
    msn: string;
    reference: string;
    pspReference: string;
    name: string;
    amount: PostApiMobilepayWebhookBodyAmount;
    timestamp: string;
    idempotencyKey: string;
    success: boolean;
};
