/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAbortCardPayment200Data } from './postApiAbortCardPayment200Data';

export type PostApiAbortCardPayment200 = {
    success?: boolean;
    message?: string;
    data?: PostApiAbortCardPayment200Data;
};
