/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsIdSendTestEmailBodyTestEmail } from './postApiCampaignsIdSendTestEmailBodyTestEmail';
import type { PostApiCampaignsIdSendTestEmailBodySubject } from './postApiCampaignsIdSendTestEmailBodySubject';

export type PostApiCampaignsIdSendTestEmailBody = {
    /** Optional test email address. If not provided, uses the test email from the campaign database. */
    testEmail?: PostApiCampaignsIdSendTestEmailBodyTestEmail;
    /** Optional email subject. If not provided, uses the subject from the campaign content database. */
    subject?: PostApiCampaignsIdSendTestEmailBodySubject;
};
