/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBundleOffersUse200UpdatedServices } from './postApiBundleOffersUse200UpdatedServices';

export type PostApiBundleOffersUse200 = {
    success: boolean;
    message: string;
    updatedServices: PostApiBundleOffersUse200UpdatedServices;
    remainingResidue: number;
};
