/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiTrustpilot500Error } from './postApiTrustpilot500Error';

export type PostApiTrustpilot500 = {
    statusCode: number;
    error: PostApiTrustpilot500Error;
    message: string;
};
