/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPaymentsSubscriptionStart500Error =
    (typeof PostApiPaymentsSubscriptionStart500Error)[keyof typeof PostApiPaymentsSubscriptionStart500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPaymentsSubscriptionStart500Error = {
    Bad_Request: 'Bad Request',
} as const;
