/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The amount for the subscription
 * @minimum 0
 */
export type PostApiPaymentsSubscriptionStartBodyAmount = number | null;
