/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiIotValidateToken401 = {
    /** Whether the token is valid */
    valid?: boolean;
    /** Error message */
    message?: string;
};
