/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The UNIX Timestamp for the delivery status event
 */
export type PostApiGatewayapiWebhookCampaignIdBodyTime = number | string;
