/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPaymentsSubscriptionPayBody = {
    /** The subscription ID to pay for */
    subscriptionId: string;
    /**
     * The end date for billing calculation (YYYY-MM-DD format)
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
    endDate: string;
};
