/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItem } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItem';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid201 = {
    statusCode: number;
    message: string;
    success: boolean;
    data: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItem[];
};
