/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiDiscountBodyCouponId } from './postApiDiscountBodyCouponId';
import type { PostApiDiscountBodyAmountType } from './postApiDiscountBodyAmountType';

export type PostApiDiscountBody = {
    /** @minLength 1 */
    name: string;
    amount?: number;
    optionMaxDiscountValue?: number;
    couponId?: PostApiDiscountBodyCouponId;
    amountType?: PostApiDiscountBodyAmountType;
};
