/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiStock500Error = (typeof PostApiStock500Error)[keyof typeof PostApiStock500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiStock500Error = {
    Bad_Request: 'Bad Request',
} as const;
