/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiServicesSync400Error } from './postApiServicesSync400Error';

export type PostApiServicesSync400 = {
    statusCode: number;
    error: PostApiServicesSync400Error;
    message: string;
};
