/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGoogleCalendarSyncHolidays500Error =
    (typeof PostApiGoogleCalendarSyncHolidays500Error)[keyof typeof PostApiGoogleCalendarSyncHolidays500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiGoogleCalendarSyncHolidays500Error = {
    Bad_Request: 'Bad Request',
} as const;
