/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiKlaviyoDisconnect400Error =
    (typeof PostApiKlaviyoDisconnect400Error)[keyof typeof PostApiKlaviyoDisconnect400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiKlaviyoDisconnect400Error = {
    Bad_Request: 'Bad Request',
} as const;
