/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGatewayapiWebhook400Error } from './postApiGatewayapiWebhook400Error';

export type PostApiGatewayapiWebhook400 = {
    statusCode: number;
    error: PostApiGatewayapiWebhook400Error;
    message: string;
};
