/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSaleBodyDataPaymentItemTxStatus =
    (typeof PostApiSaleBodyDataPaymentItemTxStatus)[keyof typeof PostApiSaleBodyDataPaymentItemTxStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSaleBodyDataPaymentItemTxStatus = {
    PENDING: 'PENDING',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    SUCCEEDED: 'SUCCEEDED',
    CANCELLED: 'CANCELLED',
} as const;
