/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerOpen201DataCashDrawerId } from './postApiCashDrawerOpen201DataCashDrawerId';
import type { PostApiCashDrawerOpen201DataLastCashDrawerEndDate } from './postApiCashDrawerOpen201DataLastCashDrawerEndDate';
import type { PostApiCashDrawerOpen201DataDrawerName } from './postApiCashDrawerOpen201DataDrawerName';
import type { PostApiCashDrawerOpen201DataDrawerStatus } from './postApiCashDrawerOpen201DataDrawerStatus';
import type { PostApiCashDrawerOpen201DataDrawerStartDate } from './postApiCashDrawerOpen201DataDrawerStartDate';
import type { PostApiCashDrawerOpen201DataDrawerEndDate } from './postApiCashDrawerOpen201DataDrawerEndDate';
import type { PostApiCashDrawerOpen201DataPaymentBreakdown } from './postApiCashDrawerOpen201DataPaymentBreakdown';
import type { PostApiCashDrawerOpen201DataSalesBreakdown } from './postApiCashDrawerOpen201DataSalesBreakdown';
import type { PostApiCashDrawerOpen201DataCreditBreakdown } from './postApiCashDrawerOpen201DataCreditBreakdown';
import type { PostApiCashDrawerOpen201DataDetailedPaymentBreakdownItem } from './postApiCashDrawerOpen201DataDetailedPaymentBreakdownItem';

export type PostApiCashDrawerOpen201Data = {
    outletId: number;
    cashDrawerId: PostApiCashDrawerOpen201DataCashDrawerId;
    fromDate: string;
    toDate: string;
    totalSales: number;
    totalTenderAmount: number;
    openingCash: number;
    closingCash: number;
    lastCashDrawerEndDate: PostApiCashDrawerOpen201DataLastCashDrawerEndDate;
    drawerName: PostApiCashDrawerOpen201DataDrawerName;
    drawerStatus: PostApiCashDrawerOpen201DataDrawerStatus;
    drawerStartDate: PostApiCashDrawerOpen201DataDrawerStartDate;
    drawerEndDate: PostApiCashDrawerOpen201DataDrawerEndDate;
    paymentBreakdown: PostApiCashDrawerOpen201DataPaymentBreakdown;
    salesBreakdown: PostApiCashDrawerOpen201DataSalesBreakdown;
    creditBreakdown: PostApiCashDrawerOpen201DataCreditBreakdown;
    detailedPaymentBreakdown?: PostApiCashDrawerOpen201DataDetailedPaymentBreakdownItem[];
};
