/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCustomerGroups201OutletId } from './postApiCustomerGroups201OutletId';
import type { PostApiCustomerGroups201Description } from './postApiCustomerGroups201Description';
import type { PostApiCustomerGroups201CreatedBy } from './postApiCustomerGroups201CreatedBy';
import type { PostApiCustomerGroups201UpdatedBy } from './postApiCustomerGroups201UpdatedBy';
import type { PostApiCustomerGroups201DeletedAt } from './postApiCustomerGroups201DeletedAt';

export type PostApiCustomerGroups201 = {
    id: string;
    outletId?: PostApiCustomerGroups201OutletId;
    name: string;
    description?: PostApiCustomerGroups201Description;
    createdAt: string;
    createdBy?: PostApiCustomerGroups201CreatedBy;
    updatedAt: string;
    updatedBy?: PostApiCustomerGroups201UpdatedBy;
    deletedAt?: PostApiCustomerGroups201DeletedAt;
    isActive: boolean;
    customerCount?: number;
};
