/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGoogleCalendarBookingSyncByGroupUuid200Data } from './postApiGoogleCalendarBookingSyncByGroupUuid200Data';

export type PostApiGoogleCalendarBookingSyncByGroupUuid200 = {
    success?: boolean;
    /** Results object containing results for each requested event */
    data?: PostApiGoogleCalendarBookingSyncByGroupUuid200Data;
    message?: string;
};
