/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiProduct500Error = (typeof PostApiProduct500Error)[keyof typeof PostApiProduct500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiProduct500Error = {
    Bad_Request: 'Bad Request',
} as const;
