/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of bundle offer
 */
export type PostApiBundleOffersBodyBundleOfferType =
    (typeof PostApiBundleOffersBodyBundleOfferType)[keyof typeof PostApiBundleOffersBodyBundleOfferType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiBundleOffersBodyBundleOfferType = {
    PUNCH_BASED: 'PUNCH_BASED',
    SERVICE_BASED: 'SERVICE_BASED',
} as const;
