/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountId } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountId';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemCouponId } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemCouponId';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountName } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountName';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountAmount } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountAmount';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemAmountType } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemAmountType';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemAmount } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemAmount';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemCreatedAt } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemCreatedAt';
import type { PostApiCreateSalesOnline201DataItemsItemDiscountsItemUpdatedAt } from './postApiCreateSalesOnline201DataItemsItemDiscountsItemUpdatedAt';

export type PostApiCreateSalesOnline201DataItemsItemDiscountsItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesDetailId: string;
    discountId: PostApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountId;
    couponId: PostApiCreateSalesOnline201DataItemsItemDiscountsItemCouponId;
    discountName: PostApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountName;
    discountAmount: PostApiCreateSalesOnline201DataItemsItemDiscountsItemDiscountAmount;
    amountType: PostApiCreateSalesOnline201DataItemsItemDiscountsItemAmountType;
    amount: PostApiCreateSalesOnline201DataItemsItemDiscountsItemAmount;
    createdAt: PostApiCreateSalesOnline201DataItemsItemDiscountsItemCreatedAt;
    updatedAt: PostApiCreateSalesOnline201DataItemsItemDiscountsItemUpdatedAt;
};
