/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsBodyContentTemplateId } from './postApiCampaignsBodyContentTemplateId';
import type { PostApiCampaignsBodyContentContentCC } from './postApiCampaignsBodyContentContentCC';
import type { PostApiCampaignsBodyContentSender } from './postApiCampaignsBodyContentSender';
import type { PostApiCampaignsBodyContentSubject } from './postApiCampaignsBodyContentSubject';
import type { PostApiCampaignsBodyContentContentType } from './postApiCampaignsBodyContentContentType';

export type PostApiCampaignsBodyContent = {
    templateId?: PostApiCampaignsBodyContentTemplateId;
    contentCC?: PostApiCampaignsBodyContentContentCC;
    sender?: PostApiCampaignsBodyContentSender;
    subject?: PostApiCampaignsBodyContentSubject;
    content: string;
    contentType: PostApiCampaignsBodyContentContentType;
};
