/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional numeric code, in hex, if available
 */
export type PostApiGatewayapiWebhookBodyCode = string | null;
