/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The ID of the SMS the notification concerns
 */
export type PostApiGatewayapiWebhookBodyId = number | string;
