/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiKlaviyo500Error } from './postApiKlaviyo500Error';

export type PostApiKlaviyo500 = {
    statusCode: number;
    error: PostApiKlaviyo500Error;
    message: string;
};
