/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCalendlyWebhook500Error } from './postApiCalendlyWebhook500Error';

export type PostApiCalendlyWebhook500 = {
    statusCode: number;
    error: PostApiCalendlyWebhook500Error;
    message: string;
};
