/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGiftCardsOnlineBody = {
    /**
     * @minLength 1
     * @maxLength 255
     */
    name: string;
    /** @maxLength 1000 */
    description?: string;
    applicableServices?: string[];
    /**
     * @minimum 0
     */
    price: number;
    /**
     * @minimum 1
     * @maximum 3650
     */
    expiryDays?: number;
    sellOnline?: boolean;
};
