/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGiftCardsBodyGiftCardCode } from './postApiGiftCardsBodyGiftCardCode';

export type PostApiGiftCardsBody = {
    /** @maxLength 256 */
    recipientName?: string;
    giftCardCode?: PostApiGiftCardsBodyGiftCardCode;
    /**
     * @minimum 1
     */
    amount: number;
    applicableServiceIds?: string[];
};
