/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPaymentsWebhook404Error } from './postApiPaymentsWebhook404Error';

export type PostApiPaymentsWebhook404 = {
    statusCode: number;
    error: PostApiPaymentsWebhook404Error;
    message: string;
};
