/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiKlaviyo400Error } from './postApiKlaviyo400Error';

export type PostApiKlaviyo400 = {
    statusCode: number;
    error: PostApiKlaviyo400Error;
    message: string;
};
