/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMakeCardPaymentBody = {
    /** Payment amount */
    amount: number;
    /** Payment ID */
    paymentId: string;
    /** Currency code */
    currency: string;
    /** Payment method */
    paymentMethod: string;
};
