/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiTax201ApplyTaxTo = (typeof PostApiTax201ApplyTaxTo)[keyof typeof PostApiTax201ApplyTaxTo];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiTax201ApplyTaxTo = {
    ALL_ITEMS_SERVICES: 'ALL_ITEMS_SERVICES',
    SELECTED_ITEMS: 'SELECTED_ITEMS',
} as const;
