/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGatewayapiWebhook400Error =
    (typeof PostApiGatewayapiWebhook400Error)[keyof typeof PostApiGatewayapiWebhook400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiGatewayapiWebhook400Error = {
    Bad_Request: 'Bad Request',
} as const;
