/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiFilesUpload500Error } from './postApiFilesUpload500Error';

export type PostApiFilesUpload500 = {
    statusCode: number;
    error: PostApiFilesUpload500Error;
    message: string;
};
