/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiServiceAdvancedReminderTemplates201ReminderTemplateType =
    (typeof PostApiServiceAdvancedReminderTemplates201ReminderTemplateType)[keyof typeof PostApiServiceAdvancedReminderTemplates201ReminderTemplateType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiServiceAdvancedReminderTemplates201ReminderTemplateType = {
    SMS: 'SMS',
    EMAIL: 'EMAIL',
    EMAIL_AND_SMS: 'EMAIL_AND_SMS',
} as const;
