/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataPaymentItemCustomerId } from './postApiCreateSalesOnline201DataPaymentItemCustomerId';
import type { PostApiCreateSalesOnline201DataPaymentItemPaymentId } from './postApiCreateSalesOnline201DataPaymentItemPaymentId';
import type { PostApiCreateSalesOnline201DataPaymentItemCurrency } from './postApiCreateSalesOnline201DataPaymentItemCurrency';
import type { PostApiCreateSalesOnline201DataPaymentItemTxStatus } from './postApiCreateSalesOnline201DataPaymentItemTxStatus';
import type { PostApiCreateSalesOnline201DataPaymentItemTerminalId } from './postApiCreateSalesOnline201DataPaymentItemTerminalId';
import type { PostApiCreateSalesOnline201DataPaymentItemTerminalRefId } from './postApiCreateSalesOnline201DataPaymentItemTerminalRefId';
import type { PostApiCreateSalesOnline201DataPaymentItemTerminalStatus } from './postApiCreateSalesOnline201DataPaymentItemTerminalStatus';
import type { PostApiCreateSalesOnline201DataPaymentItemCardType } from './postApiCreateSalesOnline201DataPaymentItemCardType';
import type { PostApiCreateSalesOnline201DataPaymentItemCardFourDigit } from './postApiCreateSalesOnline201DataPaymentItemCardFourDigit';
import type { PostApiCreateSalesOnline201DataPaymentItemPaymentType } from './postApiCreateSalesOnline201DataPaymentItemPaymentType';
import type { PostApiCreateSalesOnline201DataPaymentItemTransactionType } from './postApiCreateSalesOnline201DataPaymentItemTransactionType';
import type { PostApiCreateSalesOnline201DataPaymentItemTerminalResponse } from './postApiCreateSalesOnline201DataPaymentItemTerminalResponse';
import type { PostApiCreateSalesOnline201DataPaymentItemCreatedAt } from './postApiCreateSalesOnline201DataPaymentItemCreatedAt';
import type { PostApiCreateSalesOnline201DataPaymentItemUpdatedAt } from './postApiCreateSalesOnline201DataPaymentItemUpdatedAt';

export type PostApiCreateSalesOnline201DataPaymentItem = {
    id?: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId?: number;
    salesId?: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId?: number;
    customerId?: PostApiCreateSalesOnline201DataPaymentItemCustomerId;
    paymentId?: PostApiCreateSalesOnline201DataPaymentItemPaymentId;
    receiptId?: string;
    currency?: PostApiCreateSalesOnline201DataPaymentItemCurrency;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change?: number;
    txStatus?: PostApiCreateSalesOnline201DataPaymentItemTxStatus;
    terminalId?: PostApiCreateSalesOnline201DataPaymentItemTerminalId;
    terminalRefId?: PostApiCreateSalesOnline201DataPaymentItemTerminalRefId;
    terminalStatus?: PostApiCreateSalesOnline201DataPaymentItemTerminalStatus;
    cardType?: PostApiCreateSalesOnline201DataPaymentItemCardType;
    cardFourDigit?: PostApiCreateSalesOnline201DataPaymentItemCardFourDigit;
    paymentType?: PostApiCreateSalesOnline201DataPaymentItemPaymentType;
    transactionType?: PostApiCreateSalesOnline201DataPaymentItemTransactionType;
    terminalResponse?: PostApiCreateSalesOnline201DataPaymentItemTerminalResponse;
    createdAt?: PostApiCreateSalesOnline201DataPaymentItemCreatedAt;
    updatedAt?: PostApiCreateSalesOnline201DataPaymentItemUpdatedAt;
};
