/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGoogleCalendarDisconnect500Error } from './postApiGoogleCalendarDisconnect500Error';

export type PostApiGoogleCalendarDisconnect500 = {
    statusCode: number;
    error: PostApiGoogleCalendarDisconnect500Error;
    message: string;
};
