/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiIotValidateToken200 = {
    /** Whether the token is valid */
    valid?: boolean;
    /** Response message */
    message?: string;
    /** Outlet ID if valid */
    outletId?: number;
    /** Device ID if valid */
    deviceId?: string;
    /** Auth key if valid */
    authKey?: string;
};
