/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMarketplaceV2ConsentCheck500Error } from './postApiMarketplaceV2ConsentCheck500Error';

export type PostApiMarketplaceV2ConsentCheck500 = {
    statusCode: number;
    error: PostApiMarketplaceV2ConsentCheck500Error;
    message: string;
};
