/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationTemplates500Error } from './postApiHealthDeclarationTemplates500Error';

export type PostApiHealthDeclarationTemplates500 = {
    statusCode: number;
    error: PostApiHealthDeclarationTemplates500Error;
    message: string;
};
