/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline500Error } from './postApiCreateSalesOnline500Error';

export type PostApiCreateSalesOnline500 = {
    statusCode: number;
    error: PostApiCreateSalesOnline500Error;
    message: string;
};
