/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiIotValidateToken400Error } from './postApiIotValidateToken400Error';

export type PostApiIotValidateToken400 = {
    statusCode: number;
    error: PostApiIotValidateToken400Error;
    message: string;
};
