/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGatewayapiWebhookCampaignId400Error =
    (typeof PostApiGatewayapiWebhookCampaignId400Error)[keyof typeof PostApiGatewayapiWebhookCampaignId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiGatewayapiWebhookCampaignId400Error = {
    Bad_Request: 'Bad Request',
} as const;
