/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnlineBodyDataSalesTaxesItemTaxId } from './postApiCreateSalesOnlineBodyDataSalesTaxesItemTaxId';
import type { PostApiCreateSalesOnlineBodyDataSalesTaxesItemTaxName } from './postApiCreateSalesOnlineBodyDataSalesTaxesItemTaxName';

export type PostApiCreateSalesOnlineBodyDataSalesTaxesItem = {
    taxId?: PostApiCreateSalesOnlineBodyDataSalesTaxesItemTaxId;
    taxName?: PostApiCreateSalesOnlineBodyDataSalesTaxesItemTaxName;
    taxRate?: number;
    taxAmount?: number;
    includeTaxInItemPrice?: boolean;
    isInclusive?: boolean;
};
