/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid400Error =
    (typeof PostApiHealthDeclarationsGroupBookingGroupBookingUuid400Error)[keyof typeof PostApiHealthDeclarationsGroupBookingGroupBookingUuid400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiHealthDeclarationsGroupBookingGroupBookingUuid400Error = {
    Bad_Request: 'Bad Request',
} as const;
