/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiFilesUpload500Error = (typeof PostApiFilesUpload500Error)[keyof typeof PostApiFilesUpload500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiFilesUpload500Error = {
    Bad_Request: 'Bad Request',
} as const;
