/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnlineBodyCustomer } from './postApiCreateSalesOnlineBodyCustomer';
import type { PostApiCreateSalesOnlineBodyData } from './postApiCreateSalesOnlineBodyData';

export type PostApiCreateSalesOnlineBody = {
    outletId?: number;
    employeeId?: number;
    outletName?: string;
    customer?: PostApiCreateSalesOnlineBodyCustomer;
    data: PostApiCreateSalesOnlineBodyData;
};
