/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiDoctorsPortalInviteDoctorUuid400Error } from './postApiDoctorsPortalInviteDoctorUuid400Error';

export type PostApiDoctorsPortalInviteDoctorUuid400 = {
    statusCode: number;
    error: PostApiDoctorsPortalInviteDoctorUuid400Error;
    message: string;
};
