/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGatewayapiWebhookCampaignId500Error =
    (typeof PostApiGatewayapiWebhookCampaignId500Error)[keyof typeof PostApiGatewayapiWebhookCampaignId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiGatewayapiWebhookCampaignId500Error = {
    Bad_Request: 'Bad Request',
} as const;
