/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiProduct201Description } from './postApiProduct201Description';
import type { PostApiProduct201Image } from './postApiProduct201Image';
import type { PostApiProduct201Sku } from './postApiProduct201Sku';
import type { PostApiProduct201CategoryId } from './postApiProduct201CategoryId';
import type { PostApiProduct201SupplierId } from './postApiProduct201SupplierId';
import type { PostApiProduct201Brand } from './postApiProduct201Brand';
import type { PostApiProduct201OutletId } from './postApiProduct201OutletId';

export type PostApiProduct201 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    description: PostApiProduct201Description;
    image: PostApiProduct201Image;
    sku: PostApiProduct201Sku;
    categoryId: PostApiProduct201CategoryId;
    supplierId: PostApiProduct201SupplierId;
    brand: PostApiProduct201Brand;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    price: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    costPrice: number;
    isActive: boolean;
    availableOnline: boolean;
    outletId: PostApiProduct201OutletId;
    createdAt: string;
    updatedAt: string;
};
