/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSale201DataSalesTaxesItemTaxId } from './postApiSale201DataSalesTaxesItemTaxId';
import type { PostApiSale201DataSalesTaxesItemTaxName } from './postApiSale201DataSalesTaxesItemTaxName';

export type PostApiSale201DataSalesTaxesItem = {
    taxId?: PostApiSale201DataSalesTaxesItemTaxId;
    taxName?: PostApiSale201DataSalesTaxesItemTaxName;
    taxRate?: number;
    taxAmount?: number;
    includeTaxInItemPrice?: boolean;
    isInclusive?: boolean;
};
