/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiServicesSync400Error =
    (typeof PostApiServicesSync400Error)[keyof typeof PostApiServicesSync400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiServicesSync400Error = {
    Bad_Request: 'Bad Request',
} as const;
