/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiTrustpilot400Error } from './postApiTrustpilot400Error';

export type PostApiTrustpilot400 = {
    statusCode: number;
    error: PostApiTrustpilot400Error;
    message: string;
};
