/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAddonsUpsert400Error } from './postApiAddonsUpsert400Error';

export type PostApiAddonsUpsert400 = {
    statusCode: number;
    error: PostApiAddonsUpsert400Error;
    message: string;
};
