/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMarketplaceV2ConsentCheck500Error =
    (typeof PostApiMarketplaceV2ConsentCheck500Error)[keyof typeof PostApiMarketplaceV2ConsentCheck500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiMarketplaceV2ConsentCheck500Error = {
    Bad_Request: 'Bad Request',
} as const;
