/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCampaignsBodyConditionsItemFieldValueAnyOf } from './postApiCampaignsBodyConditionsItemFieldValueAnyOf';

/**
 * Value for the condition (e.g., "18,30" for age range, 50 for days)
 */
export type PostApiCampaignsBodyConditionsItemFieldValue =
    | unknown[]
    | string
    | number
    | boolean
    | PostApiCampaignsBodyConditionsItemFieldValueAnyOf
    | null;
