/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerClose200DataDetailedPaymentBreakdownItemItem } from './postApiCashDrawerClose200DataDetailedPaymentBreakdownItemItem';

export type PostApiCashDrawerClose200DataDetailedPaymentBreakdownItem = {
    [key: string]: PostApiCashDrawerClose200DataDetailedPaymentBreakdownItemItem[];
};
