/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Additional payment breakdown information
 */
export type PostApiCashDrawerCloseBodyPaymentBreakdown = { [key: string]: unknown };
