/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPaymentsSubscriptionPay200DataInvoiceData } from './postApiPaymentsSubscriptionPay200DataInvoiceData';
import type { PostApiPaymentsSubscriptionPay200DataBillingPeriod } from './postApiPaymentsSubscriptionPay200DataBillingPeriod';

export type PostApiPaymentsSubscriptionPay200Data = {
    subscriptionId?: string;
    outletId?: number;
    monthsBilled?: number;
    amount?: number;
    chargeType?: string;
    invoiceData?: PostApiPaymentsSubscriptionPay200DataInvoiceData;
    billingPeriod?: PostApiPaymentsSubscriptionPay200DataBillingPeriod;
};
