/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerClose500Error } from './postApiCashDrawerClose500Error';

export type PostApiCashDrawerClose500 = {
    statusCode: number;
    error: PostApiCashDrawerClose500Error;
    message: string;
};
