/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiCreateSalesOnline201DataItemsItemSaleType =
    (typeof PostApiCreateSalesOnline201DataItemsItemSaleType)[keyof typeof PostApiCreateSalesOnline201DataItemsItemSaleType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiCreateSalesOnline201DataItemsItemSaleType = {
    SALE: 'SALE',
    RETURN: 'RETURN',
} as const;
