/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSendSalesEmail500Error } from './postApiSendSalesEmail500Error';

export type PostApiSendSalesEmail500 = {
    statusCode: number;
    error: PostApiSendSalesEmail500Error;
    message: string;
};
