/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSale201Data } from './postApiSale201Data';

export type PostApiSale201 = {
    data: PostApiSale201Data;
};
