/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiTrustpilotDisconnect500Error =
    (typeof PostApiTrustpilotDisconnect500Error)[keyof typeof PostApiTrustpilotDisconnect500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiTrustpilotDisconnect500Error = {
    Bad_Request: 'Bad Request',
} as const;
