/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiTaxBodyApplyTaxTo } from './postApiTaxBodyApplyTaxTo';
import type { PostApiTaxBodyTaxType } from './postApiTaxBodyTaxType';

export type PostApiTaxBody = {
    /** @minLength 1 */
    taxName: string;
    taxRate?: number;
    applyTaxTo: PostApiTaxBodyApplyTaxTo;
    taxType: PostApiTaxBodyTaxType;
    taxOnCustomAmounts: boolean;
    taxExemption: boolean;
    includeTaxInItemPrice: boolean;
    isActive: boolean;
};
