/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSale201DataSalesDiscountsItemAmountType =
    (typeof PostApiSale201DataSalesDiscountsItemAmountType)[keyof typeof PostApiSale201DataSalesDiscountsItemAmountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSale201DataSalesDiscountsItemAmountType = {
    AMOUNT: 'AMOUNT',
    PERCENTAGE: 'PERCENTAGE',
    VARIABLE_AMOUNT: 'VARIABLE_AMOUNT',
    VARIABLE_PERCENTAGE: 'VARIABLE_PERCENTAGE',
} as const;
