/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGiftCards201GiftCardCode } from './postApiGiftCards201GiftCardCode';
import type { PostApiGiftCards201RecipientName } from './postApiGiftCards201RecipientName';
import type { PostApiGiftCards201Status } from './postApiGiftCards201Status';
import type { PostApiGiftCards201ExpiryDate } from './postApiGiftCards201ExpiryDate';
import type { PostApiGiftCards201PersonalMessage } from './postApiGiftCards201PersonalMessage';
import type { PostApiGiftCards201SoldBy } from './postApiGiftCards201SoldBy';
import type { PostApiGiftCards201Note } from './postApiGiftCards201Note';
import type { PostApiGiftCards201CustomerId } from './postApiGiftCards201CustomerId';
import type { PostApiGiftCards201GiftCardOnlineId } from './postApiGiftCards201GiftCardOnlineId';

export type PostApiGiftCards201 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    giftCardCode: PostApiGiftCards201GiftCardCode;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    originalValue: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    residueValue: number;
    recipientName: PostApiGiftCards201RecipientName;
    status: PostApiGiftCards201Status;
    applicableServiceIds?: string[];
    expiryDate: PostApiGiftCards201ExpiryDate;
    taxIds?: string[];
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    taxAmount: number;
    personalMessage: PostApiGiftCards201PersonalMessage;
    soldBy: PostApiGiftCards201SoldBy;
    createdAt: string;
    note: PostApiGiftCards201Note;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    sourceId: number;
    customerId: PostApiGiftCards201CustomerId;
    giftCardOnlineId: PostApiGiftCards201GiftCardOnlineId;
    updatedAt: string;
};
