/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataSalesTaxesItemTaxId } from './postApiCreateSalesOnline201DataSalesTaxesItemTaxId';
import type { PostApiCreateSalesOnline201DataSalesTaxesItemTaxName } from './postApiCreateSalesOnline201DataSalesTaxesItemTaxName';

export type PostApiCreateSalesOnline201DataSalesTaxesItem = {
    taxId?: PostApiCreateSalesOnline201DataSalesTaxesItemTaxId;
    taxName?: PostApiCreateSalesOnline201DataSalesTaxesItemTaxName;
    taxRate?: number;
    taxAmount?: number;
    includeTaxInItemPrice?: boolean;
    isInclusive?: boolean;
};
