/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiDoctorsPortalInviteDoctorUuid400Error =
    (typeof PostApiDoctorsPortalInviteDoctorUuid400Error)[keyof typeof PostApiDoctorsPortalInviteDoctorUuid400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiDoctorsPortalInviteDoctorUuid400Error = {
    Bad_Request: 'Bad Request',
} as const;
