/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMobilepayCreateMobilepayOrder500Error =
    (typeof PostApiMobilepayCreateMobilepayOrder500Error)[keyof typeof PostApiMobilepayCreateMobilepayOrder500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiMobilepayCreateMobilepayOrder500Error = {
    Bad_Request: 'Bad Request',
} as const;
