/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiIotDevices201Status = (typeof PostApiIotDevices201Status)[keyof typeof PostApiIotDevices201Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiIotDevices201Status = {
    CONNECTED: 'CONNECTED',
    DISCONNECTED: 'DISCONNECTED',
} as const;
