/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiItemTax201ProductId } from './postApiItemTax201ProductId';
import type { PostApiItemTax201ServiceId } from './postApiItemTax201ServiceId';
import type { PostApiItemTax201TaxId } from './postApiItemTax201TaxId';
import type { PostApiItemTax201CreatedAt } from './postApiItemTax201CreatedAt';
import type { PostApiItemTax201UpdatedAt } from './postApiItemTax201UpdatedAt';

export type PostApiItemTax201 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    productId: PostApiItemTax201ProductId;
    serviceId: PostApiItemTax201ServiceId;
    taxId: PostApiItemTax201TaxId;
    createdAt: PostApiItemTax201CreatedAt;
    updatedAt: PostApiItemTax201UpdatedAt;
};
