/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid400Error } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid400Error';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid400 = {
    statusCode: number;
    error: PostApiHealthDeclarationsGroupBookingGroupBookingUuid400Error;
    message: string;
};
