/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGiftCardsIdUse200HistoryItemInvoiceNumber } from './postApiGiftCardsIdUse200HistoryItemInvoiceNumber';

export type PostApiGiftCardsIdUse200HistoryItem = {
    salesId: string;
    invoiceNumber: PostApiGiftCardsIdUse200HistoryItemInvoiceNumber;
    amountUsed: number;
    dateTime: string;
};
