/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Array of campaign IDs (e.g., ["id1", "id2", "id3"]) or null for all campaigns
 */
export type PostApiCampaignsStatisticsBodyCampaignId = string[] | null;
