/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSendSalesEmail400Error =
    (typeof PostApiSendSalesEmail400Error)[keyof typeof PostApiSendSalesEmail400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSendSalesEmail400Error = {
    Bad_Request: 'Bad Request',
} as const;
