/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemSalesId } from './postApiCreateSalesOnline201DataSalesDiscountsItemSalesId';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemDiscountId } from './postApiCreateSalesOnline201DataSalesDiscountsItemDiscountId';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemCouponId } from './postApiCreateSalesOnline201DataSalesDiscountsItemCouponId';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemDiscountName } from './postApiCreateSalesOnline201DataSalesDiscountsItemDiscountName';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemDiscountAmount } from './postApiCreateSalesOnline201DataSalesDiscountsItemDiscountAmount';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemAmountType } from './postApiCreateSalesOnline201DataSalesDiscountsItemAmountType';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemAmount } from './postApiCreateSalesOnline201DataSalesDiscountsItemAmount';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemCreatedAt } from './postApiCreateSalesOnline201DataSalesDiscountsItemCreatedAt';
import type { PostApiCreateSalesOnline201DataSalesDiscountsItemUpdatedAt } from './postApiCreateSalesOnline201DataSalesDiscountsItemUpdatedAt';

export type PostApiCreateSalesOnline201DataSalesDiscountsItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesId: PostApiCreateSalesOnline201DataSalesDiscountsItemSalesId;
    discountId: PostApiCreateSalesOnline201DataSalesDiscountsItemDiscountId;
    couponId: PostApiCreateSalesOnline201DataSalesDiscountsItemCouponId;
    discountName: PostApiCreateSalesOnline201DataSalesDiscountsItemDiscountName;
    discountAmount: PostApiCreateSalesOnline201DataSalesDiscountsItemDiscountAmount;
    amountType: PostApiCreateSalesOnline201DataSalesDiscountsItemAmountType;
    amount: PostApiCreateSalesOnline201DataSalesDiscountsItemAmount;
    createdAt: PostApiCreateSalesOnline201DataSalesDiscountsItemCreatedAt;
    updatedAt: PostApiCreateSalesOnline201DataSalesDiscountsItemUpdatedAt;
};
