/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPublicHealthDeclarationsSubmit400Error } from './postApiPublicHealthDeclarationsSubmit400Error';

export type PostApiPublicHealthDeclarationsSubmit400 = {
    statusCode: number;
    error: PostApiPublicHealthDeclarationsSubmit400Error;
    message: string;
};
