/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiItemTaxBodyProductId } from './postApiItemTaxBodyProductId';
import type { PostApiItemTaxBodyServiceId } from './postApiItemTaxBodyServiceId';
import type { PostApiItemTaxBodyTaxId } from './postApiItemTaxBodyTaxId';

export type PostApiItemTaxBody = {
    productId?: PostApiItemTaxBodyProductId;
    serviceId?: PostApiItemTaxBodyServiceId;
    taxId?: PostApiItemTaxBodyTaxId;
    /** @minLength 1 */
    name: string;
};
