/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSaleBodyDataItemsItemGiftCardAnyOf } from './postApiSaleBodyDataItemsItemGiftCardAnyOf';

export type PostApiSaleBodyDataItemsItemGiftCard = PostApiSaleBodyDataItemsItemGiftCardAnyOf | null;
