/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSaleBodyDataSalesDiscountsItemDiscountId } from './postApiSaleBodyDataSalesDiscountsItemDiscountId';
import type { PostApiSaleBodyDataSalesDiscountsItemCouponId } from './postApiSaleBodyDataSalesDiscountsItemCouponId';
import type { PostApiSaleBodyDataSalesDiscountsItemDiscountName } from './postApiSaleBodyDataSalesDiscountsItemDiscountName';
import type { PostApiSaleBodyDataSalesDiscountsItemAmountType } from './postApiSaleBodyDataSalesDiscountsItemAmountType';

export type PostApiSaleBodyDataSalesDiscountsItem = {
    discountId?: PostApiSaleBodyDataSalesDiscountsItemDiscountId;
    couponId?: PostApiSaleBodyDataSalesDiscountsItemCouponId;
    discountName?: PostApiSaleBodyDataSalesDiscountsItemDiscountName;
    discountAmount?: number;
    amountType?: PostApiSaleBodyDataSalesDiscountsItemAmountType;
    amount?: number;
};
