/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPublicHealthDeclarationsSubmit500Error =
    (typeof PostApiPublicHealthDeclarationsSubmit500Error)[keyof typeof PostApiPublicHealthDeclarationsSubmit500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPublicHealthDeclarationsSubmit500Error = {
    Bad_Request: 'Bad Request',
} as const;
