/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationTemplates201DataDescription } from './postApiHealthDeclarationTemplates201DataDescription';
import type { PostApiHealthDeclarationTemplates201DataContent } from './postApiHealthDeclarationTemplates201DataContent';

export type PostApiHealthDeclarationTemplates201Data = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    description: PostApiHealthDeclarationTemplates201DataDescription;
    content?: PostApiHealthDeclarationTemplates201DataContent;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    createdAt: string;
    updatedAt: string;
};
