/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMobilepayCreateMobilepayOrder201DataItem } from './postApiMobilepayCreateMobilepayOrder201DataItem';

export type PostApiMobilepayCreateMobilepayOrder201 = {
    success: boolean;
    data: PostApiMobilepayCreateMobilepayOrder201DataItem[];
};
