/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiHealthDeclarationBookingBookingIdSendEmail400Error =
    (typeof PostApiHealthDeclarationBookingBookingIdSendEmail400Error)[keyof typeof PostApiHealthDeclarationBookingBookingIdSendEmail400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiHealthDeclarationBookingBookingIdSendEmail400Error = {
    Bad_Request: 'Bad Request',
} as const;
