/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiExpense400Error = (typeof PostApiExpense400Error)[keyof typeof PostApiExpense400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiExpense400Error = {
    Bad_Request: 'Bad Request',
} as const;
