/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSaleBodyDataPaymentItemBunddleOfferServicesItem } from './postApiSaleBodyDataPaymentItemBunddleOfferServicesItem';

export type PostApiSaleBodyDataPaymentItemBunddleOffer = {
    bundleOfferId: string;
    services: PostApiSaleBodyDataPaymentItemBunddleOfferServicesItem[];
};
