/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCodeAnyOf } from './postApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCodeAnyOf';

export type PostApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCode =
    PostApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCodeAnyOf | null;
