/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiCustomerGroups500Error =
    (typeof PostApiCustomerGroups500Error)[keyof typeof PostApiCustomerGroups500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiCustomerGroups500Error = {
    Bad_Request: 'Bad Request',
} as const;
