/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiKlaviyoSyncCustomer200Data } from './postApiKlaviyoSyncCustomer200Data';

export type PostApiKlaviyoSyncCustomer200 = {
    success: boolean;
    message: string;
    data?: PostApiKlaviyoSyncCustomer200Data;
    error?: string;
};
