/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSendSalesEmail500Error =
    (typeof PostApiSendSalesEmail500Error)[keyof typeof PostApiSendSalesEmail500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSendSalesEmail500Error = {
    Bad_Request: 'Bad Request',
} as const;
