/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBundleOffers201ApplicableService } from './postApiBundleOffers201ApplicableService';
import type { PostApiBundleOffers201BundleOfferType } from './postApiBundleOffers201BundleOfferType';

export type PostApiBundleOffers201 = {
    id: string;
    seqId: number;
    outletId: number;
    name: string;
    /** @nullable */
    description: string | null;
    /** Services on which bundle offer can be applied */
    applicableService: PostApiBundleOffers201ApplicableService;
    bundleOfferType: PostApiBundleOffers201BundleOfferType;
    price: number;
    expiryMonths: number;
    createdAt: string;
    updatedAt: string;
    /** @nullable */
    deletedAt: string | null;
};
