/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid500Error } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid500Error';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid500 = {
    statusCode: number;
    error: PostApiHealthDeclarationsGroupBookingGroupBookingUuid500Error;
    message: string;
};
