/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSaleBodyDataSalesTaxesItemTaxId } from './postApiSaleBodyDataSalesTaxesItemTaxId';
import type { PostApiSaleBodyDataSalesTaxesItemTaxName } from './postApiSaleBodyDataSalesTaxesItemTaxName';

export type PostApiSaleBodyDataSalesTaxesItem = {
    taxId?: PostApiSaleBodyDataSalesTaxesItemTaxId;
    taxName?: PostApiSaleBodyDataSalesTaxesItemTaxName;
    taxRate?: number;
    taxAmount?: number;
    includeTaxInItemPrice?: boolean;
    isInclusive?: boolean;
};
