/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOf } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOf';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedBy =
    PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedByAnyOf | null;
