/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiExpense400Error } from './postApiExpense400Error';

export type PostApiExpense400 = {
    statusCode: number;
    error: PostApiExpense400Error;
    message: string;
};
