/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiDoctorsPortalInviteDoctorUuid500Error =
    (typeof PostApiDoctorsPortalInviteDoctorUuid500Error)[keyof typeof PostApiDoctorsPortalInviteDoctorUuid500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiDoctorsPortalInviteDoctorUuid500Error = {
    Bad_Request: 'Bad Request',
} as const;
