/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPaymentsSubscriptionPay400Error =
    (typeof PostApiPaymentsSubscriptionPay400Error)[keyof typeof PostApiPaymentsSubscriptionPay400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPaymentsSubscriptionPay400Error = {
    Bad_Request: 'Bad Request',
} as const;
