/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiGoogleCalendarSyncHolidaysBody = {
    /** Optional. Omit to sync all holidays for the outlet */
    holidayId?: number;
};
