/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid404Error =
    (typeof PostApiHealthDeclarationsGroupBookingGroupBookingUuid404Error)[keyof typeof PostApiHealthDeclarationsGroupBookingGroupBookingUuid404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiHealthDeclarationsGroupBookingGroupBookingUuid404Error = {
    Bad_Request: 'Bad Request',
} as const;
