/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPublicHealthDeclarationsSubmit200Data } from './postApiPublicHealthDeclarationsSubmit200Data';

export type PostApiPublicHealthDeclarationsSubmit200 = {
    statusCode: number;
    message: string;
    success: boolean;
    data: PostApiPublicHealthDeclarationsSubmit200Data;
};
