/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGatewayapiWebhookCampaignId404Error } from './postApiGatewayapiWebhookCampaignId404Error';

export type PostApiGatewayapiWebhookCampaignId404 = {
    statusCode: number;
    error: PostApiGatewayapiWebhookCampaignId404Error;
    message: string;
};
