/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiIotValidateTokenBody = {
    /**
     * Outlet phone number
     * @minLength 1
     */
    phoneNumber: string;
    /**
     * IoT API key
     * @minLength 1
     */
    apiKey: string;
    /**
     * Device MAC address
     * @minLength 1
     */
    macAddress: string;
};
