/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiWebhooks201Secret } from './postApiWebhooks201Secret';

export type PostApiWebhooks201 = {
    id: number;
    outletId: number;
    event: string;
    webhookUrl: string;
    secret?: PostApiWebhooks201Secret;
    active: boolean;
};
