/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiStock500Error } from './postApiStock500Error';

export type PostApiStock500 = {
    statusCode: number;
    error: PostApiStock500Error;
    message: string;
};
