/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationBookingBookingIdSendEmail400Error } from './postApiHealthDeclarationBookingBookingIdSendEmail400Error';

export type PostApiHealthDeclarationBookingBookingIdSendEmail400 = {
    statusCode: number;
    error: PostApiHealthDeclarationBookingBookingIdSendEmail400Error;
    message: string;
};
