/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnline201DataItemsItemTaxesItemTaxId } from './postApiCreateSalesOnline201DataItemsItemTaxesItemTaxId';
import type { PostApiCreateSalesOnline201DataItemsItemTaxesItemCreatedBy } from './postApiCreateSalesOnline201DataItemsItemTaxesItemCreatedBy';
import type { PostApiCreateSalesOnline201DataItemsItemTaxesItemUpdatedBy } from './postApiCreateSalesOnline201DataItemsItemTaxesItemUpdatedBy';

export type PostApiCreateSalesOnline201DataItemsItemTaxesItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesDetailId: string;
    TaxId: PostApiCreateSalesOnline201DataItemsItemTaxesItemTaxId;
    includeTaxInItemPrice: boolean;
    createdBy: PostApiCreateSalesOnline201DataItemsItemTaxesItemCreatedBy;
    updatedBy: PostApiCreateSalesOnline201DataItemsItemTaxesItemUpdatedBy;
    createdAt: string;
    updatedAt: string;
};
