/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemRequestContent } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemRequestContent';
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResponseContent } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResponseContent';
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedBy } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedBy';
import type { PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendBy } from './postApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendBy';

export type PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItem = {
    id?: string;
    seqId?: number;
    status?: string;
    bookingId?: number;
    templateId?: string;
    requestContent?: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemRequestContent;
    /** @nullable */
    responseContent?: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResponseContent;
    outletId?: number;
    reviewedBy?: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemReviewedBy;
    /** @nullable */
    reviewedAt?: string | null;
    resendBy?: PostApiHealthDeclarationsGroupBookingGroupBookingUuid201DataItemResendBy;
    /** @nullable */
    resendAt?: string | null;
    /** @nullable */
    submittedAt?: string | null;
    /** @nullable */
    outletCustomerId?: number | null;
    createdAt?: string;
    updatedAt?: string;
    /** @nullable */
    deletedAt?: string | null;
};
