/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCode } from './postApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCode';

export type PostApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOf = {
    /** @maxLength 256 */
    recipientName?: string;
    giftCardCode?: PostApiCreateSalesOnlineBodyDataItemsItemGiftCardAnyOfGiftCardCode;
    /**
     * @minimum 1
     */
    amount?: number;
    applicableServiceIds?: string[];
};
