/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPaymentsSubscriptionPay500Error } from './postApiPaymentsSubscriptionPay500Error';

export type PostApiPaymentsSubscriptionPay500 = {
    statusCode: number;
    error: PostApiPaymentsSubscriptionPay500Error;
    message: string;
};
