/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiGiftCardsIdUse200CustomerAnyOf } from './postApiGiftCardsIdUse200CustomerAnyOf';

export type PostApiGiftCardsIdUse200Customer = PostApiGiftCardsIdUse200CustomerAnyOf | null;
