/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSaleBodyDataItemsItemDiscountsItemDiscountId } from './postApiSaleBodyDataItemsItemDiscountsItemDiscountId';
import type { PostApiSaleBodyDataItemsItemDiscountsItemCouponId } from './postApiSaleBodyDataItemsItemDiscountsItemCouponId';
import type { PostApiSaleBodyDataItemsItemDiscountsItemDiscountName } from './postApiSaleBodyDataItemsItemDiscountsItemDiscountName';
import type { PostApiSaleBodyDataItemsItemDiscountsItemAmountType } from './postApiSaleBodyDataItemsItemDiscountsItemAmountType';

export type PostApiSaleBodyDataItemsItemDiscountsItem = {
    discountId?: PostApiSaleBodyDataItemsItemDiscountsItemDiscountId;
    couponId?: PostApiSaleBodyDataItemsItemDiscountsItemCouponId;
    discountName?: PostApiSaleBodyDataItemsItemDiscountsItemDiscountName;
    discountAmount?: number;
    amountType?: PostApiSaleBodyDataItemsItemDiscountsItemAmountType;
    amount?: number;
};
