/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Name of the addon to upsert (e.g., "dinero", "economic", "billy")
 */
export type PostApiAddonsUpsertBodyAddonName =
    (typeof PostApiAddonsUpsertBodyAddonName)[keyof typeof PostApiAddonsUpsertBodyAddonName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAddonsUpsertBodyAddonName = {
    dinero: 'dinero',
    economic: 'economic',
    billy: 'billy',
} as const;
