/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPaymentsSubscriptionStart400Error =
    (typeof PostApiPaymentsSubscriptionStart400Error)[keyof typeof PostApiPaymentsSubscriptionStart400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiPaymentsSubscriptionStart400Error = {
    Bad_Request: 'Bad Request',
} as const;
