/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCashDrawerClose200DataCashDrawerId } from './postApiCashDrawerClose200DataCashDrawerId';
import type { PostApiCashDrawerClose200DataLastCashDrawerEndDate } from './postApiCashDrawerClose200DataLastCashDrawerEndDate';
import type { PostApiCashDrawerClose200DataDrawerName } from './postApiCashDrawerClose200DataDrawerName';
import type { PostApiCashDrawerClose200DataDrawerStatus } from './postApiCashDrawerClose200DataDrawerStatus';
import type { PostApiCashDrawerClose200DataDrawerStartDate } from './postApiCashDrawerClose200DataDrawerStartDate';
import type { PostApiCashDrawerClose200DataDrawerEndDate } from './postApiCashDrawerClose200DataDrawerEndDate';
import type { PostApiCashDrawerClose200DataPaymentBreakdown } from './postApiCashDrawerClose200DataPaymentBreakdown';
import type { PostApiCashDrawerClose200DataSalesBreakdown } from './postApiCashDrawerClose200DataSalesBreakdown';
import type { PostApiCashDrawerClose200DataCreditBreakdown } from './postApiCashDrawerClose200DataCreditBreakdown';
import type { PostApiCashDrawerClose200DataDetailedPaymentBreakdownItem } from './postApiCashDrawerClose200DataDetailedPaymentBreakdownItem';

export type PostApiCashDrawerClose200Data = {
    outletId: number;
    cashDrawerId: PostApiCashDrawerClose200DataCashDrawerId;
    fromDate: string;
    toDate: string;
    totalSales: number;
    totalTenderAmount: number;
    openingCash: number;
    closingCash: number;
    lastCashDrawerEndDate: PostApiCashDrawerClose200DataLastCashDrawerEndDate;
    drawerName: PostApiCashDrawerClose200DataDrawerName;
    drawerStatus: PostApiCashDrawerClose200DataDrawerStatus;
    drawerStartDate: PostApiCashDrawerClose200DataDrawerStartDate;
    drawerEndDate: PostApiCashDrawerClose200DataDrawerEndDate;
    paymentBreakdown: PostApiCashDrawerClose200DataPaymentBreakdown;
    salesBreakdown: PostApiCashDrawerClose200DataSalesBreakdown;
    creditBreakdown: PostApiCashDrawerClose200DataCreditBreakdown;
    detailedPaymentBreakdown?: PostApiCashDrawerClose200DataDetailedPaymentBreakdownItem[];
};
