/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiGiftCardsSettingsBodyPredefinedAmountsItem = {
    /**
     * The amount value
     * @minimum 0.01
     */
    value: number;
    /** Whether this amount is available for online purchase */
    onlineAvailable: boolean;
};
