/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiWebhooksId200Secret } from './putApiWebhooksId200Secret';

export type PutApiWebhooksId200 = {
    id: number;
    outletId: number;
    event: string;
    webhookUrl: string;
    secret?: PutApiWebhooksId200Secret;
    active: boolean;
};
