/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Spam period in hours before sending any campaign to same customer again. Optional.
 */
export type PutApiCampaignsIdBodyScheduleSpamPeriod = number | null;
