/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiUpdateProducts200ItemCostPriceAnyOf } from './putApiUpdateProducts200ItemCostPriceAnyOf';

export type PutApiUpdateProducts200ItemCostPrice = PutApiUpdateProducts200ItemCostPriceAnyOf | null;
