/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiExpenseId400Error } from './putApiExpenseId400Error';

export type PutApiExpenseId400 = {
    statusCode: number;
    error: PutApiExpenseId400Error;
    message: string;
};
