/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiIotDevicesDeviceId200Status } from './putApiIotDevicesDeviceId200Status';

export type PutApiIotDevicesDeviceId200 = {
    id?: string;
    outletId?: number;
    deviceType?: string;
    deviceMAC?: string;
    apiKey?: string;
    status?: PutApiIotDevicesDeviceId200Status;
    createdAt?: string;
    updatedAt?: string;
};
