/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiProductId500Error } from './putApiProductId500Error';

export type PutApiProductId500 = {
    statusCode: number;
    error: PutApiProductId500Error;
    message: string;
};
