/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiSupplierId500Error } from './putApiSupplierId500Error';

export type PutApiSupplierId500 = {
    statusCode: number;
    error: PutApiSupplierId500Error;
    message: string;
};
