/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId200DataReviewedByAnyOf } from './putApiHealthDeclarationId200DataReviewedByAnyOf';

/**
 * @nullable
 */
export type PutApiHealthDeclarationId200DataReviewedBy = null | PutApiHealthDeclarationId200DataReviewedByAnyOf | null;
