/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiCampaignsId200Description } from './putApiCampaignsId200Description';

export type PutApiCampaignsId200 = {
    id?: string;
    outletId?: number;
    name?: string;
    description?: PutApiCampaignsId200Description;
    messageType?: string;
    campaignType?: string;
    campaignStatus?: string;
    createdAt?: string;
    updatedAt?: string;
    /** Number of recipients for this campaign */
    recipientCount?: number;
};
