/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiCampaignsIdBodyMessageType =
    (typeof PutApiCampaignsIdBodyMessageType)[keyof typeof PutApiCampaignsIdBodyMessageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiCampaignsIdBodyMessageType = {
    EMAIL: 'EMAIL',
    SMS: 'SMS',
} as const;
