/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesIdBodyDataPaymentItemPaymentId } from './putApiEditSalesIdBodyDataPaymentItemPaymentId';
import type { PutApiEditSalesIdBodyDataPaymentItemTxStatus } from './putApiEditSalesIdBodyDataPaymentItemTxStatus';
import type { PutApiEditSalesIdBodyDataPaymentItemTerminalId } from './putApiEditSalesIdBodyDataPaymentItemTerminalId';
import type { PutApiEditSalesIdBodyDataPaymentItemTerminalRefId } from './putApiEditSalesIdBodyDataPaymentItemTerminalRefId';
import type { PutApiEditSalesIdBodyDataPaymentItemTerminalStatus } from './putApiEditSalesIdBodyDataPaymentItemTerminalStatus';
import type { PutApiEditSalesIdBodyDataPaymentItemCardType } from './putApiEditSalesIdBodyDataPaymentItemCardType';
import type { PutApiEditSalesIdBodyDataPaymentItemCardFourDigit } from './putApiEditSalesIdBodyDataPaymentItemCardFourDigit';
import type { PutApiEditSalesIdBodyDataPaymentItemPaymentType } from './putApiEditSalesIdBodyDataPaymentItemPaymentType';
import type { PutApiEditSalesIdBodyDataPaymentItemBunddleOffer } from './putApiEditSalesIdBodyDataPaymentItemBunddleOffer';

export type PutApiEditSalesIdBodyDataPaymentItem = {
    paymentId?: PutApiEditSalesIdBodyDataPaymentItemPaymentId;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    tenderAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    change?: number;
    txStatus?: PutApiEditSalesIdBodyDataPaymentItemTxStatus;
    terminalId?: PutApiEditSalesIdBodyDataPaymentItemTerminalId;
    terminalRefId?: PutApiEditSalesIdBodyDataPaymentItemTerminalRefId;
    terminalStatus?: PutApiEditSalesIdBodyDataPaymentItemTerminalStatus;
    cardType?: PutApiEditSalesIdBodyDataPaymentItemCardType;
    cardFourDigit?: PutApiEditSalesIdBodyDataPaymentItemCardFourDigit;
    paymentType?: PutApiEditSalesIdBodyDataPaymentItemPaymentType;
    terminalResponse?: string;
    currency?: string;
    giftCardId?: string;
    bunddleOffer?: PutApiEditSalesIdBodyDataPaymentItemBunddleOffer;
};
