/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiExpenseId404Error = (typeof PutApiExpenseId404Error)[keyof typeof PutApiExpenseId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiExpenseId404Error = {
    Bad_Request: 'Bad Request',
} as const;
