/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiCustomerGroupsId404Error } from './putApiCustomerGroupsId404Error';

export type PutApiCustomerGroupsId404 = {
    statusCode: number;
    error: PutApiCustomerGroupsId404Error;
    message: string;
};
