/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesIdBodyDataItemsItemTaxesItemTaxId } from './putApiEditSalesIdBodyDataItemsItemTaxesItemTaxId';
import type { PutApiEditSalesIdBodyDataItemsItemTaxesItemTaxName } from './putApiEditSalesIdBodyDataItemsItemTaxesItemTaxName';

export type PutApiEditSalesIdBodyDataItemsItemTaxesItem = {
    taxId?: PutApiEditSalesIdBodyDataItemsItemTaxesItemTaxId;
    taxName?: PutApiEditSalesIdBodyDataItemsItemTaxesItemTaxName;
    taxRate?: number;
    taxAmount?: number;
    includeTaxInItemPrice?: boolean;
    isInclusive?: boolean;
};
