/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiWebhooksId500Error } from './putApiWebhooksId500Error';

export type PutApiWebhooksId500 = {
    statusCode: number;
    error: PutApiWebhooksId500Error;
    message: string;
};
