/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiServicesEmployeeAssignEmployeeId404Error =
    (typeof PutApiServicesEmployeeAssignEmployeeId404Error)[keyof typeof PutApiServicesEmployeeAssignEmployeeId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiServicesEmployeeAssignEmployeeId404Error = {
    Bad_Request: 'Bad Request',
} as const;
