/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiExpenseId200CashDrawerId } from './putApiExpenseId200CashDrawerId';
import type { PutApiExpenseId200Description } from './putApiExpenseId200Description';
import type { PutApiExpenseId200CreatedAt } from './putApiExpenseId200CreatedAt';
import type { PutApiExpenseId200ExpenseCategory } from './putApiExpenseId200ExpenseCategory';
import type { PutApiExpenseId200Employee } from './putApiExpenseId200Employee';

export type PutApiExpenseId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    cashDrawerId?: PutApiExpenseId200CashDrawerId;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    amount: number;
    description: PutApiExpenseId200Description;
    createdAt: PutApiExpenseId200CreatedAt;
    updatedAt: string;
    expenseCategory: PutApiExpenseId200ExpenseCategory;
    employee: PutApiExpenseId200Employee;
};
