/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiDiscountId200Amount } from './putApiDiscountId200Amount';
import type { PutApiDiscountId200OptionMaxDiscountValue } from './putApiDiscountId200OptionMaxDiscountValue';
import type { PutApiDiscountId200CouponId } from './putApiDiscountId200CouponId';
import type { PutApiDiscountId200OutletId } from './putApiDiscountId200OutletId';
import type { PutApiDiscountId200AmountType } from './putApiDiscountId200AmountType';
import type { PutApiDiscountId200CreatedBy } from './putApiDiscountId200CreatedBy';
import type { PutApiDiscountId200UpdatedBy } from './putApiDiscountId200UpdatedBy';
import type { PutApiDiscountId200CreatedAt } from './putApiDiscountId200CreatedAt';
import type { PutApiDiscountId200UpdatedAt } from './putApiDiscountId200UpdatedAt';

export type PutApiDiscountId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    amount: PutApiDiscountId200Amount;
    optionMaxDiscountValue: PutApiDiscountId200OptionMaxDiscountValue;
    couponId: PutApiDiscountId200CouponId;
    outletId: PutApiDiscountId200OutletId;
    amountType: PutApiDiscountId200AmountType;
    createdBy: PutApiDiscountId200CreatedBy;
    updatedBy: PutApiDiscountId200UpdatedBy;
    createdAt: PutApiDiscountId200CreatedAt;
    updatedAt: PutApiDiscountId200UpdatedAt;
};
