/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiServicesEmployeeAssignEmployeeId400Error } from './putApiServicesEmployeeAssignEmployeeId400Error';

export type PutApiServicesEmployeeAssignEmployeeId400 = {
    statusCode: number;
    error: PutApiServicesEmployeeAssignEmployeeId400Error;
    message: string;
};
