/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiServicesEmployeeAssignEmployeeId404Error } from './putApiServicesEmployeeAssignEmployeeId404Error';

export type PutApiServicesEmployeeAssignEmployeeId404 = {
    statusCode: number;
    error: PutApiServicesEmployeeAssignEmployeeId404Error;
    message: string;
};
