/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiPaymentsSubscriptionEdit400Error } from './putApiPaymentsSubscriptionEdit400Error';

export type PutApiPaymentsSubscriptionEdit400 = {
    statusCode: number;
    error: PutApiPaymentsSubscriptionEdit400Error;
    message: string;
};
