/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiExpenseId500Error } from './putApiExpenseId500Error';

export type PutApiExpenseId500 = {
    statusCode: number;
    error: PutApiExpenseId500Error;
    message: string;
};
