/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId200DataParentId } from './putApiEditSalesId200DataParentId';
import type { PutApiEditSalesId200DataCustomerId } from './putApiEditSalesId200DataCustomerId';
import type { PutApiEditSalesId200DataVoidId } from './putApiEditSalesId200DataVoidId';
import type { PutApiEditSalesId200DataSyncedWith } from './putApiEditSalesId200DataSyncedWith';
import type { PutApiEditSalesId200DataSyncId } from './putApiEditSalesId200DataSyncId';
import type { PutApiEditSalesId200DataDeletedAt } from './putApiEditSalesId200DataDeletedAt';
import type { PutApiEditSalesId200DataItemsItem } from './putApiEditSalesId200DataItemsItem';
import type { PutApiEditSalesId200DataSalesTaxesItem } from './putApiEditSalesId200DataSalesTaxesItem';
import type { PutApiEditSalesId200DataSalesDiscountsItem } from './putApiEditSalesId200DataSalesDiscountsItem';
import type { PutApiEditSalesId200DataPaymentItem } from './putApiEditSalesId200DataPaymentItem';

export type PutApiEditSalesId200Data = {
    id?: string;
    seqId?: number;
    invAutoNumber?: number;
    salesDate?: string;
    invoiceId?: string;
    shortInvoiceId?: string;
    parentId?: PutApiEditSalesId200DataParentId;
    outletId?: number;
    customerId?: PutApiEditSalesId200DataCustomerId;
    customerName?: string;
    subTotal?: number;
    totalTax?: number;
    totalDiscount?: number;
    netTotal?: number;
    tenderAmount?: number;
    change?: number;
    roundOff?: number;
    tips?: number;
    salesNote?: string;
    voidId?: PutApiEditSalesId200DataVoidId;
    salesType?: string;
    createdBy?: number;
    updatedBy?: number;
    sellBy?: number;
    sourceId?: number;
    syncedWith?: PutApiEditSalesId200DataSyncedWith;
    syncId?: PutApiEditSalesId200DataSyncId;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: PutApiEditSalesId200DataDeletedAt;
    items: PutApiEditSalesId200DataItemsItem[];
    salesTaxes: PutApiEditSalesId200DataSalesTaxesItem[];
    salesDiscounts: PutApiEditSalesId200DataSalesDiscountsItem[];
    payment: PutApiEditSalesId200DataPaymentItem[];
};
