/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiDineroConfigBodyCoaConfiguration } from './putApiDineroConfigBodyCoaConfiguration';

export type PutApiDineroConfigBody = {
    /** Organization ID */
    organizationId: string;
    /** Chart of Accounts configuration */
    coaConfiguration: PutApiDineroConfigBodyCoaConfiguration;
    /** Whether to send emails from Dinero */
    sendEmailFromDinero: boolean;
};
