/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiWebhooksId404Error } from './putApiWebhooksId404Error';

export type PutApiWebhooksId404 = {
    statusCode: number;
    error: PutApiWebhooksId404Error;
    message: string;
};
