/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiEconomicConfigBodyCoaConfigurationPRODUCTGROUP = {
    PRODUCT_WITH_VAT: number;
    SERVICE_WITH_VAT: number;
    PRODCUT_WITHOUT_VAT: number;
    SERVICE_WITHOUT_VAT: number;
};
