/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationTemplateIdBodyDescription } from './putApiHealthDeclarationTemplateIdBodyDescription';

export type PutApiHealthDeclarationTemplateIdBody = {
    /** @minLength 1 */
    name?: string;
    description?: PutApiHealthDeclarationTemplateIdBodyDescription;
    content?: unknown;
};
