/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiProductCategoriesId400Error =
    (typeof PutApiProductCategoriesId400Error)[keyof typeof PutApiProductCategoriesId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiProductCategoriesId400Error = {
    Bad_Request: 'Bad Request',
} as const;
