/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId500Error } from './putApiHealthDeclarationId500Error';

export type PutApiHealthDeclarationId500 = {
    statusCode: number;
    error: PutApiHealthDeclarationId500Error;
    message: string;
};
