/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiProductId200Description } from './putApiProductId200Description';
import type { PutApiProductId200Image } from './putApiProductId200Image';
import type { PutApiProductId200Sku } from './putApiProductId200Sku';
import type { PutApiProductId200CategoryId } from './putApiProductId200CategoryId';
import type { PutApiProductId200SupplierId } from './putApiProductId200SupplierId';
import type { PutApiProductId200Brand } from './putApiProductId200Brand';
import type { PutApiProductId200OutletId } from './putApiProductId200OutletId';

export type PutApiProductId200 = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    description: PutApiProductId200Description;
    image: PutApiProductId200Image;
    sku: PutApiProductId200Sku;
    categoryId: PutApiProductId200CategoryId;
    supplierId: PutApiProductId200SupplierId;
    brand: PutApiProductId200Brand;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    price: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    costPrice: number;
    isActive: boolean;
    availableOnline: boolean;
    outletId: PutApiProductId200OutletId;
    createdAt: string;
    updatedAt: string;
};
