/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiCampaignsCampaignIdStatisticsRecipientsBody = {
    /** Array of outlet customer IDs. Recipients not in this list will be marked as SKIPPED. */
    recipients: number[];
};
