/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiCampaignsCampaignIdStatisticsRecipients200 = {
    success: boolean;
    message: string;
    /** Number of recipients added */
    added: number;
    /** Number of recipients marked as SKIPPED */
    removed: number;
};
