/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiPaymentsSubscriptionEditBodyStatus } from './putApiPaymentsSubscriptionEditBodyStatus';
import type { PutApiPaymentsSubscriptionEditBodyAmount } from './putApiPaymentsSubscriptionEditBodyAmount';

export type PutApiPaymentsSubscriptionEditBody = {
    /** The subscription ID to edit */
    subscriptionId: string;
    /** The new status for the subscription */
    status?: PutApiPaymentsSubscriptionEditBodyStatus;
    /** The new amount for the subscription */
    amount?: PutApiPaymentsSubscriptionEditBodyAmount;
    /**
     * The new duration in months for the subscription
     * @minimum 1
     */
    durationMonths?: number;
};
