/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiCampaignsIdBodyContentContentType =
    (typeof PutApiCampaignsIdBodyContentContentType)[keyof typeof PutApiCampaignsIdBodyContentContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiCampaignsIdBodyContentContentType = {
    SMS: 'SMS',
    EMAIL: 'EMAIL',
} as const;
