/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiUpdateProducts200ItemSku } from './putApiUpdateProducts200ItemSku';
import type { PutApiUpdateProducts200ItemCategoryId } from './putApiUpdateProducts200ItemCategoryId';
import type { PutApiUpdateProducts200ItemPrice } from './putApiUpdateProducts200ItemPrice';
import type { PutApiUpdateProducts200ItemCostPrice } from './putApiUpdateProducts200ItemCostPrice';

export type PutApiUpdateProducts200Item = {
    id: string;
    name?: string;
    sku?: PutApiUpdateProducts200ItemSku;
    categoryId?: PutApiUpdateProducts200ItemCategoryId;
    price?: PutApiUpdateProducts200ItemPrice;
    costPrice?: PutApiUpdateProducts200ItemCostPrice;
};
