/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiServiceSubscriptionId200DataSubscriptionStatus =
    (typeof PutApiServiceSubscriptionId200DataSubscriptionStatus)[keyof typeof PutApiServiceSubscriptionId200DataSubscriptionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiServiceSubscriptionId200DataSubscriptionStatus = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
} as const;
