/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId500Error } from './putApiEditSalesId500Error';

export type PutApiEditSalesId500 = {
    statusCode: number;
    error: PutApiEditSalesId500Error;
    message: string;
};
