/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiGiftCardsSettings200GiftCardAttachmentAnyOfAnyOfDeletedAt } from './putApiGiftCardsSettings200GiftCardAttachmentAnyOfAnyOfDeletedAt';

export type PutApiGiftCardsSettings200GiftCardAttachmentAnyOfAnyOf = {
    id: number;
    file_name: string;
    url: string;
    created_at: string;
    updated_at: string;
    deleted_at: PutApiGiftCardsSettings200GiftCardAttachmentAnyOfAnyOfDeletedAt;
    denmark_created_at: string;
};
