/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationTemplateId404Error } from './putApiHealthDeclarationTemplateId404Error';

export type PutApiHealthDeclarationTemplateId404 = {
    statusCode: number;
    error: PutApiHealthDeclarationTemplateId404Error;
    message: string;
};
