/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiHealthDeclarationId404Error =
    (typeof PutApiHealthDeclarationId404Error)[keyof typeof PutApiHealthDeclarationId404Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiHealthDeclarationId404Error = {
    Bad_Request: 'Bad Request',
} as const;
