/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiServiceSubscriptionId200DataSubscriptionStatus } from './putApiServiceSubscriptionId200DataSubscriptionStatus';
import type { PutApiServiceSubscriptionId200DataCreatedByBookingId } from './putApiServiceSubscriptionId200DataCreatedByBookingId';

export type PutApiServiceSubscriptionId200Data = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    serviceId: number;
    serviceName: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletCustomerId: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    subscriptionCredit: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    subscriptionCreditUsed: number;
    subscriptionStatus: PutApiServiceSubscriptionId200DataSubscriptionStatus;
    subscriptionStartDate: string;
    subscriptionEndDate: string;
    createdByBookingId: PutApiServiceSubscriptionId200DataCreatedByBookingId;
    createdAt: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    createdBy: number;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    updatedBy: number;
    updatedAt: string;
};
