/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationTemplateId200DataDescription } from './putApiHealthDeclarationTemplateId200DataDescription';
import type { PutApiHealthDeclarationTemplateId200DataContent } from './putApiHealthDeclarationTemplateId200DataContent';

export type PutApiHealthDeclarationTemplateId200Data = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    name: string;
    description: PutApiHealthDeclarationTemplateId200DataDescription;
    content?: PutApiHealthDeclarationTemplateId200DataContent;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    outletId: number;
    createdAt: string;
    updatedAt: string;
};
