/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId400Error } from './putApiEditSalesId400Error';

export type PutApiEditSalesId400 = {
    statusCode: number;
    error: PutApiEditSalesId400Error;
    message: string;
};
