/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PutApiGiftCardsSettingsBodyGiftCardAttachment = {
    id?: number;
    created_at?: string;
    deleted_at?: string;
    url?: string;
    file_name?: string;
    updated_at?: string;
    denmark_created_at?: string;
} | null;
