/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiPaymentsSubscriptionEdit200Data = {
    id?: string;
    outletId?: number;
    status?: string;
    subscriptionType?: string;
    startDate?: string;
    durationMonths?: number;
    lastBillingDate?: string;
    amount?: number;
    createdAt?: string;
    updatedAt?: string;
};
