/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiEditSalesIdBodyDataItemsItemItemType =
    (typeof PutApiEditSalesIdBodyDataItemsItemItemType)[keyof typeof PutApiEditSalesIdBodyDataItemsItemItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiEditSalesIdBodyDataItemsItemItemType = {
    SERVICE: 'SERVICE',
    PRODUCT: 'PRODUCT',
    GIFT_CARD: 'GIFT_CARD',
    OUTSTANDING: 'OUTSTANDING',
    CUT_CARD: 'CUT_CARD',
    BONUS: 'BONUS',
} as const;
