/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiEditSalesId200DataItemsItemDiscountsItemAmountType =
    (typeof PutApiEditSalesId200DataItemsItemDiscountsItemAmountType)[keyof typeof PutApiEditSalesId200DataItemsItemDiscountsItemAmountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiEditSalesId200DataItemsItemDiscountsItemAmountType = {
    AMOUNT: 'AMOUNT',
    PERCENTAGE: 'PERCENTAGE',
    VARIABLE_AMOUNT: 'VARIABLE_AMOUNT',
    VARIABLE_PERCENTAGE: 'VARIABLE_PERCENTAGE',
} as const;
