/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiEditSalesId400Error = (typeof PutApiEditSalesId400Error)[keyof typeof PutApiEditSalesId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiEditSalesId400Error = {
    Bad_Request: 'Bad Request',
} as const;
