/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationTemplateId200DataContentAnyOf } from './putApiHealthDeclarationTemplateId200DataContentAnyOf';

export type PutApiHealthDeclarationTemplateId200DataContent =
    PutApiHealthDeclarationTemplateId200DataContentAnyOf | null;
