/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiExpenseId500Error = (typeof PutApiExpenseId500Error)[keyof typeof PutApiExpenseId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiExpenseId500Error = {
    Bad_Request: 'Bad Request',
} as const;
