/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId200DataRequestContent } from './putApiHealthDeclarationId200DataRequestContent';
import type { PutApiHealthDeclarationId200DataResponseContent } from './putApiHealthDeclarationId200DataResponseContent';
import type { PutApiHealthDeclarationId200DataReviewedBy } from './putApiHealthDeclarationId200DataReviewedBy';
import type { PutApiHealthDeclarationId200DataResendBy } from './putApiHealthDeclarationId200DataResendBy';

export type PutApiHealthDeclarationId200Data = {
    id?: string;
    seqId?: number;
    status?: string;
    bookingId?: number;
    templateId?: string;
    requestContent?: PutApiHealthDeclarationId200DataRequestContent;
    /** @nullable */
    responseContent?: PutApiHealthDeclarationId200DataResponseContent;
    outletId?: number;
    /** @nullable */
    reviewedBy?: PutApiHealthDeclarationId200DataReviewedBy;
    /** @nullable */
    reviewedAt?: string | null;
    /** @nullable */
    resendBy?: PutApiHealthDeclarationId200DataResendBy;
    /** @nullable */
    resendAt?: string | null;
    /** @nullable */
    submittedAt?: string | null;
    /** @nullable */
    outletCustomerId?: number | null;
    createdAt?: string;
    updatedAt?: string;
    /** @nullable */
    deletedAt?: string | null;
};
