/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Waiting period in hours before sending to same customer again. Optional.
 */
export type PutApiCampaignsIdBodyScheduleWaitingPeriod = number | null;
