/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiIotDevicesDeviceId200Status =
    (typeof PutApiIotDevicesDeviceId200Status)[keyof typeof PutApiIotDevicesDeviceId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiIotDevicesDeviceId200Status = {
    CONNECTED: 'CONNECTED',
    DISCONNECTED: 'DISCONNECTED',
} as const;
