/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiServicesEmployeeAssignEmployeeId500Error } from './putApiServicesEmployeeAssignEmployeeId500Error';

export type PutApiServicesEmployeeAssignEmployeeId500 = {
    statusCode: number;
    error: PutApiServicesEmployeeAssignEmployeeId500Error;
    message: string;
};
