/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId200DataPaymentItemCustomerId } from './putApiEditSalesId200DataPaymentItemCustomerId';
import type { PutApiEditSalesId200DataPaymentItemPaymentId } from './putApiEditSalesId200DataPaymentItemPaymentId';
import type { PutApiEditSalesId200DataPaymentItemTerminalId } from './putApiEditSalesId200DataPaymentItemTerminalId';
import type { PutApiEditSalesId200DataPaymentItemTerminalRefId } from './putApiEditSalesId200DataPaymentItemTerminalRefId';
import type { PutApiEditSalesId200DataPaymentItemTerminalStatus } from './putApiEditSalesId200DataPaymentItemTerminalStatus';
import type { PutApiEditSalesId200DataPaymentItemCardType } from './putApiEditSalesId200DataPaymentItemCardType';
import type { PutApiEditSalesId200DataPaymentItemCardFourDigit } from './putApiEditSalesId200DataPaymentItemCardFourDigit';
import type { PutApiEditSalesId200DataPaymentItemTransactionType } from './putApiEditSalesId200DataPaymentItemTransactionType';
import type { PutApiEditSalesId200DataPaymentItemDeletedAt } from './putApiEditSalesId200DataPaymentItemDeletedAt';

export type PutApiEditSalesId200DataPaymentItem = {
    id?: string;
    seqId?: number;
    salesId?: string;
    outletId?: number;
    customerId?: PutApiEditSalesId200DataPaymentItemCustomerId;
    paymentId?: PutApiEditSalesId200DataPaymentItemPaymentId;
    receiptId?: string;
    currency?: string;
    amount?: number;
    tenderAmount?: number;
    change?: number;
    txStatus?: string;
    terminalId?: PutApiEditSalesId200DataPaymentItemTerminalId;
    terminalRefId?: PutApiEditSalesId200DataPaymentItemTerminalRefId;
    terminalStatus?: PutApiEditSalesId200DataPaymentItemTerminalStatus;
    cardType?: PutApiEditSalesId200DataPaymentItemCardType;
    cardFourDigit?: PutApiEditSalesId200DataPaymentItemCardFourDigit;
    paymentType?: string;
    transactionType?: PutApiEditSalesId200DataPaymentItemTransactionType;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: PutApiEditSalesId200DataPaymentItemDeletedAt;
};
