/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiHealthDeclarationIdBodyStatus =
    (typeof PutApiHealthDeclarationIdBodyStatus)[keyof typeof PutApiHealthDeclarationIdBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiHealthDeclarationIdBodyStatus = {
    NOT_REQUIRED: 'NOT_REQUIRED',
    SCHEDULED: 'SCHEDULED',
    SENT: 'SENT',
    COMPLETED: 'COMPLETED',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
    RESENT: 'RESENT',
    CREATED: 'CREATED',
    REMINDER_SENT: 'REMINDER_SENT',
    REMINDER_SENT_CONFLICT: 'REMINDER_SENT_CONFLICT',
    SUBMITTED: 'SUBMITTED',
    REVIEWED: 'REVIEWED',
} as const;
