/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiUpdateProducts200ItemPriceAnyOf } from './putApiUpdateProducts200ItemPriceAnyOf';

export type PutApiUpdateProducts200ItemPrice = PutApiUpdateProducts200ItemPriceAnyOf | null;
