/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiIotDevicesDeviceIdBody = {
    /**
     * @minLength 1
     * @maxLength 255
     */
    deviceMAC: string;
};
