/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId200DataItemsItemDiscountsItemDiscountId } from './putApiEditSalesId200DataItemsItemDiscountsItemDiscountId';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemCouponId } from './putApiEditSalesId200DataItemsItemDiscountsItemCouponId';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemDiscountName } from './putApiEditSalesId200DataItemsItemDiscountsItemDiscountName';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemDiscountAmount } from './putApiEditSalesId200DataItemsItemDiscountsItemDiscountAmount';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemAmountType } from './putApiEditSalesId200DataItemsItemDiscountsItemAmountType';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemAmount } from './putApiEditSalesId200DataItemsItemDiscountsItemAmount';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemCreatedAt } from './putApiEditSalesId200DataItemsItemDiscountsItemCreatedAt';
import type { PutApiEditSalesId200DataItemsItemDiscountsItemUpdatedAt } from './putApiEditSalesId200DataItemsItemDiscountsItemUpdatedAt';

export type PutApiEditSalesId200DataItemsItemDiscountsItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesDetailId: string;
    discountId: PutApiEditSalesId200DataItemsItemDiscountsItemDiscountId;
    couponId: PutApiEditSalesId200DataItemsItemDiscountsItemCouponId;
    discountName: PutApiEditSalesId200DataItemsItemDiscountsItemDiscountName;
    discountAmount: PutApiEditSalesId200DataItemsItemDiscountsItemDiscountAmount;
    amountType: PutApiEditSalesId200DataItemsItemDiscountsItemAmountType;
    amount: PutApiEditSalesId200DataItemsItemDiscountsItemAmount;
    createdAt: PutApiEditSalesId200DataItemsItemDiscountsItemCreatedAt;
    updatedAt: PutApiEditSalesId200DataItemsItemDiscountsItemUpdatedAt;
};
