/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiPaymentsSubscriptionEdit404Error } from './putApiPaymentsSubscriptionEdit404Error';

export type PutApiPaymentsSubscriptionEdit404 = {
    statusCode: number;
    error: PutApiPaymentsSubscriptionEdit404Error;
    message: string;
};
