/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiEditSalesId500Error = (typeof PutApiEditSalesId500Error)[keyof typeof PutApiEditSalesId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiEditSalesId500Error = {
    Bad_Request: 'Bad Request',
} as const;
