/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId400Error } from './putApiHealthDeclarationId400Error';

export type PutApiHealthDeclarationId400 = {
    statusCode: number;
    error: PutApiHealthDeclarationId400Error;
    message: string;
};
