/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiEditSalesIdBodyDataItemsItemSaleType =
    (typeof PutApiEditSalesIdBodyDataItemsItemSaleType)[keyof typeof PutApiEditSalesIdBodyDataItemsItemSaleType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiEditSalesIdBodyDataItemsItemSaleType = {
    SALE: 'SALE',
    RETURN: 'RETURN',
} as const;
