/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiSupplierId400Error = (typeof PutApiSupplierId400Error)[keyof typeof PutApiSupplierId400Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiSupplierId400Error = {
    Bad_Request: 'Bad Request',
} as const;
