/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiServiceSubscriptionIdBodySubscriptionStatus =
    (typeof PutApiServiceSubscriptionIdBodySubscriptionStatus)[keyof typeof PutApiServiceSubscriptionIdBodySubscriptionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiServiceSubscriptionIdBodySubscriptionStatus = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
} as const;
