/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiDineroConfig200DataCoaConfiguration } from './putApiDineroConfig200DataCoaConfiguration';

export type PutApiDineroConfig200Data = {
    coaConfiguration?: PutApiDineroConfig200DataCoaConfiguration;
    sendEmailFromDinero?: boolean;
};
