/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesIdBodyDataPaymentItemBunddleOfferServicesItem } from './putApiEditSalesIdBodyDataPaymentItemBunddleOfferServicesItem';

export type PutApiEditSalesIdBodyDataPaymentItemBunddleOffer = {
    bundleOfferId: string;
    services: PutApiEditSalesIdBodyDataPaymentItemBunddleOfferServicesItem[];
};
