/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesIdBodyDataSalesTaxesItemTaxId } from './putApiEditSalesIdBodyDataSalesTaxesItemTaxId';
import type { PutApiEditSalesIdBodyDataSalesTaxesItemTaxName } from './putApiEditSalesIdBodyDataSalesTaxesItemTaxName';

export type PutApiEditSalesIdBodyDataSalesTaxesItem = {
    taxId?: PutApiEditSalesIdBodyDataSalesTaxesItemTaxId;
    taxName?: PutApiEditSalesIdBodyDataSalesTaxesItemTaxName;
    taxRate?: number;
    taxAmount?: number;
    includeTaxInItemPrice?: boolean;
    isInclusive?: boolean;
};
