/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiDiscountId500Error } from './putApiDiscountId500Error';

export type PutApiDiscountId500 = {
    statusCode: number;
    error: PutApiDiscountId500Error;
    message: string;
};
