/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId404Error } from './putApiHealthDeclarationId404Error';

export type PutApiHealthDeclarationId404 = {
    statusCode: number;
    error: PutApiHealthDeclarationId404Error;
    message: string;
};
