/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiCustomerGroupsId200OutletId } from './putApiCustomerGroupsId200OutletId';
import type { PutApiCustomerGroupsId200Description } from './putApiCustomerGroupsId200Description';
import type { PutApiCustomerGroupsId200CreatedBy } from './putApiCustomerGroupsId200CreatedBy';
import type { PutApiCustomerGroupsId200UpdatedBy } from './putApiCustomerGroupsId200UpdatedBy';
import type { PutApiCustomerGroupsId200DeletedAt } from './putApiCustomerGroupsId200DeletedAt';

export type PutApiCustomerGroupsId200 = {
    id: string;
    outletId?: PutApiCustomerGroupsId200OutletId;
    name: string;
    description?: PutApiCustomerGroupsId200Description;
    createdAt: string;
    createdBy?: PutApiCustomerGroupsId200CreatedBy;
    updatedAt: string;
    updatedBy?: PutApiCustomerGroupsId200UpdatedBy;
    deletedAt?: PutApiCustomerGroupsId200DeletedAt;
    isActive: boolean;
    customerCount?: number;
};
