/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiBundleOffersSettingsBody = {
    /** Array of tax IDs that can be applied */
    taxIds?: string[];
    /** Whether to send design by sale */
    sendDesignBySale?: boolean;
    /**
     * Color of bundle offer cards (hex format)
     * @pattern ^#[0-9A-F]{6}$
     */
    cardColor?: string;
    /** Personal message template */
    personalMessage?: string;
    /** Description for online sales */
    onlineSaleDescription?: string;
    /** Whether to show service on design */
    showServiceOnDesign?: boolean;
};
