/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId200DataResendByAnyOf } from './putApiHealthDeclarationId200DataResendByAnyOf';

/**
 * @nullable
 */
export type PutApiHealthDeclarationId200DataResendBy = null | PutApiHealthDeclarationId200DataResendByAnyOf | null;
