/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiProductCategoriesId500Error } from './putApiProductCategoriesId500Error';

export type PutApiProductCategoriesId500 = {
    statusCode: number;
    error: PutApiProductCategoriesId500Error;
    message: string;
};
