/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiServiceSubscriptionId404Error } from './putApiServiceSubscriptionId404Error';

export type PutApiServiceSubscriptionId404 = {
    statusCode: number;
    error: PutApiServiceSubscriptionId404Error;
    message: string;
};
