/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiUpdateProductsBodyDataItemPriceAnyOf } from './putApiUpdateProductsBodyDataItemPriceAnyOf';

export type PutApiUpdateProductsBodyDataItemPrice = PutApiUpdateProductsBodyDataItemPriceAnyOf | null;
