/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiUpdateProducts500Error =
    (typeof PutApiUpdateProducts500Error)[keyof typeof PutApiUpdateProducts500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiUpdateProducts500Error = {
    Bad_Request: 'Bad Request',
} as const;
