/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationId200DataResendByAnyOfEmployeeName } from './putApiHealthDeclarationId200DataResendByAnyOfEmployeeName';

/**
 * @nullable
 */
export type PutApiHealthDeclarationId200DataResendByAnyOf = {
    employeeId?: number;
    employeeName?: PutApiHealthDeclarationId200DataResendByAnyOfEmployeeName;
} | null;
