/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiServicesEmployeeAssignEmployeeId500Error =
    (typeof PutApiServicesEmployeeAssignEmployeeId500Error)[keyof typeof PutApiServicesEmployeeAssignEmployeeId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiServicesEmployeeAssignEmployeeId500Error = {
    Bad_Request: 'Bad Request',
} as const;
