/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiServiceSubscriptionId400Error } from './putApiServiceSubscriptionId400Error';

export type PutApiServiceSubscriptionId400 = {
    statusCode: number;
    error: PutApiServiceSubscriptionId400Error;
    message: string;
};
