/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesIdBodyDataItemsItemProductId } from './putApiEditSalesIdBodyDataItemsItemProductId';
import type { PutApiEditSalesIdBodyDataItemsItemBundleOfferId } from './putApiEditSalesIdBodyDataItemsItemBundleOfferId';
import type { PutApiEditSalesIdBodyDataItemsItemServiceId } from './putApiEditSalesIdBodyDataItemsItemServiceId';
import type { PutApiEditSalesIdBodyDataItemsItemEmployeeId } from './putApiEditSalesIdBodyDataItemsItemEmployeeId';
import type { PutApiEditSalesIdBodyDataItemsItemItemType } from './putApiEditSalesIdBodyDataItemsItemItemType';
import type { PutApiEditSalesIdBodyDataItemsItemSaleType } from './putApiEditSalesIdBodyDataItemsItemSaleType';
import type { PutApiEditSalesIdBodyDataItemsItemItemImageUrl } from './putApiEditSalesIdBodyDataItemsItemItemImageUrl';
import type { PutApiEditSalesIdBodyDataItemsItemUnitId } from './putApiEditSalesIdBodyDataItemsItemUnitId';
import type { PutApiEditSalesIdBodyDataItemsItemUnitName } from './putApiEditSalesIdBodyDataItemsItemUnitName';
import type { PutApiEditSalesIdBodyDataItemsItemUnitAbbreviation } from './putApiEditSalesIdBodyDataItemsItemUnitAbbreviation';
import type { PutApiEditSalesIdBodyDataItemsItemCategoryId } from './putApiEditSalesIdBodyDataItemsItemCategoryId';
import type { PutApiEditSalesIdBodyDataItemsItemDiscountType } from './putApiEditSalesIdBodyDataItemsItemDiscountType';
import type { PutApiEditSalesIdBodyDataItemsItemTaxesItem } from './putApiEditSalesIdBodyDataItemsItemTaxesItem';
import type { PutApiEditSalesIdBodyDataItemsItemGiftCard } from './putApiEditSalesIdBodyDataItemsItemGiftCard';
import type { PutApiEditSalesIdBodyDataItemsItemDiscountsItem } from './putApiEditSalesIdBodyDataItemsItemDiscountsItem';

export type PutApiEditSalesIdBodyDataItemsItem = {
    productId?: PutApiEditSalesIdBodyDataItemsItemProductId;
    bundleOfferId?: PutApiEditSalesIdBodyDataItemsItemBundleOfferId;
    serviceId?: PutApiEditSalesIdBodyDataItemsItemServiceId;
    employeeId?: PutApiEditSalesIdBodyDataItemsItemEmployeeId;
    itemName?: string;
    itemType?: PutApiEditSalesIdBodyDataItemsItemItemType;
    saleType?: PutApiEditSalesIdBodyDataItemsItemSaleType;
    quantity: number;
    amount: number;
    discountAmount?: number;
    /**
     * @minimum -140737488355328
     * @maximum 140737488355327
     */
    taxAmount?: number;
    price: number;
    note?: string;
    description?: string;
    itemImageUrl?: PutApiEditSalesIdBodyDataItemsItemItemImageUrl;
    unitId?: PutApiEditSalesIdBodyDataItemsItemUnitId;
    unitName?: PutApiEditSalesIdBodyDataItemsItemUnitName;
    unitAbbreviation?: PutApiEditSalesIdBodyDataItemsItemUnitAbbreviation;
    categoryId?: PutApiEditSalesIdBodyDataItemsItemCategoryId;
    categoryName?: string;
    discountType?: PutApiEditSalesIdBodyDataItemsItemDiscountType;
    salesDetailId?: string;
    taxes?: PutApiEditSalesIdBodyDataItemsItemTaxesItem[];
    giftCard?: PutApiEditSalesIdBodyDataItemsItemGiftCard;
    discounts?: PutApiEditSalesIdBodyDataItemsItemDiscountsItem[];
    [key: string]: unknown;
};
