/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesIdBodyDataItemsItemGiftCardAnyOfGiftCardCode } from './putApiEditSalesIdBodyDataItemsItemGiftCardAnyOfGiftCardCode';

export type PutApiEditSalesIdBodyDataItemsItemGiftCardAnyOf = {
    /** @maxLength 256 */
    recipientName?: string;
    giftCardCode?: PutApiEditSalesIdBodyDataItemsItemGiftCardAnyOfGiftCardCode;
    /**
     * @minimum 1
     */
    amount?: number;
    applicableServiceIds?: string[];
};
