/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiSupplierId500Error = (typeof PutApiSupplierId500Error)[keyof typeof PutApiSupplierId500Error];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiSupplierId500Error = {
    Bad_Request: 'Bad Request',
} as const;
