/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId200Data } from './putApiEditSalesId200Data';

export type PutApiEditSalesId200 = {
    data: PutApiEditSalesId200Data;
    msg: string;
    success: boolean;
};
