/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHealthDeclarationTemplateId500Error } from './putApiHealthDeclarationTemplateId500Error';

export type PutApiHealthDeclarationTemplateId500 = {
    statusCode: number;
    error: PutApiHealthDeclarationTemplateId500Error;
    message: string;
};
