/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiEditSalesId200DataSalesDiscountsItemDiscountId } from './putApiEditSalesId200DataSalesDiscountsItemDiscountId';
import type { PutApiEditSalesId200DataSalesDiscountsItemCouponId } from './putApiEditSalesId200DataSalesDiscountsItemCouponId';
import type { PutApiEditSalesId200DataSalesDiscountsItemDiscountName } from './putApiEditSalesId200DataSalesDiscountsItemDiscountName';
import type { PutApiEditSalesId200DataSalesDiscountsItemDiscountAmount } from './putApiEditSalesId200DataSalesDiscountsItemDiscountAmount';
import type { PutApiEditSalesId200DataSalesDiscountsItemAmountType } from './putApiEditSalesId200DataSalesDiscountsItemAmountType';
import type { PutApiEditSalesId200DataSalesDiscountsItemAmount } from './putApiEditSalesId200DataSalesDiscountsItemAmount';
import type { PutApiEditSalesId200DataSalesDiscountsItemCreatedAt } from './putApiEditSalesId200DataSalesDiscountsItemCreatedAt';
import type { PutApiEditSalesId200DataSalesDiscountsItemUpdatedAt } from './putApiEditSalesId200DataSalesDiscountsItemUpdatedAt';

export type PutApiEditSalesId200DataSalesDiscountsItem = {
    id: string;
    /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
    seqId: number;
    salesDetailId: string;
    discountId: PutApiEditSalesId200DataSalesDiscountsItemDiscountId;
    couponId: PutApiEditSalesId200DataSalesDiscountsItemCouponId;
    discountName: PutApiEditSalesId200DataSalesDiscountsItemDiscountName;
    discountAmount: PutApiEditSalesId200DataSalesDiscountsItemDiscountAmount;
    amountType: PutApiEditSalesId200DataSalesDiscountsItemAmountType;
    amount: PutApiEditSalesId200DataSalesDiscountsItemAmount;
    createdAt: PutApiEditSalesId200DataSalesDiscountsItemCreatedAt;
    updatedAt: PutApiEditSalesId200DataSalesDiscountsItemUpdatedAt;
};
